/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppApiExecutivePictureOrderBy,
  AppApiVendorRoleMapOrderIn,
  ErrorResponse,
  ExecutiveImageSchema,
  HTTPValidationError,
} from '../models/index';
import {
    AppApiExecutivePictureOrderByFromJSON,
    AppApiExecutivePictureOrderByToJSON,
    AppApiVendorRoleMapOrderInFromJSON,
    AppApiVendorRoleMapOrderInToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ExecutiveImageSchemaFromJSON,
    ExecutiveImageSchemaToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface DeleteExecutivePictureEntebusAccountPictureDeleteRequest {
    id?: number | null;
}

export interface DownloadExecutivePictureEntebusAccountPictureIdGetRequest {
    id: number;
    width?: number | null;
    height?: number | null;
}

export interface FetchExecutivePicturesEntebusAccountPictureGetRequest {
    executiveId?: number | null;
    fileName?: string | null;
    fileType?: string | null;
    fileSizeGe?: number | null;
    fileSizeLe?: number | null;
    id?: number | null;
    idGe?: number | null;
    idLe?: number | null;
    idList?: Array<number> | null;
    createdOnGe?: Date | null;
    createdOnLe?: Date | null;
    orderBy?: AppApiExecutivePictureOrderBy;
    orderIn?: AppApiVendorRoleMapOrderIn;
    offset?: number;
    limit?: number;
}

export interface UploadExecutivePictureEntebusAccountPicturePostRequest {
    file: Blob;
    executiveId?: number | null;
}

/**
 * 
 */
export class AccountPictureApi extends runtime.BaseAPI {

    /**
     * Delete an executive\'s profile picture.       Executives can delete their own profile picture.          Authorized users with `update_executive` permission can update any executive profile picture.        Removes the image from `executive_pictures` bucket in MinIO and deletes metadata from executive_image table.
     * Delete Executive Picture
     */
    async deleteExecutivePictureEntebusAccountPictureDeleteRaw(requestParameters: DeleteExecutivePictureEntebusAccountPictureDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['id'] != null) {
            formParams.append('id', requestParameters['id'] as any);
        }


        let urlPath = `/entebus/account/picture`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an executive\'s profile picture.       Executives can delete their own profile picture.          Authorized users with `update_executive` permission can update any executive profile picture.        Removes the image from `executive_pictures` bucket in MinIO and deletes metadata from executive_image table.
     * Delete Executive Picture
     */
    async deleteExecutivePictureEntebusAccountPictureDelete(requestParameters: DeleteExecutivePictureEntebusAccountPictureDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteExecutivePictureEntebusAccountPictureDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Download executive profile picture in original or resized resolution.        Requires a valid executive token.        Return the image file from `executive_pictures` bucket in MinIO in original resolution or specified resolution.          Returns the original image file.
     * Download Executive Picture
     */
    async downloadExecutivePictureEntebusAccountPictureIdGetRaw(requestParameters: DownloadExecutivePictureEntebusAccountPictureIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling downloadExecutivePictureEntebusAccountPictureIdGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['width'] != null) {
            queryParameters['width'] = requestParameters['width'];
        }

        if (requestParameters['height'] != null) {
            queryParameters['height'] = requestParameters['height'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entebus/account/picture/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Download executive profile picture in original or resized resolution.        Requires a valid executive token.        Return the image file from `executive_pictures` bucket in MinIO in original resolution or specified resolution.          Returns the original image file.
     * Download Executive Picture
     */
    async downloadExecutivePictureEntebusAccountPictureIdGet(requestParameters: DownloadExecutivePictureEntebusAccountPictureIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.downloadExecutivePictureEntebusAccountPictureIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Fetch metadata of all executive profile pictures with filtering, sorting, and pagination.        Filter by file name file type, file size, id\'s and creation/update timestamps.        Filter by ID ranges or lists.        Sort by ID, creation date, or update date, file size in ascending or descending order.       Paginate using offset and limit.         Returns a list of executive profile pictures metadata, matching the criteria.
     * Fetch Executive Pictures
     */
    async fetchExecutivePicturesEntebusAccountPictureGetRaw(requestParameters: FetchExecutivePicturesEntebusAccountPictureGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ExecutiveImageSchema>>> {
        const queryParameters: any = {};

        if (requestParameters['executiveId'] != null) {
            queryParameters['executive_id'] = requestParameters['executiveId'];
        }

        if (requestParameters['fileName'] != null) {
            queryParameters['file_name'] = requestParameters['fileName'];
        }

        if (requestParameters['fileType'] != null) {
            queryParameters['file_type'] = requestParameters['fileType'];
        }

        if (requestParameters['fileSizeGe'] != null) {
            queryParameters['file_size_ge'] = requestParameters['fileSizeGe'];
        }

        if (requestParameters['fileSizeLe'] != null) {
            queryParameters['file_size_le'] = requestParameters['fileSizeLe'];
        }

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['idGe'] != null) {
            queryParameters['id_ge'] = requestParameters['idGe'];
        }

        if (requestParameters['idLe'] != null) {
            queryParameters['id_le'] = requestParameters['idLe'];
        }

        if (requestParameters['idList'] != null) {
            queryParameters['id_list'] = requestParameters['idList'];
        }

        if (requestParameters['createdOnGe'] != null) {
            queryParameters['created_on_ge'] = (requestParameters['createdOnGe'] as any).toISOString();
        }

        if (requestParameters['createdOnLe'] != null) {
            queryParameters['created_on_le'] = (requestParameters['createdOnLe'] as any).toISOString();
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['order_by'] = requestParameters['orderBy'];
        }

        if (requestParameters['orderIn'] != null) {
            queryParameters['order_in'] = requestParameters['orderIn'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entebus/account/picture`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ExecutiveImageSchemaFromJSON));
    }

    /**
     * Fetch metadata of all executive profile pictures with filtering, sorting, and pagination.        Filter by file name file type, file size, id\'s and creation/update timestamps.        Filter by ID ranges or lists.        Sort by ID, creation date, or update date, file size in ascending or descending order.       Paginate using offset and limit.         Returns a list of executive profile pictures metadata, matching the criteria.
     * Fetch Executive Pictures
     */
    async fetchExecutivePicturesEntebusAccountPictureGet(requestParameters: FetchExecutivePicturesEntebusAccountPictureGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ExecutiveImageSchema>> {
        const response = await this.fetchExecutivePicturesEntebusAccountPictureGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload the executive\'s profile picture.      Executives can update their own profile picture.          Authorized users with `update_executive` permission can update any executive profile picture.           Stores the image in the `executive_pictures` bucket in MinIO and saves the metadata in `executive_image` table.
     * Upload Executive Picture
     */
    async uploadExecutivePictureEntebusAccountPicturePostRaw(requestParameters: UploadExecutivePictureEntebusAccountPicturePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExecutiveImageSchema>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadExecutivePictureEntebusAccountPicturePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['executiveId'] != null) {
            formParams.append('executive_id', requestParameters['executiveId'] as any);
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/entebus/account/picture`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExecutiveImageSchemaFromJSON(jsonValue));
    }

    /**
     * Upload the executive\'s profile picture.      Executives can update their own profile picture.          Authorized users with `update_executive` permission can update any executive profile picture.           Stores the image in the `executive_pictures` bucket in MinIO and saves the metadata in `executive_image` table.
     * Upload Executive Picture
     */
    async uploadExecutivePictureEntebusAccountPicturePost(requestParameters: UploadExecutivePictureEntebusAccountPicturePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExecutiveImageSchema> {
        const response = await this.uploadExecutivePictureEntebusAccountPicturePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
