/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccountStatus,
  AppApiExecutiveAccountOrderBy,
  AppApiVendorRoleMapOrderIn,
  ErrorResponse,
  ExecutiveSchema,
  GenderType,
  HTTPValidationError,
} from '../models/index';
import {
    AccountStatusFromJSON,
    AccountStatusToJSON,
    AppApiExecutiveAccountOrderByFromJSON,
    AppApiExecutiveAccountOrderByToJSON,
    AppApiVendorRoleMapOrderInFromJSON,
    AppApiVendorRoleMapOrderInToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ExecutiveSchemaFromJSON,
    ExecutiveSchemaToJSON,
    GenderTypeFromJSON,
    GenderTypeToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CreateExecutiveEntebusAccountPostRequest {
    username: string;
    password: string;
    gender?: GenderType;
    fullName?: string | null;
    designation?: string | null;
    phoneNumber?: string | null;
    emailId?: string | null;
}

export interface DeleteExecutiveEntebusAccountDeleteRequest {
    id: number;
}

export interface FetchExecutiveEntebusAccountGetRequest {
    username?: string | null;
    gender?: GenderType | null;
    fullName?: string | null;
    designation?: string | null;
    phoneNumber?: string | null;
    emailId?: string | null;
    status?: AccountStatus | null;
    id?: number | null;
    idGe?: number | null;
    idLe?: number | null;
    idList?: Array<number> | null;
    updatedOnGe?: Date | null;
    updatedOnLe?: Date | null;
    createdOnGe?: Date | null;
    createdOnLe?: Date | null;
    orderBy?: AppApiExecutiveAccountOrderBy;
    orderIn?: AppApiVendorRoleMapOrderIn;
    offset?: number;
    limit?: number;
}

export interface UpdateExecutiveEntebusAccountPatchRequest {
    id?: number | null;
    password?: string | null;
    gender?: GenderType | null;
    fullName?: string | null;
    designation?: string | null;
    phoneNumber?: string | null;
    emailId?: string | null;
    status?: AccountStatus | null;
}

/**
 * 
 */
export class AccountApi extends runtime.BaseAPI {

    /**
     * Create a new executive account.          Only authorized users with `create_executive` permission can create a new executive.         The password is hashed using Argon2 before storing.          Duplicate usernames are not allowed.
     * Create Executive
     */
    async createExecutiveEntebusAccountPostRaw(requestParameters: CreateExecutiveEntebusAccountPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExecutiveSchema>> {
        if (requestParameters['username'] == null) {
            throw new runtime.RequiredError(
                'username',
                'Required parameter "username" was null or undefined when calling createExecutiveEntebusAccountPost().'
            );
        }

        if (requestParameters['password'] == null) {
            throw new runtime.RequiredError(
                'password',
                'Required parameter "password" was null or undefined when calling createExecutiveEntebusAccountPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['username'] != null) {
            formParams.append('username', requestParameters['username'] as any);
        }

        if (requestParameters['password'] != null) {
            formParams.append('password', requestParameters['password'] as any);
        }

        if (requestParameters['gender'] != null) {
            formParams.append('gender', requestParameters['gender'] as any);
        }

        if (requestParameters['fullName'] != null) {
            formParams.append('full_name', requestParameters['fullName'] as any);
        }

        if (requestParameters['designation'] != null) {
            formParams.append('designation', requestParameters['designation'] as any);
        }

        if (requestParameters['phoneNumber'] != null) {
            formParams.append('phone_number', requestParameters['phoneNumber'] as any);
        }

        if (requestParameters['emailId'] != null) {
            formParams.append('email_id', requestParameters['emailId'] as any);
        }


        let urlPath = `/entebus/account`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExecutiveSchemaFromJSON(jsonValue));
    }

    /**
     * Create a new executive account.          Only authorized users with `create_executive` permission can create a new executive.         The password is hashed using Argon2 before storing.          Duplicate usernames are not allowed.
     * Create Executive
     */
    async createExecutiveEntebusAccountPost(requestParameters: CreateExecutiveEntebusAccountPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExecutiveSchema> {
        const response = await this.createExecutiveEntebusAccountPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an executive account.         Only users with the `delete_executive` permission can delete executive accounts.         Self-deletion is not allowed for safety reasons.         If the specified executive exists, it will be deleted permanently.       If the specified executive has a profile picture, it will be deleted permanently.        The deleted account details are logged for audit purposes.
     * Delete Executive
     */
    async deleteExecutiveEntebusAccountDeleteRaw(requestParameters: DeleteExecutiveEntebusAccountDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteExecutiveEntebusAccountDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['id'] != null) {
            formParams.append('id', requestParameters['id'] as any);
        }


        let urlPath = `/entebus/account`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an executive account.         Only users with the `delete_executive` permission can delete executive accounts.         Self-deletion is not allowed for safety reasons.         If the specified executive exists, it will be deleted permanently.       If the specified executive has a profile picture, it will be deleted permanently.        The deleted account details are logged for audit purposes.
     * Delete Executive
     */
    async deleteExecutiveEntebusAccountDelete(requestParameters: DeleteExecutiveEntebusAccountDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteExecutiveEntebusAccountDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Fetch executive accounts with filtering, sorting, and pagination.        Filter by username, gender, designation, contact details, status, and creation/update timestamps.        Filter by ID ranges or lists.        Sort by ID, creation date, or update date in ascending or descending order.      Paginate using offset and limit.         Returns a list of executive accounts matching the criteria.
     * Fetch Executive
     */
    async fetchExecutiveEntebusAccountGetRaw(requestParameters: FetchExecutiveEntebusAccountGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ExecutiveSchema>>> {
        const queryParameters: any = {};

        if (requestParameters['username'] != null) {
            queryParameters['username'] = requestParameters['username'];
        }

        if (requestParameters['gender'] != null) {
            queryParameters['gender'] = requestParameters['gender'];
        }

        if (requestParameters['fullName'] != null) {
            queryParameters['full_name'] = requestParameters['fullName'];
        }

        if (requestParameters['designation'] != null) {
            queryParameters['designation'] = requestParameters['designation'];
        }

        if (requestParameters['phoneNumber'] != null) {
            queryParameters['phone_number'] = requestParameters['phoneNumber'];
        }

        if (requestParameters['emailId'] != null) {
            queryParameters['email_id'] = requestParameters['emailId'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['idGe'] != null) {
            queryParameters['id_ge'] = requestParameters['idGe'];
        }

        if (requestParameters['idLe'] != null) {
            queryParameters['id_le'] = requestParameters['idLe'];
        }

        if (requestParameters['idList'] != null) {
            queryParameters['id_list'] = requestParameters['idList'];
        }

        if (requestParameters['updatedOnGe'] != null) {
            queryParameters['updated_on_ge'] = (requestParameters['updatedOnGe'] as any).toISOString();
        }

        if (requestParameters['updatedOnLe'] != null) {
            queryParameters['updated_on_le'] = (requestParameters['updatedOnLe'] as any).toISOString();
        }

        if (requestParameters['createdOnGe'] != null) {
            queryParameters['created_on_ge'] = (requestParameters['createdOnGe'] as any).toISOString();
        }

        if (requestParameters['createdOnLe'] != null) {
            queryParameters['created_on_le'] = (requestParameters['createdOnLe'] as any).toISOString();
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['order_by'] = requestParameters['orderBy'];
        }

        if (requestParameters['orderIn'] != null) {
            queryParameters['order_in'] = requestParameters['orderIn'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entebus/account`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ExecutiveSchemaFromJSON));
    }

    /**
     * Fetch executive accounts with filtering, sorting, and pagination.        Filter by username, gender, designation, contact details, status, and creation/update timestamps.        Filter by ID ranges or lists.        Sort by ID, creation date, or update date in ascending or descending order.      Paginate using offset and limit.         Returns a list of executive accounts matching the criteria.
     * Fetch Executive
     */
    async fetchExecutiveEntebusAccountGet(requestParameters: FetchExecutiveEntebusAccountGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ExecutiveSchema>> {
        const response = await this.fetchExecutiveEntebusAccountGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an existing executive account.        Executives can update their own account but cannot update their own status.          Authorized users with `update_executive` permission can update any executive.        Password changes are securely hashed.        Modifications are only saved if changes are detected.
     * Update Executive
     */
    async updateExecutiveEntebusAccountPatchRaw(requestParameters: UpdateExecutiveEntebusAccountPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExecutiveSchema>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['id'] != null) {
            formParams.append('id', requestParameters['id'] as any);
        }

        if (requestParameters['password'] != null) {
            formParams.append('password', requestParameters['password'] as any);
        }

        if (requestParameters['gender'] != null) {
            formParams.append('gender', requestParameters['gender'] as any);
        }

        if (requestParameters['fullName'] != null) {
            formParams.append('full_name', requestParameters['fullName'] as any);
        }

        if (requestParameters['designation'] != null) {
            formParams.append('designation', requestParameters['designation'] as any);
        }

        if (requestParameters['phoneNumber'] != null) {
            formParams.append('phone_number', requestParameters['phoneNumber'] as any);
        }

        if (requestParameters['emailId'] != null) {
            formParams.append('email_id', requestParameters['emailId'] as any);
        }

        if (requestParameters['status'] != null) {
            formParams.append('status', requestParameters['status'] as any);
        }


        let urlPath = `/entebus/account`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExecutiveSchemaFromJSON(jsonValue));
    }

    /**
     * Update an existing executive account.        Executives can update their own account but cannot update their own status.          Authorized users with `update_executive` permission can update any executive.        Password changes are securely hashed.        Modifications are only saved if changes are detected.
     * Update Executive
     */
    async updateExecutiveEntebusAccountPatch(requestParameters: UpdateExecutiveEntebusAccountPatchRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExecutiveSchema> {
        const response = await this.updateExecutiveEntebusAccountPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
