/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppApiBusOrderBy,
  AppApiVendorRoleMapOrderIn,
  BusSchema,
  BusStatus,
  ErrorResponse,
  HTTPValidationError,
} from '../models/index';
import {
    AppApiBusOrderByFromJSON,
    AppApiBusOrderByToJSON,
    AppApiVendorRoleMapOrderInFromJSON,
    AppApiVendorRoleMapOrderInToJSON,
    BusSchemaFromJSON,
    BusSchemaToJSON,
    BusStatusFromJSON,
    BusStatusToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CreateBusCompanyBusPostRequest {
    registrationNumber: string;
    name: string;
    capacity: number;
    manufacturedOn: Date;
    companyId: number;
    insuranceUpto?: Date | null;
    pollutionUpto?: Date | null;
    fitnessUpto?: Date | null;
    roadTaxUpto?: Date | null;
    status?: BusStatus;
}

export interface DeleteBusCompanyBusDeleteRequest {
    id: number;
}

export interface FetchBusesCompanyBusGetRequest {
    name?: string | null;
    registrationNumber?: string | null;
    id?: number | null;
    idGe?: number | null;
    idLe?: number | null;
    idList?: Array<number> | null;
    capacityGe?: number | null;
    capacityLe?: number | null;
    updatedOnGe?: Date | null;
    updatedOnLe?: Date | null;
    createdOnGe?: Date | null;
    createdOnLe?: Date | null;
    orderBy?: AppApiBusOrderBy;
    orderIn?: AppApiVendorRoleMapOrderIn;
    offset?: number;
    limit?: number;
    status?: BusStatus | null;
    manufacturedOnGe?: Date | null;
    manufacturedOnLe?: Date | null;
    insuranceUptoGe?: Date | null;
    insuranceUptoLe?: Date | null;
    pollutionUptoGe?: Date | null;
    pollutionUptoLe?: Date | null;
    fitnessUptoGe?: Date | null;
    fitnessUptoLe?: Date | null;
    roadTaxUptoGe?: Date | null;
    roadTaxUptoLe?: Date | null;
    companyId?: number | null;
}

export interface UpdateBusCompanyBusPatchRequest {
    id: number;
    name?: string | null;
    capacity?: number | null;
    manufacturedOn?: Date | null;
    insuranceUpto?: Date | null;
    pollutionUpto?: Date | null;
    fitnessUpto?: Date | null;
    roadTaxUpto?: Date | null;
    status?: BusStatus | null;
}

/**
 * 
 */
export class BusApi extends runtime.BaseAPI {

    /**
     * Creates a new bus for a specified  company.          Only executive with `create_bus` permission can create bus.          Manufactured on must be a past date.         Logs the bus account creation activity with the associated token.
     * Create Bus
     */
    async createBusCompanyBusPostRaw(requestParameters: CreateBusCompanyBusPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusSchema>> {
        if (requestParameters['registrationNumber'] == null) {
            throw new runtime.RequiredError(
                'registrationNumber',
                'Required parameter "registrationNumber" was null or undefined when calling createBusCompanyBusPost().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling createBusCompanyBusPost().'
            );
        }

        if (requestParameters['capacity'] == null) {
            throw new runtime.RequiredError(
                'capacity',
                'Required parameter "capacity" was null or undefined when calling createBusCompanyBusPost().'
            );
        }

        if (requestParameters['manufacturedOn'] == null) {
            throw new runtime.RequiredError(
                'manufacturedOn',
                'Required parameter "manufacturedOn" was null or undefined when calling createBusCompanyBusPost().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling createBusCompanyBusPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['registrationNumber'] != null) {
            formParams.append('registration_number', requestParameters['registrationNumber'] as any);
        }

        if (requestParameters['name'] != null) {
            formParams.append('name', requestParameters['name'] as any);
        }

        if (requestParameters['capacity'] != null) {
            formParams.append('capacity', requestParameters['capacity'] as any);
        }

        if (requestParameters['manufacturedOn'] != null) {
            formParams.append('manufactured_on', (requestParameters['manufacturedOn'] as any).toISOString());
        }

        if (requestParameters['insuranceUpto'] != null) {
            formParams.append('insurance_upto', (requestParameters['insuranceUpto'] as any).toISOString());
        }

        if (requestParameters['pollutionUpto'] != null) {
            formParams.append('pollution_upto', (requestParameters['pollutionUpto'] as any).toISOString());
        }

        if (requestParameters['fitnessUpto'] != null) {
            formParams.append('fitness_upto', (requestParameters['fitnessUpto'] as any).toISOString());
        }

        if (requestParameters['roadTaxUpto'] != null) {
            formParams.append('road_tax_upto', (requestParameters['roadTaxUpto'] as any).toISOString());
        }

        if (requestParameters['status'] != null) {
            formParams.append('status', requestParameters['status'] as any);
        }

        if (requestParameters['companyId'] != null) {
            formParams.append('company_id', requestParameters['companyId'] as any);
        }


        let urlPath = `/company/bus`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BusSchemaFromJSON(jsonValue));
    }

    /**
     * Creates a new bus for a specified  company.          Only executive with `create_bus` permission can create bus.          Manufactured on must be a past date.         Logs the bus account creation activity with the associated token.
     * Create Bus
     */
    async createBusCompanyBusPost(requestParameters: CreateBusCompanyBusPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusSchema> {
        const response = await this.createBusCompanyBusPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes an existing bus belonging to any company.            Only executives with `delete_bus` permission can perform this operation.         Validates the bus ID before deletion.            If the bus exists, it is permanently removed from the system.            Logs the deletion activity using the executive\'s token and request metadata.
     * Delete Bus
     */
    async deleteBusCompanyBusDeleteRaw(requestParameters: DeleteBusCompanyBusDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteBusCompanyBusDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['id'] != null) {
            formParams.append('id', requestParameters['id'] as any);
        }


        let urlPath = `/company/bus`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes an existing bus belonging to any company.            Only executives with `delete_bus` permission can perform this operation.         Validates the bus ID before deletion.            If the bus exists, it is permanently removed from the system.            Logs the deletion activity using the executive\'s token and request metadata.
     * Delete Bus
     */
    async deleteBusCompanyBusDelete(requestParameters: DeleteBusCompanyBusDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteBusCompanyBusDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Fetches a list of all buses across companies.            Supports filtering by company ID, name, registration number and metadata.        Requires a valid executive token.
     * Fetch Buses
     */
    async fetchBusesCompanyBusGetRaw(requestParameters: FetchBusesCompanyBusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BusSchema>>> {
        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['registrationNumber'] != null) {
            queryParameters['registration_number'] = requestParameters['registrationNumber'];
        }

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['idGe'] != null) {
            queryParameters['id_ge'] = requestParameters['idGe'];
        }

        if (requestParameters['idLe'] != null) {
            queryParameters['id_le'] = requestParameters['idLe'];
        }

        if (requestParameters['idList'] != null) {
            queryParameters['id_list'] = requestParameters['idList'];
        }

        if (requestParameters['capacityGe'] != null) {
            queryParameters['capacity_ge'] = requestParameters['capacityGe'];
        }

        if (requestParameters['capacityLe'] != null) {
            queryParameters['capacity_le'] = requestParameters['capacityLe'];
        }

        if (requestParameters['updatedOnGe'] != null) {
            queryParameters['updated_on_ge'] = (requestParameters['updatedOnGe'] as any).toISOString();
        }

        if (requestParameters['updatedOnLe'] != null) {
            queryParameters['updated_on_le'] = (requestParameters['updatedOnLe'] as any).toISOString();
        }

        if (requestParameters['createdOnGe'] != null) {
            queryParameters['created_on_ge'] = (requestParameters['createdOnGe'] as any).toISOString();
        }

        if (requestParameters['createdOnLe'] != null) {
            queryParameters['created_on_le'] = (requestParameters['createdOnLe'] as any).toISOString();
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['order_by'] = requestParameters['orderBy'];
        }

        if (requestParameters['orderIn'] != null) {
            queryParameters['order_in'] = requestParameters['orderIn'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['manufacturedOnGe'] != null) {
            queryParameters['manufactured_on_ge'] = (requestParameters['manufacturedOnGe'] as any).toISOString();
        }

        if (requestParameters['manufacturedOnLe'] != null) {
            queryParameters['manufactured_on_le'] = (requestParameters['manufacturedOnLe'] as any).toISOString();
        }

        if (requestParameters['insuranceUptoGe'] != null) {
            queryParameters['insurance_upto_ge'] = (requestParameters['insuranceUptoGe'] as any).toISOString();
        }

        if (requestParameters['insuranceUptoLe'] != null) {
            queryParameters['insurance_upto_le'] = (requestParameters['insuranceUptoLe'] as any).toISOString();
        }

        if (requestParameters['pollutionUptoGe'] != null) {
            queryParameters['pollution_upto_ge'] = (requestParameters['pollutionUptoGe'] as any).toISOString();
        }

        if (requestParameters['pollutionUptoLe'] != null) {
            queryParameters['pollution_upto_le'] = (requestParameters['pollutionUptoLe'] as any).toISOString();
        }

        if (requestParameters['fitnessUptoGe'] != null) {
            queryParameters['fitness_upto_ge'] = (requestParameters['fitnessUptoGe'] as any).toISOString();
        }

        if (requestParameters['fitnessUptoLe'] != null) {
            queryParameters['fitness_upto_le'] = (requestParameters['fitnessUptoLe'] as any).toISOString();
        }

        if (requestParameters['roadTaxUptoGe'] != null) {
            queryParameters['road_tax_upto_ge'] = (requestParameters['roadTaxUptoGe'] as any).toISOString();
        }

        if (requestParameters['roadTaxUptoLe'] != null) {
            queryParameters['road_tax_upto_le'] = (requestParameters['roadTaxUptoLe'] as any).toISOString();
        }

        if (requestParameters['companyId'] != null) {
            queryParameters['company_id'] = requestParameters['companyId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/company/bus`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BusSchemaFromJSON));
    }

    /**
     * Fetches a list of all buses across companies.            Supports filtering by company ID, name, registration number and metadata.        Requires a valid executive token.
     * Fetch Buses
     */
    async fetchBusesCompanyBusGet(requestParameters: FetchBusesCompanyBusGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BusSchema>> {
        const response = await this.fetchBusesCompanyBusGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates an existing bus belonging to any company.            Only executives with `update_bus` permission can perform this operation.             Supports partial updates such as modifying the bus name or capacity.             Changes are saved only if the bus data has been modified.            Manufactured on must be a past date.         Logs the bus updating activity with the associated token.
     * Update Bus
     */
    async updateBusCompanyBusPatchRaw(requestParameters: UpdateBusCompanyBusPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusSchema>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateBusCompanyBusPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['id'] != null) {
            formParams.append('id', requestParameters['id'] as any);
        }

        if (requestParameters['name'] != null) {
            formParams.append('name', requestParameters['name'] as any);
        }

        if (requestParameters['capacity'] != null) {
            formParams.append('capacity', requestParameters['capacity'] as any);
        }

        if (requestParameters['manufacturedOn'] != null) {
            formParams.append('manufactured_on', (requestParameters['manufacturedOn'] as any).toISOString());
        }

        if (requestParameters['insuranceUpto'] != null) {
            formParams.append('insurance_upto', (requestParameters['insuranceUpto'] as any).toISOString());
        }

        if (requestParameters['pollutionUpto'] != null) {
            formParams.append('pollution_upto', (requestParameters['pollutionUpto'] as any).toISOString());
        }

        if (requestParameters['fitnessUpto'] != null) {
            formParams.append('fitness_upto', (requestParameters['fitnessUpto'] as any).toISOString());
        }

        if (requestParameters['roadTaxUpto'] != null) {
            formParams.append('road_tax_upto', (requestParameters['roadTaxUpto'] as any).toISOString());
        }

        if (requestParameters['status'] != null) {
            formParams.append('status', requestParameters['status'] as any);
        }


        let urlPath = `/company/bus`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BusSchemaFromJSON(jsonValue));
    }

    /**
     * Updates an existing bus belonging to any company.            Only executives with `update_bus` permission can perform this operation.             Supports partial updates such as modifying the bus name or capacity.             Changes are saved only if the bus data has been modified.            Manufactured on must be a past date.         Logs the bus updating activity with the associated token.
     * Update Bus
     */
    async updateBusCompanyBusPatch(requestParameters: UpdateBusCompanyBusPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusSchema> {
        const response = await this.updateBusCompanyBusPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
