/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppApiBusStopOrderBy,
  AppApiVendorRoleMapOrderIn,
  BusStopSchema,
  ErrorResponse,
  HTTPValidationError,
} from '../models/index';
import {
    AppApiBusStopOrderByFromJSON,
    AppApiBusStopOrderByToJSON,
    AppApiVendorRoleMapOrderInFromJSON,
    AppApiVendorRoleMapOrderInToJSON,
    BusStopSchemaFromJSON,
    BusStopSchemaToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CreateBusStopLandmarkBusStopPostRequest {
    name: string;
    landmarkId: number;
    location: string;
}

export interface DeleteBusStopLandmarkBusStopDeleteRequest {
    id: number;
}

export interface FetchBusStopLandmarkBusStopGetRequest {
    name?: string | null;
    location?: string | null;
    id?: number | null;
    idGe?: number | null;
    idLe?: number | null;
    idList?: Array<number> | null;
    landmarkId?: number | null;
    landmarkIdList?: Array<number> | null;
    updatedOnGe?: Date | null;
    updatedOnLe?: Date | null;
    createdOnGe?: Date | null;
    createdOnLe?: Date | null;
    orderBy?: AppApiBusStopOrderBy;
    orderIn?: AppApiVendorRoleMapOrderIn;
    offset?: number;
    limit?: number;
}

export interface UpdateBusStopLandmarkBusStopPatchRequest {
    id: number;
    name?: string | null;
    location?: string | null;
}

/**
 * 
 */
export class BusStopApi extends runtime.BaseAPI {

    /**
     * Create a new bus stop within a landmark boundary.       Validates location SRID and ensures the bus stop is geographically inside the target landmark.       Requires `create_landmark` or `update_landmark` permission.
     * Create Bus Stop
     */
    async createBusStopLandmarkBusStopPostRaw(requestParameters: CreateBusStopLandmarkBusStopPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusStopSchema>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling createBusStopLandmarkBusStopPost().'
            );
        }

        if (requestParameters['landmarkId'] == null) {
            throw new runtime.RequiredError(
                'landmarkId',
                'Required parameter "landmarkId" was null or undefined when calling createBusStopLandmarkBusStopPost().'
            );
        }

        if (requestParameters['location'] == null) {
            throw new runtime.RequiredError(
                'location',
                'Required parameter "location" was null or undefined when calling createBusStopLandmarkBusStopPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['name'] != null) {
            formParams.append('name', requestParameters['name'] as any);
        }

        if (requestParameters['landmarkId'] != null) {
            formParams.append('landmark_id', requestParameters['landmarkId'] as any);
        }

        if (requestParameters['location'] != null) {
            formParams.append('location', requestParameters['location'] as any);
        }


        let urlPath = `/landmark/bus_stop`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BusStopSchemaFromJSON(jsonValue));
    }

    /**
     * Create a new bus stop within a landmark boundary.       Validates location SRID and ensures the bus stop is geographically inside the target landmark.       Requires `create_landmark` or `update_landmark` permission.
     * Create Bus Stop
     */
    async createBusStopLandmarkBusStopPost(requestParameters: CreateBusStopLandmarkBusStopPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusStopSchema> {
        const response = await this.createBusStopLandmarkBusStopPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a bus stop by ID.       Requires `create_landmark` or `update_landmark` permission.       Removes the record if it exists and logs the deletion event.
     * Delete Bus Stop
     */
    async deleteBusStopLandmarkBusStopDeleteRaw(requestParameters: DeleteBusStopLandmarkBusStopDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteBusStopLandmarkBusStopDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['id'] != null) {
            formParams.append('id', requestParameters['id'] as any);
        }


        let urlPath = `/landmark/bus_stop`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a bus stop by ID.       Requires `create_landmark` or `update_landmark` permission.       Removes the record if it exists and logs the deletion event.
     * Delete Bus Stop
     */
    async deleteBusStopLandmarkBusStopDelete(requestParameters: DeleteBusStopLandmarkBusStopDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteBusStopLandmarkBusStopDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieve bus stops based on flexible query filters.       Supports pagination and distance-based sorting when location is provided.       Requires a valid executive token.
     * Fetch Bus Stop
     */
    async fetchBusStopLandmarkBusStopGetRaw(requestParameters: FetchBusStopLandmarkBusStopGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BusStopSchema>>> {
        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['location'] != null) {
            queryParameters['location'] = requestParameters['location'];
        }

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['idGe'] != null) {
            queryParameters['id_ge'] = requestParameters['idGe'];
        }

        if (requestParameters['idLe'] != null) {
            queryParameters['id_le'] = requestParameters['idLe'];
        }

        if (requestParameters['idList'] != null) {
            queryParameters['id_list'] = requestParameters['idList'];
        }

        if (requestParameters['landmarkId'] != null) {
            queryParameters['landmark_id'] = requestParameters['landmarkId'];
        }

        if (requestParameters['landmarkIdList'] != null) {
            queryParameters['landmark_id_list'] = requestParameters['landmarkIdList'];
        }

        if (requestParameters['updatedOnGe'] != null) {
            queryParameters['updated_on_ge'] = (requestParameters['updatedOnGe'] as any).toISOString();
        }

        if (requestParameters['updatedOnLe'] != null) {
            queryParameters['updated_on_le'] = (requestParameters['updatedOnLe'] as any).toISOString();
        }

        if (requestParameters['createdOnGe'] != null) {
            queryParameters['created_on_ge'] = (requestParameters['createdOnGe'] as any).toISOString();
        }

        if (requestParameters['createdOnLe'] != null) {
            queryParameters['created_on_le'] = (requestParameters['createdOnLe'] as any).toISOString();
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['order_by'] = requestParameters['orderBy'];
        }

        if (requestParameters['orderIn'] != null) {
            queryParameters['order_in'] = requestParameters['orderIn'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/landmark/bus_stop`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BusStopSchemaFromJSON));
    }

    /**
     * Retrieve bus stops based on flexible query filters.       Supports pagination and distance-based sorting when location is provided.       Requires a valid executive token.
     * Fetch Bus Stop
     */
    async fetchBusStopLandmarkBusStopGet(requestParameters: FetchBusStopLandmarkBusStopGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BusStopSchema>> {
        const response = await this.fetchBusStopLandmarkBusStopGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an existing bus stop\'s name and/or location.       If location is updated, it is validated against the landmark\'s boundary.       Requires `create_landmark` or `update_landmark` permission.
     * Update Bus Stop
     */
    async updateBusStopLandmarkBusStopPatchRaw(requestParameters: UpdateBusStopLandmarkBusStopPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusStopSchema>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateBusStopLandmarkBusStopPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['id'] != null) {
            formParams.append('id', requestParameters['id'] as any);
        }

        if (requestParameters['name'] != null) {
            formParams.append('name', requestParameters['name'] as any);
        }

        if (requestParameters['location'] != null) {
            formParams.append('location', requestParameters['location'] as any);
        }


        let urlPath = `/landmark/bus_stop`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BusStopSchemaFromJSON(jsonValue));
    }

    /**
     * Update an existing bus stop\'s name and/or location.       If location is updated, it is validated against the landmark\'s boundary.       Requires `create_landmark` or `update_landmark` permission.
     * Update Bus Stop
     */
    async updateBusStopLandmarkBusStopPatch(requestParameters: UpdateBusStopLandmarkBusStopPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusStopSchema> {
        const response = await this.updateBusStopLandmarkBusStopPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
