/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppApiCompanyOrderBy,
  AppApiVendorRoleMapOrderIn,
  CompanySchema,
  CompanyStatus,
  CompanyType,
  ErrorResponse,
  HTTPValidationError,
} from '../models/index';
import {
    AppApiCompanyOrderByFromJSON,
    AppApiCompanyOrderByToJSON,
    AppApiVendorRoleMapOrderInFromJSON,
    AppApiVendorRoleMapOrderInToJSON,
    CompanySchemaFromJSON,
    CompanySchemaToJSON,
    CompanyStatusFromJSON,
    CompanyStatusToJSON,
    CompanyTypeFromJSON,
    CompanyTypeToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CreateCompanyCompanyPostRequest {
    name: string;
    address: string;
    contactPerson: string;
    phoneNumber: string;
    emailId: string;
    location: string;
    status?: CompanyStatus;
    type?: CompanyType;
}

export interface DeleteCompanyCompanyDeleteRequest {
    id: number;
}

export interface FetchCompanyCompanyGetRequest {
    id?: number | null;
    name?: string | null;
    type?: CompanyType | null;
    location?: string | null;
    idGe?: number | null;
    idLe?: number | null;
    idList?: Array<number> | null;
    updatedOnGe?: Date | null;
    updatedOnLe?: Date | null;
    createdOnGe?: Date | null;
    createdOnLe?: Date | null;
    orderBy?: AppApiCompanyOrderBy;
    orderIn?: AppApiVendorRoleMapOrderIn;
    offset?: number;
    limit?: number;
    status?: CompanyStatus | null;
    address?: string | null;
    contactPerson?: string | null;
    phoneNumber?: string | null;
    emailId?: string | null;
}

export interface UpdateCompanyCompanyPatchRequest {
    id: number;
    address?: string | null;
    contactPerson?: string | null;
    phoneNumber?: string | null;
    emailId?: string | null;
    location?: string | null;
    name?: string | null;
    status?: CompanyStatus | null;
    type?: CompanyType | null;
}

/**
 * 
 */
export class CompanyApi extends runtime.BaseAPI {

    /**
     * Create a new company.       Requires executive permissions with `create_company` role.       A wallet is automatically created with the company name when a company is created.              Validates location format and ensures all required fields are provided.
     * Create Company
     */
    async createCompanyCompanyPostRaw(requestParameters: CreateCompanyCompanyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CompanySchema>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling createCompanyCompanyPost().'
            );
        }

        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling createCompanyCompanyPost().'
            );
        }

        if (requestParameters['contactPerson'] == null) {
            throw new runtime.RequiredError(
                'contactPerson',
                'Required parameter "contactPerson" was null or undefined when calling createCompanyCompanyPost().'
            );
        }

        if (requestParameters['phoneNumber'] == null) {
            throw new runtime.RequiredError(
                'phoneNumber',
                'Required parameter "phoneNumber" was null or undefined when calling createCompanyCompanyPost().'
            );
        }

        if (requestParameters['emailId'] == null) {
            throw new runtime.RequiredError(
                'emailId',
                'Required parameter "emailId" was null or undefined when calling createCompanyCompanyPost().'
            );
        }

        if (requestParameters['location'] == null) {
            throw new runtime.RequiredError(
                'location',
                'Required parameter "location" was null or undefined when calling createCompanyCompanyPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['name'] != null) {
            formParams.append('name', requestParameters['name'] as any);
        }

        if (requestParameters['status'] != null) {
            formParams.append('status', requestParameters['status'] as any);
        }

        if (requestParameters['type'] != null) {
            formParams.append('type', requestParameters['type'] as any);
        }

        if (requestParameters['address'] != null) {
            formParams.append('address', requestParameters['address'] as any);
        }

        if (requestParameters['contactPerson'] != null) {
            formParams.append('contact_person', requestParameters['contactPerson'] as any);
        }

        if (requestParameters['phoneNumber'] != null) {
            formParams.append('phone_number', requestParameters['phoneNumber'] as any);
        }

        if (requestParameters['emailId'] != null) {
            formParams.append('email_id', requestParameters['emailId'] as any);
        }

        if (requestParameters['location'] != null) {
            formParams.append('location', requestParameters['location'] as any);
        }


        let urlPath = `/company`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CompanySchemaFromJSON(jsonValue));
    }

    /**
     * Create a new company.       Requires executive permissions with `create_company` role.       A wallet is automatically created with the company name when a company is created.              Validates location format and ensures all required fields are provided.
     * Create Company
     */
    async createCompanyCompanyPost(requestParameters: CreateCompanyCompanyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CompanySchema> {
        const response = await this.createCompanyCompanyPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an existing company by ID.       Requires executive permissions with `delete_company` role.       Deletes the company and logs the deletion event.
     * Delete Company
     */
    async deleteCompanyCompanyDeleteRaw(requestParameters: DeleteCompanyCompanyDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteCompanyCompanyDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['id'] != null) {
            formParams.append('id', requestParameters['id'] as any);
        }


        let urlPath = `/company`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an existing company by ID.       Requires executive permissions with `delete_company` role.       Deletes the company and logs the deletion event.
     * Delete Company
     */
    async deleteCompanyCompanyDelete(requestParameters: DeleteCompanyCompanyDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteCompanyCompanyDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Fetch a list of companies with optional filters like ID, name, type, location, etc.       Supports sorting and pagination.       Requires a valid executive token.
     * Fetch Company
     */
    async fetchCompanyCompanyGetRaw(requestParameters: FetchCompanyCompanyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CompanySchema>>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['location'] != null) {
            queryParameters['location'] = requestParameters['location'];
        }

        if (requestParameters['idGe'] != null) {
            queryParameters['id_ge'] = requestParameters['idGe'];
        }

        if (requestParameters['idLe'] != null) {
            queryParameters['id_le'] = requestParameters['idLe'];
        }

        if (requestParameters['idList'] != null) {
            queryParameters['id_list'] = requestParameters['idList'];
        }

        if (requestParameters['updatedOnGe'] != null) {
            queryParameters['updated_on_ge'] = (requestParameters['updatedOnGe'] as any).toISOString();
        }

        if (requestParameters['updatedOnLe'] != null) {
            queryParameters['updated_on_le'] = (requestParameters['updatedOnLe'] as any).toISOString();
        }

        if (requestParameters['createdOnGe'] != null) {
            queryParameters['created_on_ge'] = (requestParameters['createdOnGe'] as any).toISOString();
        }

        if (requestParameters['createdOnLe'] != null) {
            queryParameters['created_on_le'] = (requestParameters['createdOnLe'] as any).toISOString();
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['order_by'] = requestParameters['orderBy'];
        }

        if (requestParameters['orderIn'] != null) {
            queryParameters['order_in'] = requestParameters['orderIn'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        if (requestParameters['contactPerson'] != null) {
            queryParameters['contact_person'] = requestParameters['contactPerson'];
        }

        if (requestParameters['phoneNumber'] != null) {
            queryParameters['phone_number'] = requestParameters['phoneNumber'];
        }

        if (requestParameters['emailId'] != null) {
            queryParameters['email_id'] = requestParameters['emailId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/company`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CompanySchemaFromJSON));
    }

    /**
     * Fetch a list of companies with optional filters like ID, name, type, location, etc.       Supports sorting and pagination.       Requires a valid executive token.
     * Fetch Company
     */
    async fetchCompanyCompanyGet(requestParameters: FetchCompanyCompanyGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CompanySchema>> {
        const response = await this.fetchCompanyCompanyGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an existing company record.       Requires executive permissions with `update_company` role.             Updates only the provided fields and validates the location if present.          Allowed status transitions:         UNDER_VERIFICATION → VERIFIED         UNDER_VERIFICATION → SUSPENDED         VERIFIED ↔ SUSPENDED
     * Update Company
     */
    async updateCompanyCompanyPatchRaw(requestParameters: UpdateCompanyCompanyPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CompanySchema>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateCompanyCompanyPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['id'] != null) {
            formParams.append('id', requestParameters['id'] as any);
        }

        if (requestParameters['address'] != null) {
            formParams.append('address', requestParameters['address'] as any);
        }

        if (requestParameters['contactPerson'] != null) {
            formParams.append('contact_person', requestParameters['contactPerson'] as any);
        }

        if (requestParameters['phoneNumber'] != null) {
            formParams.append('phone_number', requestParameters['phoneNumber'] as any);
        }

        if (requestParameters['emailId'] != null) {
            formParams.append('email_id', requestParameters['emailId'] as any);
        }

        if (requestParameters['location'] != null) {
            formParams.append('location', requestParameters['location'] as any);
        }

        if (requestParameters['name'] != null) {
            formParams.append('name', requestParameters['name'] as any);
        }

        if (requestParameters['status'] != null) {
            formParams.append('status', requestParameters['status'] as any);
        }

        if (requestParameters['type'] != null) {
            formParams.append('type', requestParameters['type'] as any);
        }


        let urlPath = `/company`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CompanySchemaFromJSON(jsonValue));
    }

    /**
     * Update an existing company record.       Requires executive permissions with `update_company` role.             Updates only the provided fields and validates the location if present.          Allowed status transitions:         UNDER_VERIFICATION → VERIFIED         UNDER_VERIFICATION → SUSPENDED         VERIFIED ↔ SUSPENDED
     * Update Company
     */
    async updateCompanyCompanyPatch(requestParameters: UpdateCompanyCompanyPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CompanySchema> {
        const response = await this.updateCompanyCompanyPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
