/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppApiFareOrderBy,
  AppApiVendorRoleMapOrderIn,
  BodyCreateFareCompanyFarePost,
  BodyUpdateFareCompanyFarePatch,
  ErrorResponse,
  FareSchema,
  FareScope,
  HTTPValidationError,
} from '../models/index';
import {
    AppApiFareOrderByFromJSON,
    AppApiFareOrderByToJSON,
    AppApiVendorRoleMapOrderInFromJSON,
    AppApiVendorRoleMapOrderInToJSON,
    BodyCreateFareCompanyFarePostFromJSON,
    BodyCreateFareCompanyFarePostToJSON,
    BodyUpdateFareCompanyFarePatchFromJSON,
    BodyUpdateFareCompanyFarePatchToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    FareSchemaFromJSON,
    FareSchemaToJSON,
    FareScopeFromJSON,
    FareScopeToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CreateFareCompanyFarePostRequest {
    bodyCreateFareCompanyFarePost: BodyCreateFareCompanyFarePost;
}

export interface DeleteFareCompanyFareDeleteRequest {
    body: number;
}

export interface FetchFareCompanyFareGetRequest {
    name?: string | null;
    scope?: FareScope | null;
    id?: number | null;
    idGe?: number | null;
    idLe?: number | null;
    idList?: Array<number> | null;
    version?: number | null;
    versionGe?: number | null;
    versionLe?: number | null;
    updatedOnGe?: Date | null;
    updatedOnLe?: Date | null;
    createdOnGe?: Date | null;
    createdOnLe?: Date | null;
    orderBy?: AppApiFareOrderBy;
    orderIn?: AppApiVendorRoleMapOrderIn;
    offset?: number;
    limit?: number;
    companyId?: number | null;
}

export interface UpdateFareCompanyFarePatchRequest {
    bodyUpdateFareCompanyFarePatch: BodyUpdateFareCompanyFarePatch;
}

/**
 * 
 */
export class FareApi extends runtime.BaseAPI {

    /**
     * Create a new fare in global scope or in local  scope for a specified company.                Requires executive role with `create_fare` permission.         If the fare is in Local scope, it must be associated with the company.     If the fare is in Global scope, company_id must be None.        The DF function and DF attributes are always tightly coupled together.           The DF function is validated against the attributes.         The name of the JS function must be `getFare` and this function will accept exactly three arguments which are ticket_type, distance and extra.       The getFare function must return -1 if there is some logical or runtime error occurred during the function call.        The max size of fare function is 10 MB.      The fare function should not take more than 1 seconds to execute.        Preferable dynamic fare version is 1.            Preferable distance unit is meter and currency is INR.        Log the fare creation activity with the associated token.
     * Create Fare
     */
    async createFareCompanyFarePostRaw(requestParameters: CreateFareCompanyFarePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FareSchema>> {
        if (requestParameters['bodyCreateFareCompanyFarePost'] == null) {
            throw new runtime.RequiredError(
                'bodyCreateFareCompanyFarePost',
                'Required parameter "bodyCreateFareCompanyFarePost" was null or undefined when calling createFareCompanyFarePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/company/fare`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BodyCreateFareCompanyFarePostToJSON(requestParameters['bodyCreateFareCompanyFarePost']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FareSchemaFromJSON(jsonValue));
    }

    /**
     * Create a new fare in global scope or in local  scope for a specified company.                Requires executive role with `create_fare` permission.         If the fare is in Local scope, it must be associated with the company.     If the fare is in Global scope, company_id must be None.        The DF function and DF attributes are always tightly coupled together.           The DF function is validated against the attributes.         The name of the JS function must be `getFare` and this function will accept exactly three arguments which are ticket_type, distance and extra.       The getFare function must return -1 if there is some logical or runtime error occurred during the function call.        The max size of fare function is 10 MB.      The fare function should not take more than 1 seconds to execute.        Preferable dynamic fare version is 1.            Preferable distance unit is meter and currency is INR.        Log the fare creation activity with the associated token.
     * Create Fare
     */
    async createFareCompanyFarePost(requestParameters: CreateFareCompanyFarePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FareSchema> {
        const response = await this.createFareCompanyFarePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes an existing fare.            Only executives with `delete_fare` permission can perform this operation.         Validates the fare ID before deletion.            If the fare exists, it is permanently removed from the system.            Logs the deletion activity using the executive\'s token and request metadata.
     * Delete Fare
     */
    async deleteFareCompanyFareDeleteRaw(requestParameters: DeleteFareCompanyFareDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling deleteFareCompanyFareDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/company/fare`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes an existing fare.            Only executives with `delete_fare` permission can perform this operation.         Validates the fare ID before deletion.            If the fare exists, it is permanently removed from the system.            Logs the deletion activity using the executive\'s token and request metadata.
     * Delete Fare
     */
    async deleteFareCompanyFareDelete(requestParameters: DeleteFareCompanyFareDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteFareCompanyFareDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Fetches a list of all fares across Global and Local scope.            Supports filtering by company ID, name, scope and metadata.       Supports filtering, sorting, and pagination.          Requires a valid executive token.
     * Fetch Fare
     */
    async fetchFareCompanyFareGetRaw(requestParameters: FetchFareCompanyFareGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FareSchema>>> {
        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['scope'] != null) {
            queryParameters['scope'] = requestParameters['scope'];
        }

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['idGe'] != null) {
            queryParameters['id_ge'] = requestParameters['idGe'];
        }

        if (requestParameters['idLe'] != null) {
            queryParameters['id_le'] = requestParameters['idLe'];
        }

        if (requestParameters['idList'] != null) {
            queryParameters['id_list'] = requestParameters['idList'];
        }

        if (requestParameters['version'] != null) {
            queryParameters['version'] = requestParameters['version'];
        }

        if (requestParameters['versionGe'] != null) {
            queryParameters['version_ge'] = requestParameters['versionGe'];
        }

        if (requestParameters['versionLe'] != null) {
            queryParameters['version_le'] = requestParameters['versionLe'];
        }

        if (requestParameters['updatedOnGe'] != null) {
            queryParameters['updated_on_ge'] = (requestParameters['updatedOnGe'] as any).toISOString();
        }

        if (requestParameters['updatedOnLe'] != null) {
            queryParameters['updated_on_le'] = (requestParameters['updatedOnLe'] as any).toISOString();
        }

        if (requestParameters['createdOnGe'] != null) {
            queryParameters['created_on_ge'] = (requestParameters['createdOnGe'] as any).toISOString();
        }

        if (requestParameters['createdOnLe'] != null) {
            queryParameters['created_on_le'] = (requestParameters['createdOnLe'] as any).toISOString();
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['order_by'] = requestParameters['orderBy'];
        }

        if (requestParameters['orderIn'] != null) {
            queryParameters['order_in'] = requestParameters['orderIn'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['companyId'] != null) {
            queryParameters['company_id'] = requestParameters['companyId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/company/fare`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FareSchemaFromJSON));
    }

    /**
     * Fetches a list of all fares across Global and Local scope.            Supports filtering by company ID, name, scope and metadata.       Supports filtering, sorting, and pagination.          Requires a valid executive token.
     * Fetch Fare
     */
    async fetchFareCompanyFareGet(requestParameters: FetchFareCompanyFareGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FareSchema>> {
        const response = await this.fetchFareCompanyFareGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates an existing fare belonging to any company.            Only executives with `update_fare` permission can perform this operation.             Supports partial updates such as modifying the fare name or function.          The DF function and DF attributes are always tightly coupled together.           The DF function is validated against the attributes.         The name of the JS function must be `getFare` and this function will accept exactly three arguments which are ticket_type, distance and extra.       The getFare function must return -1 if there is some logical or runtime error occurred during the function call.           Changes are saved only if the fare data has been modified.         The max size of fare function is 10 MB.      The fare function should not take more than 1 seconds to execute.        The version is automatically incremented, when the fare is modified.         Preferable dynamic fare version is 1.            Preferable distance unit is meter and currency is INR.       Logs the fare updating activity with the associated token.
     * Update Fare
     */
    async updateFareCompanyFarePatchRaw(requestParameters: UpdateFareCompanyFarePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FareSchema>> {
        if (requestParameters['bodyUpdateFareCompanyFarePatch'] == null) {
            throw new runtime.RequiredError(
                'bodyUpdateFareCompanyFarePatch',
                'Required parameter "bodyUpdateFareCompanyFarePatch" was null or undefined when calling updateFareCompanyFarePatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/company/fare`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: BodyUpdateFareCompanyFarePatchToJSON(requestParameters['bodyUpdateFareCompanyFarePatch']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FareSchemaFromJSON(jsonValue));
    }

    /**
     * Updates an existing fare belonging to any company.            Only executives with `update_fare` permission can perform this operation.             Supports partial updates such as modifying the fare name or function.          The DF function and DF attributes are always tightly coupled together.           The DF function is validated against the attributes.         The name of the JS function must be `getFare` and this function will accept exactly three arguments which are ticket_type, distance and extra.       The getFare function must return -1 if there is some logical or runtime error occurred during the function call.           Changes are saved only if the fare data has been modified.         The max size of fare function is 10 MB.      The fare function should not take more than 1 seconds to execute.        The version is automatically incremented, when the fare is modified.         Preferable dynamic fare version is 1.            Preferable distance unit is meter and currency is INR.       Logs the fare updating activity with the associated token.
     * Update Fare
     */
    async updateFareCompanyFarePatch(requestParameters: UpdateFareCompanyFarePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FareSchema> {
        const response = await this.updateFareCompanyFarePatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
