/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppApiLandmarkOrderBy,
  AppApiVendorRoleMapOrderIn,
  ErrorResponse,
  HTTPValidationError,
  LandmarkSchema,
  LandmarkType,
} from '../models/index';
import {
    AppApiLandmarkOrderByFromJSON,
    AppApiLandmarkOrderByToJSON,
    AppApiVendorRoleMapOrderInFromJSON,
    AppApiVendorRoleMapOrderInToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    LandmarkSchemaFromJSON,
    LandmarkSchemaToJSON,
    LandmarkTypeFromJSON,
    LandmarkTypeToJSON,
} from '../models/index';

export interface CreateLandmarkLandmarkPostRequest {
    name: string;
    boundary: string;
    type?: LandmarkType;
}

export interface DeleteLandmarkLandmarkDeleteRequest {
    id: number;
}

export interface FetchLandmarkLandmarkGetRequest {
    name?: string | null;
    location?: string | null;
    id?: number | null;
    idGe?: number | null;
    idLe?: number | null;
    idList?: Array<number> | null;
    type?: LandmarkType | null;
    typeList?: Array<LandmarkType> | null;
    updatedOnGe?: Date | null;
    updatedOnLe?: Date | null;
    createdOnGe?: Date | null;
    createdOnLe?: Date | null;
    orderBy?: AppApiLandmarkOrderBy;
    orderIn?: AppApiVendorRoleMapOrderIn;
    offset?: number;
    limit?: number;
}

export interface UpdateLandmarkLandmarkPatchRequest {
    id: number | null;
    name?: string | null;
    boundary?: string | null;
    type?: LandmarkType | null;
}

/**
 * 
 */
export class LandmarkApi extends runtime.BaseAPI {

    /**
     * Create a new landmark by specifying its name, type, and spatial boundary.       The boundary must be a valid AABB polygon in SRID 4326 (WGS84), and its area must be within an acceptable range.       Only executives with `create_landmark` permission can perform this operation.
     * Create Landmark
     */
    async createLandmarkLandmarkPostRaw(requestParameters: CreateLandmarkLandmarkPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LandmarkSchema>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling createLandmarkLandmarkPost().'
            );
        }

        if (requestParameters['boundary'] == null) {
            throw new runtime.RequiredError(
                'boundary',
                'Required parameter "boundary" was null or undefined when calling createLandmarkLandmarkPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['name'] != null) {
            formParams.append('name', requestParameters['name'] as any);
        }

        if (requestParameters['boundary'] != null) {
            formParams.append('boundary', requestParameters['boundary'] as any);
        }

        if (requestParameters['type'] != null) {
            formParams.append('type', requestParameters['type'] as any);
        }


        let urlPath = `/landmark`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LandmarkSchemaFromJSON(jsonValue));
    }

    /**
     * Create a new landmark by specifying its name, type, and spatial boundary.       The boundary must be a valid AABB polygon in SRID 4326 (WGS84), and its area must be within an acceptable range.       Only executives with `create_landmark` permission can perform this operation.
     * Create Landmark
     */
    async createLandmarkLandmarkPost(requestParameters: CreateLandmarkLandmarkPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LandmarkSchema> {
        const response = await this.createLandmarkLandmarkPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an existing landmark by ID.       Only executives with `delete_landmark` permission can perform this action.       If the landmark exists, it will be permanently removed.
     * Delete Landmark
     */
    async deleteLandmarkLandmarkDeleteRaw(requestParameters: DeleteLandmarkLandmarkDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteLandmarkLandmarkDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['id'] != null) {
            formParams.append('id', requestParameters['id'] as any);
        }


        let urlPath = `/landmark`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an existing landmark by ID.       Only executives with `delete_landmark` permission can perform this action.       If the landmark exists, it will be permanently removed.
     * Delete Landmark
     */
    async deleteLandmarkLandmarkDelete(requestParameters: DeleteLandmarkLandmarkDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteLandmarkLandmarkDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieve a list of landmarks with advanced filtering, sorting, and pagination.       Supports spatial queries using a reference location in SRID 4326, and ordering by proximity or metadata fields.       Only accessible to authenticated executives.
     * Fetch Landmark
     */
    async fetchLandmarkLandmarkGetRaw(requestParameters: FetchLandmarkLandmarkGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<LandmarkSchema>>> {
        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['location'] != null) {
            queryParameters['location'] = requestParameters['location'];
        }

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['idGe'] != null) {
            queryParameters['id_ge'] = requestParameters['idGe'];
        }

        if (requestParameters['idLe'] != null) {
            queryParameters['id_le'] = requestParameters['idLe'];
        }

        if (requestParameters['idList'] != null) {
            queryParameters['id_list'] = requestParameters['idList'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['typeList'] != null) {
            queryParameters['type_list'] = requestParameters['typeList'];
        }

        if (requestParameters['updatedOnGe'] != null) {
            queryParameters['updated_on_ge'] = (requestParameters['updatedOnGe'] as any).toISOString();
        }

        if (requestParameters['updatedOnLe'] != null) {
            queryParameters['updated_on_le'] = (requestParameters['updatedOnLe'] as any).toISOString();
        }

        if (requestParameters['createdOnGe'] != null) {
            queryParameters['created_on_ge'] = (requestParameters['createdOnGe'] as any).toISOString();
        }

        if (requestParameters['createdOnLe'] != null) {
            queryParameters['created_on_le'] = (requestParameters['createdOnLe'] as any).toISOString();
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['order_by'] = requestParameters['orderBy'];
        }

        if (requestParameters['orderIn'] != null) {
            queryParameters['order_in'] = requestParameters['orderIn'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/landmark`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LandmarkSchemaFromJSON));
    }

    /**
     * Retrieve a list of landmarks with advanced filtering, sorting, and pagination.       Supports spatial queries using a reference location in SRID 4326, and ordering by proximity or metadata fields.       Only accessible to authenticated executives.
     * Fetch Landmark
     */
    async fetchLandmarkLandmarkGet(requestParameters: FetchLandmarkLandmarkGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<LandmarkSchema>> {
        const response = await this.fetchLandmarkLandmarkGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update the details of an existing landmark including name, type, or boundary.       If the boundary is changed, all associated bus stops must remain within the new boundary.       Only executives with `update_landmark` permission can perform this operation.
     * Update Landmark
     */
    async updateLandmarkLandmarkPatchRaw(requestParameters: UpdateLandmarkLandmarkPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LandmarkSchema>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateLandmarkLandmarkPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['id'] != null) {
            formParams.append('id', requestParameters['id'] as any);
        }

        if (requestParameters['name'] != null) {
            formParams.append('name', requestParameters['name'] as any);
        }

        if (requestParameters['boundary'] != null) {
            formParams.append('boundary', requestParameters['boundary'] as any);
        }

        if (requestParameters['type'] != null) {
            formParams.append('type', requestParameters['type'] as any);
        }


        let urlPath = `/landmark`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LandmarkSchemaFromJSON(jsonValue));
    }

    /**
     * Update the details of an existing landmark including name, type, or boundary.       If the boundary is changed, all associated bus stops must remain within the new boundary.       Only executives with `update_landmark` permission can perform this operation.
     * Update Landmark
     */
    async updateLandmarkLandmarkPatch(requestParameters: UpdateLandmarkLandmarkPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LandmarkSchema> {
        const response = await this.updateLandmarkLandmarkPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
