/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppApiLandmarkInRouteOrderBy,
  AppApiVendorRoleMapOrderIn,
  ErrorResponse,
  HTTPValidationError,
  LandmarkInRouteSchema,
} from '../models/index';
import {
    AppApiLandmarkInRouteOrderByFromJSON,
    AppApiLandmarkInRouteOrderByToJSON,
    AppApiVendorRoleMapOrderInFromJSON,
    AppApiVendorRoleMapOrderInToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    LandmarkInRouteSchemaFromJSON,
    LandmarkInRouteSchemaToJSON,
} from '../models/index';

export interface CreateLandmarkInRouteCompanyRouteLandmarkPostRequest {
    routeId: number;
    landmarkId: number;
    distanceFromStart: number;
    arrivalDelta: number;
    departureDelta: number;
}

export interface DeleteLandmarkInRouteCompanyRouteLandmarkDeleteRequest {
    id: number;
}

export interface FetchLandmarksInRouteCompanyRouteLandmarkGetRequest {
    routeId?: number | null;
    landmarkId?: number | null;
    landmarkIdList?: Array<number> | null;
    id?: number | null;
    idGe?: number | null;
    idLe?: number | null;
    idList?: Array<number> | null;
    distanceFromStartGe?: number | null;
    distanceFromStartLe?: number | null;
    arrivalDeltaGe?: number | null;
    arrivalDeltaLe?: number | null;
    departureDeltaGe?: number | null;
    departureDeltaLe?: number | null;
    updatedOnGe?: Date | null;
    updatedOnLe?: Date | null;
    createdOnGe?: Date | null;
    createdOnLe?: Date | null;
    orderBy?: AppApiLandmarkInRouteOrderBy;
    orderIn?: AppApiVendorRoleMapOrderIn;
    offset?: number;
    limit?: number;
    companyId?: number | null;
}

export interface UpdateLandmarkInRouteCompanyRouteLandmarkPatchRequest {
    id: number;
    distanceFromStart?: number | null;
    arrivalDelta?: number | null;
    departureDelta?: number | null;
}

/**
 * 
 */
export class LandmarkInRouteApi extends runtime.BaseAPI {

    /**
     * Create a new landmark assignment within a route for a company.       Requires `create_route` or `update_route` permission.       Validates route and landmark existence before creation.             When creating a new landmark in a route, the route will be validated and status of the route will be updated.       Validates departure_delta is greater than arrival_delta.
     * Create Landmark In Route
     */
    async createLandmarkInRouteCompanyRouteLandmarkPostRaw(requestParameters: CreateLandmarkInRouteCompanyRouteLandmarkPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LandmarkInRouteSchema>> {
        if (requestParameters['routeId'] == null) {
            throw new runtime.RequiredError(
                'routeId',
                'Required parameter "routeId" was null or undefined when calling createLandmarkInRouteCompanyRouteLandmarkPost().'
            );
        }

        if (requestParameters['landmarkId'] == null) {
            throw new runtime.RequiredError(
                'landmarkId',
                'Required parameter "landmarkId" was null or undefined when calling createLandmarkInRouteCompanyRouteLandmarkPost().'
            );
        }

        if (requestParameters['distanceFromStart'] == null) {
            throw new runtime.RequiredError(
                'distanceFromStart',
                'Required parameter "distanceFromStart" was null or undefined when calling createLandmarkInRouteCompanyRouteLandmarkPost().'
            );
        }

        if (requestParameters['arrivalDelta'] == null) {
            throw new runtime.RequiredError(
                'arrivalDelta',
                'Required parameter "arrivalDelta" was null or undefined when calling createLandmarkInRouteCompanyRouteLandmarkPost().'
            );
        }

        if (requestParameters['departureDelta'] == null) {
            throw new runtime.RequiredError(
                'departureDelta',
                'Required parameter "departureDelta" was null or undefined when calling createLandmarkInRouteCompanyRouteLandmarkPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['routeId'] != null) {
            formParams.append('route_id', requestParameters['routeId'] as any);
        }

        if (requestParameters['landmarkId'] != null) {
            formParams.append('landmark_id', requestParameters['landmarkId'] as any);
        }

        if (requestParameters['distanceFromStart'] != null) {
            formParams.append('distance_from_start', requestParameters['distanceFromStart'] as any);
        }

        if (requestParameters['arrivalDelta'] != null) {
            formParams.append('arrival_delta', requestParameters['arrivalDelta'] as any);
        }

        if (requestParameters['departureDelta'] != null) {
            formParams.append('departure_delta', requestParameters['departureDelta'] as any);
        }


        let urlPath = `/company/route/landmark`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LandmarkInRouteSchemaFromJSON(jsonValue));
    }

    /**
     * Create a new landmark assignment within a route for a company.       Requires `create_route` or `update_route` permission.       Validates route and landmark existence before creation.             When creating a new landmark in a route, the route will be validated and status of the route will be updated.       Validates departure_delta is greater than arrival_delta.
     * Create Landmark In Route
     */
    async createLandmarkInRouteCompanyRouteLandmarkPost(requestParameters: CreateLandmarkInRouteCompanyRouteLandmarkPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LandmarkInRouteSchema> {
        const response = await this.createLandmarkInRouteCompanyRouteLandmarkPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a specific landmark assigned to a route by ID.       Requires `create_route` or `update_route` permission.       When deleting a landmark in a route, the route will be validated and status of the route will be updated.      Deletes the record if it exists.
     * Delete Landmark In Route
     */
    async deleteLandmarkInRouteCompanyRouteLandmarkDeleteRaw(requestParameters: DeleteLandmarkInRouteCompanyRouteLandmarkDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteLandmarkInRouteCompanyRouteLandmarkDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['id'] != null) {
            formParams.append('id', requestParameters['id'] as any);
        }


        let urlPath = `/company/route/landmark`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a specific landmark assigned to a route by ID.       Requires `create_route` or `update_route` permission.       When deleting a landmark in a route, the route will be validated and status of the route will be updated.      Deletes the record if it exists.
     * Delete Landmark In Route
     */
    async deleteLandmarkInRouteCompanyRouteLandmarkDelete(requestParameters: DeleteLandmarkInRouteCompanyRouteLandmarkDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteLandmarkInRouteCompanyRouteLandmarkDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Fetch all landmarks assigned to routes.       Supports filtering by route ID, landmark ID, distance, delta times, etc.       Requires a valid executive token.
     * Fetch Landmarks In Route
     */
    async fetchLandmarksInRouteCompanyRouteLandmarkGetRaw(requestParameters: FetchLandmarksInRouteCompanyRouteLandmarkGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<LandmarkInRouteSchema>>> {
        const queryParameters: any = {};

        if (requestParameters['routeId'] != null) {
            queryParameters['route_id'] = requestParameters['routeId'];
        }

        if (requestParameters['landmarkId'] != null) {
            queryParameters['landmark_id'] = requestParameters['landmarkId'];
        }

        if (requestParameters['landmarkIdList'] != null) {
            queryParameters['landmark_id_list'] = requestParameters['landmarkIdList'];
        }

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['idGe'] != null) {
            queryParameters['id_ge'] = requestParameters['idGe'];
        }

        if (requestParameters['idLe'] != null) {
            queryParameters['id_le'] = requestParameters['idLe'];
        }

        if (requestParameters['idList'] != null) {
            queryParameters['id_list'] = requestParameters['idList'];
        }

        if (requestParameters['distanceFromStartGe'] != null) {
            queryParameters['distance_from_start_ge'] = requestParameters['distanceFromStartGe'];
        }

        if (requestParameters['distanceFromStartLe'] != null) {
            queryParameters['distance_from_start_le'] = requestParameters['distanceFromStartLe'];
        }

        if (requestParameters['arrivalDeltaGe'] != null) {
            queryParameters['arrival_delta_ge'] = requestParameters['arrivalDeltaGe'];
        }

        if (requestParameters['arrivalDeltaLe'] != null) {
            queryParameters['arrival_delta_le'] = requestParameters['arrivalDeltaLe'];
        }

        if (requestParameters['departureDeltaGe'] != null) {
            queryParameters['departure_delta_ge'] = requestParameters['departureDeltaGe'];
        }

        if (requestParameters['departureDeltaLe'] != null) {
            queryParameters['departure_delta_le'] = requestParameters['departureDeltaLe'];
        }

        if (requestParameters['updatedOnGe'] != null) {
            queryParameters['updated_on_ge'] = (requestParameters['updatedOnGe'] as any).toISOString();
        }

        if (requestParameters['updatedOnLe'] != null) {
            queryParameters['updated_on_le'] = (requestParameters['updatedOnLe'] as any).toISOString();
        }

        if (requestParameters['createdOnGe'] != null) {
            queryParameters['created_on_ge'] = (requestParameters['createdOnGe'] as any).toISOString();
        }

        if (requestParameters['createdOnLe'] != null) {
            queryParameters['created_on_le'] = (requestParameters['createdOnLe'] as any).toISOString();
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['order_by'] = requestParameters['orderBy'];
        }

        if (requestParameters['orderIn'] != null) {
            queryParameters['order_in'] = requestParameters['orderIn'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['companyId'] != null) {
            queryParameters['company_id'] = requestParameters['companyId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/company/route/landmark`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LandmarkInRouteSchemaFromJSON));
    }

    /**
     * Fetch all landmarks assigned to routes.       Supports filtering by route ID, landmark ID, distance, delta times, etc.       Requires a valid executive token.
     * Fetch Landmarks In Route
     */
    async fetchLandmarksInRouteCompanyRouteLandmarkGet(requestParameters: FetchLandmarksInRouteCompanyRouteLandmarkGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<LandmarkInRouteSchema>> {
        const response = await this.fetchLandmarksInRouteCompanyRouteLandmarkGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update properties of a landmark within a route.       Requires `create_route` or `update_route` permission.       Only updates fields that are explicitly provided.        When updating a landmark in a route, the route will be validated and status of the route will be updated.      Validates departure_delta is greater than arrival_delta.
     * Update Landmark In Route
     */
    async updateLandmarkInRouteCompanyRouteLandmarkPatchRaw(requestParameters: UpdateLandmarkInRouteCompanyRouteLandmarkPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LandmarkInRouteSchema>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateLandmarkInRouteCompanyRouteLandmarkPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['id'] != null) {
            formParams.append('id', requestParameters['id'] as any);
        }

        if (requestParameters['distanceFromStart'] != null) {
            formParams.append('distance_from_start', requestParameters['distanceFromStart'] as any);
        }

        if (requestParameters['arrivalDelta'] != null) {
            formParams.append('arrival_delta', requestParameters['arrivalDelta'] as any);
        }

        if (requestParameters['departureDelta'] != null) {
            formParams.append('departure_delta', requestParameters['departureDelta'] as any);
        }


        let urlPath = `/company/route/landmark`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LandmarkInRouteSchemaFromJSON(jsonValue));
    }

    /**
     * Update properties of a landmark within a route.       Requires `create_route` or `update_route` permission.       Only updates fields that are explicitly provided.        When updating a landmark in a route, the route will be validated and status of the route will be updated.      Validates departure_delta is greater than arrival_delta.
     * Update Landmark In Route
     */
    async updateLandmarkInRouteCompanyRouteLandmarkPatch(requestParameters: UpdateLandmarkInRouteCompanyRouteLandmarkPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LandmarkInRouteSchema> {
        const response = await this.updateLandmarkInRouteCompanyRouteLandmarkPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
