/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppApiOperatorRoleMapOrderBy,
  AppApiVendorRoleMapOrderIn,
  ErrorResponse,
  HTTPValidationError,
  OperatorRoleMapSchema,
} from '../models/index';
import {
    AppApiOperatorRoleMapOrderByFromJSON,
    AppApiOperatorRoleMapOrderByToJSON,
    AppApiVendorRoleMapOrderInFromJSON,
    AppApiVendorRoleMapOrderInToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    OperatorRoleMapSchemaFromJSON,
    OperatorRoleMapSchemaToJSON,
} from '../models/index';

export interface CreateRoleMapCompanyAccountRolePostRequest {
    roleId: number;
    operatorId: number;
}

export interface DeleteRoleMapCompanyAccountRoleDeleteRequest {
    id: number;
}

export interface FetchRoleMapCompanyAccountRoleGetRequest {
    roleId?: number | null;
    operatorId?: number | null;
    id?: number | null;
    idGe?: number | null;
    idLe?: number | null;
    idList?: Array<number> | null;
    updatedOnGe?: Date | null;
    updatedOnLe?: Date | null;
    createdOnGe?: Date | null;
    createdOnLe?: Date | null;
    orderBy?: AppApiOperatorRoleMapOrderBy;
    orderIn?: AppApiVendorRoleMapOrderIn;
    offset?: number;
    limit?: number;
    companyId?: number | null;
}

export interface UpdateRoleMapCompanyAccountRolePatchRequest {
    id: number;
    roleId?: number | null;
}

/**
 * 
 */
export class OperatorRoleMapApi extends runtime.BaseAPI {

    /**
     * Assign a role to an operator account.         Only authorized users with `update_op_role` permission can create a new role map.         Log the role map creation activity with the associated token.
     * Create Role Map
     */
    async createRoleMapCompanyAccountRolePostRaw(requestParameters: CreateRoleMapCompanyAccountRolePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperatorRoleMapSchema>> {
        if (requestParameters['roleId'] == null) {
            throw new runtime.RequiredError(
                'roleId',
                'Required parameter "roleId" was null or undefined when calling createRoleMapCompanyAccountRolePost().'
            );
        }

        if (requestParameters['operatorId'] == null) {
            throw new runtime.RequiredError(
                'operatorId',
                'Required parameter "operatorId" was null or undefined when calling createRoleMapCompanyAccountRolePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['roleId'] != null) {
            formParams.append('role_id', requestParameters['roleId'] as any);
        }

        if (requestParameters['operatorId'] != null) {
            formParams.append('operator_id', requestParameters['operatorId'] as any);
        }


        let urlPath = `/company/account/role`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OperatorRoleMapSchemaFromJSON(jsonValue));
    }

    /**
     * Assign a role to an operator account.         Only authorized users with `update_op_role` permission can create a new role map.         Log the role map creation activity with the associated token.
     * Create Role Map
     */
    async createRoleMapCompanyAccountRolePost(requestParameters: CreateRoleMapCompanyAccountRolePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperatorRoleMapSchema> {
        const response = await this.createRoleMapCompanyAccountRolePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes an existing operator role maps.            Only executives with `update_op_role` permission can perform this operation.         Validates the role map ID before deletion.            If the mapping exists, it is permanently removed from the system.            Logs the deletion activity using the executive\'s token and request metadata.
     * Delete Role Map
     */
    async deleteRoleMapCompanyAccountRoleDeleteRaw(requestParameters: DeleteRoleMapCompanyAccountRoleDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteRoleMapCompanyAccountRoleDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['id'] != null) {
            formParams.append('id', requestParameters['id'] as any);
        }


        let urlPath = `/company/account/role`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes an existing operator role maps.            Only executives with `update_op_role` permission can perform this operation.         Validates the role map ID before deletion.            If the mapping exists, it is permanently removed from the system.            Logs the deletion activity using the executive\'s token and request metadata.
     * Delete Role Map
     */
    async deleteRoleMapCompanyAccountRoleDelete(requestParameters: DeleteRoleMapCompanyAccountRoleDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteRoleMapCompanyAccountRoleDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Fetches a list of all operator role maps across companies.            Supports filtering by ID and metadata.        Supports filtering, sorting, and pagination.          Requires a valid executive token.
     * Fetch Role Map
     */
    async fetchRoleMapCompanyAccountRoleGetRaw(requestParameters: FetchRoleMapCompanyAccountRoleGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OperatorRoleMapSchema>>> {
        const queryParameters: any = {};

        if (requestParameters['roleId'] != null) {
            queryParameters['role_id'] = requestParameters['roleId'];
        }

        if (requestParameters['operatorId'] != null) {
            queryParameters['operator_id'] = requestParameters['operatorId'];
        }

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['idGe'] != null) {
            queryParameters['id_ge'] = requestParameters['idGe'];
        }

        if (requestParameters['idLe'] != null) {
            queryParameters['id_le'] = requestParameters['idLe'];
        }

        if (requestParameters['idList'] != null) {
            queryParameters['id_list'] = requestParameters['idList'];
        }

        if (requestParameters['updatedOnGe'] != null) {
            queryParameters['updated_on_ge'] = (requestParameters['updatedOnGe'] as any).toISOString();
        }

        if (requestParameters['updatedOnLe'] != null) {
            queryParameters['updated_on_le'] = (requestParameters['updatedOnLe'] as any).toISOString();
        }

        if (requestParameters['createdOnGe'] != null) {
            queryParameters['created_on_ge'] = (requestParameters['createdOnGe'] as any).toISOString();
        }

        if (requestParameters['createdOnLe'] != null) {
            queryParameters['created_on_le'] = (requestParameters['createdOnLe'] as any).toISOString();
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['order_by'] = requestParameters['orderBy'];
        }

        if (requestParameters['orderIn'] != null) {
            queryParameters['order_in'] = requestParameters['orderIn'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['companyId'] != null) {
            queryParameters['company_id'] = requestParameters['companyId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/company/account/role`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OperatorRoleMapSchemaFromJSON));
    }

    /**
     * Fetches a list of all operator role maps across companies.            Supports filtering by ID and metadata.        Supports filtering, sorting, and pagination.          Requires a valid executive token.
     * Fetch Role Map
     */
    async fetchRoleMapCompanyAccountRoleGet(requestParameters: FetchRoleMapCompanyAccountRoleGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OperatorRoleMapSchema>> {
        const response = await this.fetchRoleMapCompanyAccountRoleGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates an existing role maps.            Only executives with `update_op_role` permission can perform this operation.         Support partial updates such as modifying the role_id.             Logs the role map updating activity with the associated token.
     * Update Role Map
     */
    async updateRoleMapCompanyAccountRolePatchRaw(requestParameters: UpdateRoleMapCompanyAccountRolePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperatorRoleMapSchema>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateRoleMapCompanyAccountRolePatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['id'] != null) {
            formParams.append('id', requestParameters['id'] as any);
        }

        if (requestParameters['roleId'] != null) {
            formParams.append('role_id', requestParameters['roleId'] as any);
        }


        let urlPath = `/company/account/role`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OperatorRoleMapSchemaFromJSON(jsonValue));
    }

    /**
     * Updates an existing role maps.            Only executives with `update_op_role` permission can perform this operation.         Support partial updates such as modifying the role_id.             Logs the role map updating activity with the associated token.
     * Update Role Map
     */
    async updateRoleMapCompanyAccountRolePatch(requestParameters: UpdateRoleMapCompanyAccountRolePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperatorRoleMapSchema> {
        const response = await this.updateRoleMapCompanyAccountRolePatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
