/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccountStatus,
  AppApiOperatorAccountOrderBy,
  AppApiVendorRoleMapOrderIn,
  ErrorResponse,
  GenderType,
  HTTPValidationError,
  OperatorSchema,
} from '../models/index';
import {
    AccountStatusFromJSON,
    AccountStatusToJSON,
    AppApiOperatorAccountOrderByFromJSON,
    AppApiOperatorAccountOrderByToJSON,
    AppApiVendorRoleMapOrderInFromJSON,
    AppApiVendorRoleMapOrderInToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    GenderTypeFromJSON,
    GenderTypeToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    OperatorSchemaFromJSON,
    OperatorSchemaToJSON,
} from '../models/index';

export interface CreateOperatorCompanyAccountPostRequest {
    username: string;
    password: string;
    companyId: number;
    gender?: GenderType;
    fullName?: string | null;
    phoneNumber?: string | null;
    emailId?: string | null;
}

export interface DeleteOperatorCompanyAccountDeleteRequest {
    id: number;
}

export interface FetchOperatorCompanyAccountGetRequest {
    username?: string | null;
    gender?: GenderType | null;
    fullName?: string | null;
    status?: AccountStatus | null;
    phoneNumber?: string | null;
    emailId?: string | null;
    id?: number | null;
    idGe?: number | null;
    idLe?: number | null;
    idList?: Array<number> | null;
    updatedOnGe?: Date | null;
    updatedOnLe?: Date | null;
    createdOnGe?: Date | null;
    createdOnLe?: Date | null;
    orderBy?: AppApiOperatorAccountOrderBy;
    orderIn?: AppApiVendorRoleMapOrderIn;
    offset?: number;
    limit?: number;
    companyId?: number | null;
}

export interface UpdateOperatorCompanyAccountPatchRequest {
    id: number;
    password?: string | null;
    gender?: GenderType | null;
    fullName?: string | null;
    status?: AccountStatus | null;
    phoneNumber?: string | null;
    emailId?: string | null;
}

/**
 * 
 */
export class OperatorAccountApi extends runtime.BaseAPI {

    /**
     * Creates a new operator account with an active status.            Only executive with `create_operator` permission can create operator.            Logs the operator account creation activity with the associated token.          Follow patterns for smooth creation of username and password.            The password is hashed using Argon2 before storing.
     * Create Operator
     */
    async createOperatorCompanyAccountPostRaw(requestParameters: CreateOperatorCompanyAccountPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperatorSchema>> {
        if (requestParameters['username'] == null) {
            throw new runtime.RequiredError(
                'username',
                'Required parameter "username" was null or undefined when calling createOperatorCompanyAccountPost().'
            );
        }

        if (requestParameters['password'] == null) {
            throw new runtime.RequiredError(
                'password',
                'Required parameter "password" was null or undefined when calling createOperatorCompanyAccountPost().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling createOperatorCompanyAccountPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['username'] != null) {
            formParams.append('username', requestParameters['username'] as any);
        }

        if (requestParameters['password'] != null) {
            formParams.append('password', requestParameters['password'] as any);
        }

        if (requestParameters['gender'] != null) {
            formParams.append('gender', requestParameters['gender'] as any);
        }

        if (requestParameters['fullName'] != null) {
            formParams.append('full_name', requestParameters['fullName'] as any);
        }

        if (requestParameters['phoneNumber'] != null) {
            formParams.append('phone_number', requestParameters['phoneNumber'] as any);
        }

        if (requestParameters['emailId'] != null) {
            formParams.append('email_id', requestParameters['emailId'] as any);
        }

        if (requestParameters['companyId'] != null) {
            formParams.append('company_id', requestParameters['companyId'] as any);
        }


        let urlPath = `/company/account`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OperatorSchemaFromJSON(jsonValue));
    }

    /**
     * Creates a new operator account with an active status.            Only executive with `create_operator` permission can create operator.            Logs the operator account creation activity with the associated token.          Follow patterns for smooth creation of username and password.            The password is hashed using Argon2 before storing.
     * Create Operator
     */
    async createOperatorCompanyAccountPost(requestParameters: CreateOperatorCompanyAccountPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperatorSchema> {
        const response = await this.createOperatorCompanyAccountPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an existing operator by ID.       Requires executive permissions with `delete_operator` role.       Deletes the operator and logs the deletion event.
     * Delete Operator
     */
    async deleteOperatorCompanyAccountDeleteRaw(requestParameters: DeleteOperatorCompanyAccountDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteOperatorCompanyAccountDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['id'] != null) {
            formParams.append('id', requestParameters['id'] as any);
        }


        let urlPath = `/company/account`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an existing operator by ID.       Requires executive permissions with `delete_operator` role.       Deletes the operator and logs the deletion event.
     * Delete Operator
     */
    async deleteOperatorCompanyAccountDelete(requestParameters: DeleteOperatorCompanyAccountDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteOperatorCompanyAccountDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Fetch operator accounts with filtering, sorting, and pagination.         Filter by company_id, username, gender, designation, contact details, status, and creation/update timestamps.        Filter by ID ranges or lists.         Sort by ID, creation date, or update date in ascending or descending order.          Paginate using offset and limit.         Returns a list of operator accounts matching the criteria.           Requires a valid executive token.
     * Fetch Operator
     */
    async fetchOperatorCompanyAccountGetRaw(requestParameters: FetchOperatorCompanyAccountGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OperatorSchema>>> {
        const queryParameters: any = {};

        if (requestParameters['username'] != null) {
            queryParameters['username'] = requestParameters['username'];
        }

        if (requestParameters['gender'] != null) {
            queryParameters['gender'] = requestParameters['gender'];
        }

        if (requestParameters['fullName'] != null) {
            queryParameters['full_name'] = requestParameters['fullName'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['phoneNumber'] != null) {
            queryParameters['phone_number'] = requestParameters['phoneNumber'];
        }

        if (requestParameters['emailId'] != null) {
            queryParameters['email_id'] = requestParameters['emailId'];
        }

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['idGe'] != null) {
            queryParameters['id_ge'] = requestParameters['idGe'];
        }

        if (requestParameters['idLe'] != null) {
            queryParameters['id_le'] = requestParameters['idLe'];
        }

        if (requestParameters['idList'] != null) {
            queryParameters['id_list'] = requestParameters['idList'];
        }

        if (requestParameters['updatedOnGe'] != null) {
            queryParameters['updated_on_ge'] = (requestParameters['updatedOnGe'] as any).toISOString();
        }

        if (requestParameters['updatedOnLe'] != null) {
            queryParameters['updated_on_le'] = (requestParameters['updatedOnLe'] as any).toISOString();
        }

        if (requestParameters['createdOnGe'] != null) {
            queryParameters['created_on_ge'] = (requestParameters['createdOnGe'] as any).toISOString();
        }

        if (requestParameters['createdOnLe'] != null) {
            queryParameters['created_on_le'] = (requestParameters['createdOnLe'] as any).toISOString();
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['order_by'] = requestParameters['orderBy'];
        }

        if (requestParameters['orderIn'] != null) {
            queryParameters['order_in'] = requestParameters['orderIn'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['companyId'] != null) {
            queryParameters['company_id'] = requestParameters['companyId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/company/account`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OperatorSchemaFromJSON));
    }

    /**
     * Fetch operator accounts with filtering, sorting, and pagination.         Filter by company_id, username, gender, designation, contact details, status, and creation/update timestamps.        Filter by ID ranges or lists.         Sort by ID, creation date, or update date in ascending or descending order.          Paginate using offset and limit.         Returns a list of operator accounts matching the criteria.           Requires a valid executive token.
     * Fetch Operator
     */
    async fetchOperatorCompanyAccountGet(requestParameters: FetchOperatorCompanyAccountGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OperatorSchema>> {
        const response = await this.fetchOperatorCompanyAccountGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates an existing operator account.            Executive with `update_operator` permission can update operators.          Follow patterns for smooth creation of password.             The password is hashed using Argon2 before storing.              If the status is set to`SUSPENDED, all tokens associated with that operator are revoked.           Logs the operator account update activity with the associated token.
     * Update Operator
     */
    async updateOperatorCompanyAccountPatchRaw(requestParameters: UpdateOperatorCompanyAccountPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperatorSchema>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateOperatorCompanyAccountPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['id'] != null) {
            formParams.append('id', requestParameters['id'] as any);
        }

        if (requestParameters['password'] != null) {
            formParams.append('password', requestParameters['password'] as any);
        }

        if (requestParameters['gender'] != null) {
            formParams.append('gender', requestParameters['gender'] as any);
        }

        if (requestParameters['fullName'] != null) {
            formParams.append('full_name', requestParameters['fullName'] as any);
        }

        if (requestParameters['status'] != null) {
            formParams.append('status', requestParameters['status'] as any);
        }

        if (requestParameters['phoneNumber'] != null) {
            formParams.append('phone_number', requestParameters['phoneNumber'] as any);
        }

        if (requestParameters['emailId'] != null) {
            formParams.append('email_id', requestParameters['emailId'] as any);
        }


        let urlPath = `/company/account`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OperatorSchemaFromJSON(jsonValue));
    }

    /**
     * Updates an existing operator account.            Executive with `update_operator` permission can update operators.          Follow patterns for smooth creation of password.             The password is hashed using Argon2 before storing.              If the status is set to`SUSPENDED, all tokens associated with that operator are revoked.           Logs the operator account update activity with the associated token.
     * Update Operator
     */
    async updateOperatorCompanyAccountPatch(requestParameters: UpdateOperatorCompanyAccountPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperatorSchema> {
        const response = await this.updateOperatorCompanyAccountPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
