/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppApiOperatorRoleOrderBy,
  AppApiVendorRoleMapOrderIn,
  ErrorResponse,
  HTTPValidationError,
  OperatorRoleSchema,
} from '../models/index';
import {
    AppApiOperatorRoleOrderByFromJSON,
    AppApiOperatorRoleOrderByToJSON,
    AppApiVendorRoleMapOrderInFromJSON,
    AppApiVendorRoleMapOrderInToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    OperatorRoleSchemaFromJSON,
    OperatorRoleSchemaToJSON,
} from '../models/index';

export interface CreateRoleCompanyRolePostRequest {
    name: string;
    companyId: number;
    manageToken?: boolean;
    updateCompany?: boolean;
    createOperator?: boolean;
    updateOperator?: boolean;
    deleteOperator?: boolean;
    createRoute?: boolean;
    updateRoute?: boolean;
    deleteRoute?: boolean;
    createBus?: boolean;
    updateBus?: boolean;
    deleteBus?: boolean;
    createSchedule?: boolean;
    updateSchedule?: boolean;
    deleteSchedule?: boolean;
    createService?: boolean;
    updateService?: boolean;
    deleteService?: boolean;
    createFare?: boolean;
    updateFare?: boolean;
    deleteFare?: boolean;
    createDuty?: boolean;
    updateDuty?: boolean;
    deleteDuty?: boolean;
    createRole?: boolean;
    updateRole?: boolean;
    deleteRole?: boolean;
}

export interface DeleteRoleCompanyRoleDeleteRequest {
    id: number;
}

export interface FetchRoleCompanyRoleGetRequest {
    name?: string | null;
    id?: number | null;
    idGe?: number | null;
    idLe?: number | null;
    idList?: Array<number> | null;
    manageToken?: boolean | null;
    updateCompany?: boolean | null;
    createOperator?: boolean | null;
    updateOperator?: boolean | null;
    deleteOperator?: boolean | null;
    createRoute?: boolean | null;
    updateRoute?: boolean | null;
    deleteRoute?: boolean | null;
    createBus?: boolean | null;
    updateBus?: boolean | null;
    deleteBus?: boolean | null;
    createSchedule?: boolean | null;
    updateSchedule?: boolean | null;
    deleteSchedule?: boolean | null;
    createService?: boolean | null;
    updateService?: boolean | null;
    deleteService?: boolean | null;
    createFare?: boolean | null;
    updateFare?: boolean | null;
    deleteFare?: boolean | null;
    createDuty?: boolean | null;
    updateDuty?: boolean | null;
    deleteDuty?: boolean | null;
    createRole?: boolean | null;
    updateRole?: boolean | null;
    deleteRole?: boolean | null;
    updatedOnGe?: Date | null;
    updatedOnLe?: Date | null;
    createdOnGe?: Date | null;
    createdOnLe?: Date | null;
    orderBy?: AppApiOperatorRoleOrderBy;
    orderIn?: AppApiVendorRoleMapOrderIn;
    offset?: number;
    limit?: number;
    companyId?: number | null;
}

export interface UpdateRoleCompanyRolePatchRequest {
    id: number;
    name?: string | null;
    manageToken?: boolean | null;
    updateCompany?: boolean | null;
    createOperator?: boolean | null;
    updateOperator?: boolean | null;
    deleteOperator?: boolean | null;
    createRoute?: boolean | null;
    updateRoute?: boolean | null;
    deleteRoute?: boolean | null;
    createBus?: boolean | null;
    updateBus?: boolean | null;
    deleteBus?: boolean | null;
    createSchedule?: boolean | null;
    updateSchedule?: boolean | null;
    deleteSchedule?: boolean | null;
    createService?: boolean | null;
    updateService?: boolean | null;
    deleteService?: boolean | null;
    createFare?: boolean | null;
    updateFare?: boolean | null;
    deleteFare?: boolean | null;
    createDuty?: boolean | null;
    updateDuty?: boolean | null;
    deleteDuty?: boolean | null;
    createRole?: boolean | null;
    updateRole?: boolean | null;
    deleteRole?: boolean | null;
}

/**
 * 
 */
export class OperatorRoleApi extends runtime.BaseAPI {

    /**
     * Create a new operator role.          Only authorized users with `create_op_role` permission can create a new role.           Role name must be unique across the company.             Log the role creation activity with the associated token.
     * Create Role
     */
    async createRoleCompanyRolePostRaw(requestParameters: CreateRoleCompanyRolePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperatorRoleSchema>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling createRoleCompanyRolePost().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling createRoleCompanyRolePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['name'] != null) {
            formParams.append('name', requestParameters['name'] as any);
        }

        if (requestParameters['manageToken'] != null) {
            formParams.append('manage_token', requestParameters['manageToken'] as any);
        }

        if (requestParameters['updateCompany'] != null) {
            formParams.append('update_company', requestParameters['updateCompany'] as any);
        }

        if (requestParameters['createOperator'] != null) {
            formParams.append('create_operator', requestParameters['createOperator'] as any);
        }

        if (requestParameters['updateOperator'] != null) {
            formParams.append('update_operator', requestParameters['updateOperator'] as any);
        }

        if (requestParameters['deleteOperator'] != null) {
            formParams.append('delete_operator', requestParameters['deleteOperator'] as any);
        }

        if (requestParameters['createRoute'] != null) {
            formParams.append('create_route', requestParameters['createRoute'] as any);
        }

        if (requestParameters['updateRoute'] != null) {
            formParams.append('update_route', requestParameters['updateRoute'] as any);
        }

        if (requestParameters['deleteRoute'] != null) {
            formParams.append('delete_route', requestParameters['deleteRoute'] as any);
        }

        if (requestParameters['createBus'] != null) {
            formParams.append('create_bus', requestParameters['createBus'] as any);
        }

        if (requestParameters['updateBus'] != null) {
            formParams.append('update_bus', requestParameters['updateBus'] as any);
        }

        if (requestParameters['deleteBus'] != null) {
            formParams.append('delete_bus', requestParameters['deleteBus'] as any);
        }

        if (requestParameters['createSchedule'] != null) {
            formParams.append('create_schedule', requestParameters['createSchedule'] as any);
        }

        if (requestParameters['updateSchedule'] != null) {
            formParams.append('update_schedule', requestParameters['updateSchedule'] as any);
        }

        if (requestParameters['deleteSchedule'] != null) {
            formParams.append('delete_schedule', requestParameters['deleteSchedule'] as any);
        }

        if (requestParameters['createService'] != null) {
            formParams.append('create_service', requestParameters['createService'] as any);
        }

        if (requestParameters['updateService'] != null) {
            formParams.append('update_service', requestParameters['updateService'] as any);
        }

        if (requestParameters['deleteService'] != null) {
            formParams.append('delete_service', requestParameters['deleteService'] as any);
        }

        if (requestParameters['createFare'] != null) {
            formParams.append('create_fare', requestParameters['createFare'] as any);
        }

        if (requestParameters['updateFare'] != null) {
            formParams.append('update_fare', requestParameters['updateFare'] as any);
        }

        if (requestParameters['deleteFare'] != null) {
            formParams.append('delete_fare', requestParameters['deleteFare'] as any);
        }

        if (requestParameters['createDuty'] != null) {
            formParams.append('create_duty', requestParameters['createDuty'] as any);
        }

        if (requestParameters['updateDuty'] != null) {
            formParams.append('update_duty', requestParameters['updateDuty'] as any);
        }

        if (requestParameters['deleteDuty'] != null) {
            formParams.append('delete_duty', requestParameters['deleteDuty'] as any);
        }

        if (requestParameters['createRole'] != null) {
            formParams.append('create_role', requestParameters['createRole'] as any);
        }

        if (requestParameters['updateRole'] != null) {
            formParams.append('update_role', requestParameters['updateRole'] as any);
        }

        if (requestParameters['deleteRole'] != null) {
            formParams.append('delete_role', requestParameters['deleteRole'] as any);
        }

        if (requestParameters['companyId'] != null) {
            formParams.append('company_id', requestParameters['companyId'] as any);
        }


        let urlPath = `/company/role`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OperatorRoleSchemaFromJSON(jsonValue));
    }

    /**
     * Create a new operator role.          Only authorized users with `create_op_role` permission can create a new role.           Role name must be unique across the company.             Log the role creation activity with the associated token.
     * Create Role
     */
    async createRoleCompanyRolePost(requestParameters: CreateRoleCompanyRolePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperatorRoleSchema> {
        const response = await this.createRoleCompanyRolePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes an existing operator role.            Only executives with `delete_op_role` permission can perform this operation.         Validates the role ID before deletion.            If the role exists, it is permanently removed from the system.            Logs the deletion activity using the executive\'s token and request metadata.
     * Delete Role
     */
    async deleteRoleCompanyRoleDeleteRaw(requestParameters: DeleteRoleCompanyRoleDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteRoleCompanyRoleDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['id'] != null) {
            formParams.append('id', requestParameters['id'] as any);
        }


        let urlPath = `/company/role`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes an existing operator role.            Only executives with `delete_op_role` permission can perform this operation.         Validates the role ID before deletion.            If the role exists, it is permanently removed from the system.            Logs the deletion activity using the executive\'s token and request metadata.
     * Delete Role
     */
    async deleteRoleCompanyRoleDelete(requestParameters: DeleteRoleCompanyRoleDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteRoleCompanyRoleDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Fetches a list of all operator role across companies.            Supports filtering by ID, name, permissions and metadata.        Supports filtering, sorting, and pagination.          Requires a valid executive token.
     * Fetch Role
     */
    async fetchRoleCompanyRoleGetRaw(requestParameters: FetchRoleCompanyRoleGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OperatorRoleSchema>>> {
        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['idGe'] != null) {
            queryParameters['id_ge'] = requestParameters['idGe'];
        }

        if (requestParameters['idLe'] != null) {
            queryParameters['id_le'] = requestParameters['idLe'];
        }

        if (requestParameters['idList'] != null) {
            queryParameters['id_list'] = requestParameters['idList'];
        }

        if (requestParameters['manageToken'] != null) {
            queryParameters['manage_token'] = requestParameters['manageToken'];
        }

        if (requestParameters['updateCompany'] != null) {
            queryParameters['update_company'] = requestParameters['updateCompany'];
        }

        if (requestParameters['createOperator'] != null) {
            queryParameters['create_operator'] = requestParameters['createOperator'];
        }

        if (requestParameters['updateOperator'] != null) {
            queryParameters['update_operator'] = requestParameters['updateOperator'];
        }

        if (requestParameters['deleteOperator'] != null) {
            queryParameters['delete_operator'] = requestParameters['deleteOperator'];
        }

        if (requestParameters['createRoute'] != null) {
            queryParameters['create_route'] = requestParameters['createRoute'];
        }

        if (requestParameters['updateRoute'] != null) {
            queryParameters['update_route'] = requestParameters['updateRoute'];
        }

        if (requestParameters['deleteRoute'] != null) {
            queryParameters['delete_route'] = requestParameters['deleteRoute'];
        }

        if (requestParameters['createBus'] != null) {
            queryParameters['create_bus'] = requestParameters['createBus'];
        }

        if (requestParameters['updateBus'] != null) {
            queryParameters['update_bus'] = requestParameters['updateBus'];
        }

        if (requestParameters['deleteBus'] != null) {
            queryParameters['delete_bus'] = requestParameters['deleteBus'];
        }

        if (requestParameters['createSchedule'] != null) {
            queryParameters['create_schedule'] = requestParameters['createSchedule'];
        }

        if (requestParameters['updateSchedule'] != null) {
            queryParameters['update_schedule'] = requestParameters['updateSchedule'];
        }

        if (requestParameters['deleteSchedule'] != null) {
            queryParameters['delete_schedule'] = requestParameters['deleteSchedule'];
        }

        if (requestParameters['createService'] != null) {
            queryParameters['create_service'] = requestParameters['createService'];
        }

        if (requestParameters['updateService'] != null) {
            queryParameters['update_service'] = requestParameters['updateService'];
        }

        if (requestParameters['deleteService'] != null) {
            queryParameters['delete_service'] = requestParameters['deleteService'];
        }

        if (requestParameters['createFare'] != null) {
            queryParameters['create_fare'] = requestParameters['createFare'];
        }

        if (requestParameters['updateFare'] != null) {
            queryParameters['update_fare'] = requestParameters['updateFare'];
        }

        if (requestParameters['deleteFare'] != null) {
            queryParameters['delete_fare'] = requestParameters['deleteFare'];
        }

        if (requestParameters['createDuty'] != null) {
            queryParameters['create_duty'] = requestParameters['createDuty'];
        }

        if (requestParameters['updateDuty'] != null) {
            queryParameters['update_duty'] = requestParameters['updateDuty'];
        }

        if (requestParameters['deleteDuty'] != null) {
            queryParameters['delete_duty'] = requestParameters['deleteDuty'];
        }

        if (requestParameters['createRole'] != null) {
            queryParameters['create_role'] = requestParameters['createRole'];
        }

        if (requestParameters['updateRole'] != null) {
            queryParameters['update_role'] = requestParameters['updateRole'];
        }

        if (requestParameters['deleteRole'] != null) {
            queryParameters['delete_role'] = requestParameters['deleteRole'];
        }

        if (requestParameters['updatedOnGe'] != null) {
            queryParameters['updated_on_ge'] = (requestParameters['updatedOnGe'] as any).toISOString();
        }

        if (requestParameters['updatedOnLe'] != null) {
            queryParameters['updated_on_le'] = (requestParameters['updatedOnLe'] as any).toISOString();
        }

        if (requestParameters['createdOnGe'] != null) {
            queryParameters['created_on_ge'] = (requestParameters['createdOnGe'] as any).toISOString();
        }

        if (requestParameters['createdOnLe'] != null) {
            queryParameters['created_on_le'] = (requestParameters['createdOnLe'] as any).toISOString();
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['order_by'] = requestParameters['orderBy'];
        }

        if (requestParameters['orderIn'] != null) {
            queryParameters['order_in'] = requestParameters['orderIn'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['companyId'] != null) {
            queryParameters['company_id'] = requestParameters['companyId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/company/role`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OperatorRoleSchemaFromJSON));
    }

    /**
     * Fetches a list of all operator role across companies.            Supports filtering by ID, name, permissions and metadata.        Supports filtering, sorting, and pagination.          Requires a valid executive token.
     * Fetch Role
     */
    async fetchRoleCompanyRoleGet(requestParameters: FetchRoleCompanyRoleGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OperatorRoleSchema>> {
        const response = await this.fetchRoleCompanyRoleGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates an existing operator role.            Only executives with `update_op_role` permission can perform this operation.         Support partial updates such as modifying the role name.            Changes are saved only if the role data has been modified.             Logs the role updating activity with the associated token.
     * Update Role
     */
    async updateRoleCompanyRolePatchRaw(requestParameters: UpdateRoleCompanyRolePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperatorRoleSchema>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateRoleCompanyRolePatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['id'] != null) {
            formParams.append('id', requestParameters['id'] as any);
        }

        if (requestParameters['name'] != null) {
            formParams.append('name', requestParameters['name'] as any);
        }

        if (requestParameters['manageToken'] != null) {
            formParams.append('manage_token', requestParameters['manageToken'] as any);
        }

        if (requestParameters['updateCompany'] != null) {
            formParams.append('update_company', requestParameters['updateCompany'] as any);
        }

        if (requestParameters['createOperator'] != null) {
            formParams.append('create_operator', requestParameters['createOperator'] as any);
        }

        if (requestParameters['updateOperator'] != null) {
            formParams.append('update_operator', requestParameters['updateOperator'] as any);
        }

        if (requestParameters['deleteOperator'] != null) {
            formParams.append('delete_operator', requestParameters['deleteOperator'] as any);
        }

        if (requestParameters['createRoute'] != null) {
            formParams.append('create_route', requestParameters['createRoute'] as any);
        }

        if (requestParameters['updateRoute'] != null) {
            formParams.append('update_route', requestParameters['updateRoute'] as any);
        }

        if (requestParameters['deleteRoute'] != null) {
            formParams.append('delete_route', requestParameters['deleteRoute'] as any);
        }

        if (requestParameters['createBus'] != null) {
            formParams.append('create_bus', requestParameters['createBus'] as any);
        }

        if (requestParameters['updateBus'] != null) {
            formParams.append('update_bus', requestParameters['updateBus'] as any);
        }

        if (requestParameters['deleteBus'] != null) {
            formParams.append('delete_bus', requestParameters['deleteBus'] as any);
        }

        if (requestParameters['createSchedule'] != null) {
            formParams.append('create_schedule', requestParameters['createSchedule'] as any);
        }

        if (requestParameters['updateSchedule'] != null) {
            formParams.append('update_schedule', requestParameters['updateSchedule'] as any);
        }

        if (requestParameters['deleteSchedule'] != null) {
            formParams.append('delete_schedule', requestParameters['deleteSchedule'] as any);
        }

        if (requestParameters['createService'] != null) {
            formParams.append('create_service', requestParameters['createService'] as any);
        }

        if (requestParameters['updateService'] != null) {
            formParams.append('update_service', requestParameters['updateService'] as any);
        }

        if (requestParameters['deleteService'] != null) {
            formParams.append('delete_service', requestParameters['deleteService'] as any);
        }

        if (requestParameters['createFare'] != null) {
            formParams.append('create_fare', requestParameters['createFare'] as any);
        }

        if (requestParameters['updateFare'] != null) {
            formParams.append('update_fare', requestParameters['updateFare'] as any);
        }

        if (requestParameters['deleteFare'] != null) {
            formParams.append('delete_fare', requestParameters['deleteFare'] as any);
        }

        if (requestParameters['createDuty'] != null) {
            formParams.append('create_duty', requestParameters['createDuty'] as any);
        }

        if (requestParameters['updateDuty'] != null) {
            formParams.append('update_duty', requestParameters['updateDuty'] as any);
        }

        if (requestParameters['deleteDuty'] != null) {
            formParams.append('delete_duty', requestParameters['deleteDuty'] as any);
        }

        if (requestParameters['createRole'] != null) {
            formParams.append('create_role', requestParameters['createRole'] as any);
        }

        if (requestParameters['updateRole'] != null) {
            formParams.append('update_role', requestParameters['updateRole'] as any);
        }

        if (requestParameters['deleteRole'] != null) {
            formParams.append('delete_role', requestParameters['deleteRole'] as any);
        }


        let urlPath = `/company/role`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OperatorRoleSchemaFromJSON(jsonValue));
    }

    /**
     * Updates an existing operator role.            Only executives with `update_op_role` permission can perform this operation.         Support partial updates such as modifying the role name.            Changes are saved only if the role data has been modified.             Logs the role updating activity with the associated token.
     * Update Role
     */
    async updateRoleCompanyRolePatch(requestParameters: UpdateRoleCompanyRolePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperatorRoleSchema> {
        const response = await this.updateRoleCompanyRolePatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
