/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppApiExecutiveRoleMapOrderBy,
  AppApiVendorRoleMapOrderIn,
  ErrorResponse,
  ExecutiveRoleMapSchema,
  HTTPValidationError,
} from '../models/index';
import {
    AppApiExecutiveRoleMapOrderByFromJSON,
    AppApiExecutiveRoleMapOrderByToJSON,
    AppApiVendorRoleMapOrderInFromJSON,
    AppApiVendorRoleMapOrderInToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ExecutiveRoleMapSchemaFromJSON,
    ExecutiveRoleMapSchemaToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CreateRoleMapEntebusAccountRolePostRequest {
    roleId: number;
    executiveId: number;
}

export interface DeleteRoleMapEntebusAccountRoleDeleteRequest {
    id: number;
}

export interface FetchRoleMapEntebusAccountRoleGetRequest {
    roleId?: number | null;
    executiveId?: number | null;
    id?: number | null;
    idGe?: number | null;
    idLe?: number | null;
    idList?: Array<number> | null;
    updatedOnGe?: Date | null;
    updatedOnLe?: Date | null;
    createdOnGe?: Date | null;
    createdOnLe?: Date | null;
    orderBy?: AppApiExecutiveRoleMapOrderBy;
    orderIn?: AppApiVendorRoleMapOrderIn;
    offset?: number;
    limit?: number;
}

export interface UpdateRoleMapEntebusAccountRolePatchRequest {
    id: number;
    roleId?: number | null;
}

/**
 * 
 */
export class RoleMapApi extends runtime.BaseAPI {

    /**
     * Assign a role to an executive account.         Only authorized users with `update_ex_role` permission can create a new role map.         Log the role map creation activity with the associated token.
     * Create Role Map
     */
    async createRoleMapEntebusAccountRolePostRaw(requestParameters: CreateRoleMapEntebusAccountRolePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExecutiveRoleMapSchema>> {
        if (requestParameters['roleId'] == null) {
            throw new runtime.RequiredError(
                'roleId',
                'Required parameter "roleId" was null or undefined when calling createRoleMapEntebusAccountRolePost().'
            );
        }

        if (requestParameters['executiveId'] == null) {
            throw new runtime.RequiredError(
                'executiveId',
                'Required parameter "executiveId" was null or undefined when calling createRoleMapEntebusAccountRolePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['roleId'] != null) {
            formParams.append('role_id', requestParameters['roleId'] as any);
        }

        if (requestParameters['executiveId'] != null) {
            formParams.append('executive_id', requestParameters['executiveId'] as any);
        }


        let urlPath = `/entebus/account/role`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExecutiveRoleMapSchemaFromJSON(jsonValue));
    }

    /**
     * Assign a role to an executive account.         Only authorized users with `update_ex_role` permission can create a new role map.         Log the role map creation activity with the associated token.
     * Create Role Map
     */
    async createRoleMapEntebusAccountRolePost(requestParameters: CreateRoleMapEntebusAccountRolePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExecutiveRoleMapSchema> {
        const response = await this.createRoleMapEntebusAccountRolePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes an existing role maps.            Only executives with `update_ex_role` permission can perform this operation.         Validates the role map ID before deletion.            If the mapping exists, it is permanently removed from the system.            Logs the deletion activity using the executive\'s token and request metadata.
     * Delete Role Map
     */
    async deleteRoleMapEntebusAccountRoleDeleteRaw(requestParameters: DeleteRoleMapEntebusAccountRoleDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteRoleMapEntebusAccountRoleDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['id'] != null) {
            formParams.append('id', requestParameters['id'] as any);
        }


        let urlPath = `/entebus/account/role`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes an existing role maps.            Only executives with `update_ex_role` permission can perform this operation.         Validates the role map ID before deletion.            If the mapping exists, it is permanently removed from the system.            Logs the deletion activity using the executive\'s token and request metadata.
     * Delete Role Map
     */
    async deleteRoleMapEntebusAccountRoleDelete(requestParameters: DeleteRoleMapEntebusAccountRoleDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteRoleMapEntebusAccountRoleDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Fetches a list of all executive role maps.            Supports filtering by ID and metadata.        Supports filtering, sorting, and pagination.          Requires a valid executive token.
     * Fetch Role Map
     */
    async fetchRoleMapEntebusAccountRoleGetRaw(requestParameters: FetchRoleMapEntebusAccountRoleGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ExecutiveRoleMapSchema>>> {
        const queryParameters: any = {};

        if (requestParameters['roleId'] != null) {
            queryParameters['role_id'] = requestParameters['roleId'];
        }

        if (requestParameters['executiveId'] != null) {
            queryParameters['executive_id'] = requestParameters['executiveId'];
        }

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['idGe'] != null) {
            queryParameters['id_ge'] = requestParameters['idGe'];
        }

        if (requestParameters['idLe'] != null) {
            queryParameters['id_le'] = requestParameters['idLe'];
        }

        if (requestParameters['idList'] != null) {
            queryParameters['id_list'] = requestParameters['idList'];
        }

        if (requestParameters['updatedOnGe'] != null) {
            queryParameters['updated_on_ge'] = (requestParameters['updatedOnGe'] as any).toISOString();
        }

        if (requestParameters['updatedOnLe'] != null) {
            queryParameters['updated_on_le'] = (requestParameters['updatedOnLe'] as any).toISOString();
        }

        if (requestParameters['createdOnGe'] != null) {
            queryParameters['created_on_ge'] = (requestParameters['createdOnGe'] as any).toISOString();
        }

        if (requestParameters['createdOnLe'] != null) {
            queryParameters['created_on_le'] = (requestParameters['createdOnLe'] as any).toISOString();
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['order_by'] = requestParameters['orderBy'];
        }

        if (requestParameters['orderIn'] != null) {
            queryParameters['order_in'] = requestParameters['orderIn'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entebus/account/role`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ExecutiveRoleMapSchemaFromJSON));
    }

    /**
     * Fetches a list of all executive role maps.            Supports filtering by ID and metadata.        Supports filtering, sorting, and pagination.          Requires a valid executive token.
     * Fetch Role Map
     */
    async fetchRoleMapEntebusAccountRoleGet(requestParameters: FetchRoleMapEntebusAccountRoleGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ExecutiveRoleMapSchema>> {
        const response = await this.fetchRoleMapEntebusAccountRoleGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates an existing role maps.            Only executives with `update_ex_role` permission can perform this operation.         Support partial updates such as modifying the role_id.             Logs the role map updating activity with the associated token.
     * Update Role Map
     */
    async updateRoleMapEntebusAccountRolePatchRaw(requestParameters: UpdateRoleMapEntebusAccountRolePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExecutiveRoleMapSchema>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateRoleMapEntebusAccountRolePatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['id'] != null) {
            formParams.append('id', requestParameters['id'] as any);
        }

        if (requestParameters['roleId'] != null) {
            formParams.append('role_id', requestParameters['roleId'] as any);
        }


        let urlPath = `/entebus/account/role`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExecutiveRoleMapSchemaFromJSON(jsonValue));
    }

    /**
     * Updates an existing role maps.            Only executives with `update_ex_role` permission can perform this operation.         Support partial updates such as modifying the role_id.             Logs the role map updating activity with the associated token.
     * Update Role Map
     */
    async updateRoleMapEntebusAccountRolePatch(requestParameters: UpdateRoleMapEntebusAccountRolePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExecutiveRoleMapSchema> {
        const response = await this.updateRoleMapEntebusAccountRolePatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
