/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppApiServiceOrderBy,
  AppApiVendorRoleMapOrderIn,
  ErrorResponse,
  HTTPValidationError,
  ServiceSchema,
} from '../models/index';
import {
    AppApiServiceOrderByFromJSON,
    AppApiServiceOrderByToJSON,
    AppApiVendorRoleMapOrderInFromJSON,
    AppApiVendorRoleMapOrderInToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ServiceSchemaFromJSON,
    ServiceSchemaToJSON,
} from '../models/index';

export interface CreateScheduledTriggerCompanyScheduleTriggerPostRequest {
    scheduleId: number;
    startingAt: Date;
}

export interface FetchScheduledTriggerCompanyScheduleTriggerGetRequest {
    id?: number | null;
    orderBy?: AppApiServiceOrderBy;
    orderIn?: AppApiVendorRoleMapOrderIn;
    offset?: number;
    limit?: number;
    companyId?: number | null;
}

/**
 * 
 */
export class ScheduledTriggerApi extends runtime.BaseAPI {

    /**
     * Create a new service for a specified company.                Requires executive role with `create_service` permission.     The bus must be in ACTIVE status.      The company must be in VERIFIED status.         The route must have at least two landmarks associated with it.             The first landmark must have a distance_from_start of 0, and both arrival_delta and departure_delta must also be 0.          For all intermediate landmarks (between the first and the last), the departure_delta must be greater than the arrival_delta.         The last landmark must have equal values for arrival_delta and departure_delta.         The service name is derived from the names of the route start_time + the first and last landmarks + the bus registration number, not from user input.                  The ending_at is derived from the route last landmarks arrival_delta, not user input.          The service can be generated only for today and tomorrow.        The started_on will be set to current time when the operator start the duty, not user input.         The finished_on will be set to current time when the operators finish the service or when the statement is generated, not user input.        The service is created in the CREATED status by default.            The data is derived from the submitted schedule.         The last_triggered_on is set to current time when the service is created using this endpoint.            The next_trigger_on is set to the datetime when the service should be triggered next, considering the frequency, date, and starting time from the route     Log the service creation activity with the associated token.
     * Create Scheduled Trigger
     */
    async createScheduledTriggerCompanyScheduleTriggerPostRaw(requestParameters: CreateScheduledTriggerCompanyScheduleTriggerPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServiceSchema>> {
        if (requestParameters['scheduleId'] == null) {
            throw new runtime.RequiredError(
                'scheduleId',
                'Required parameter "scheduleId" was null or undefined when calling createScheduledTriggerCompanyScheduleTriggerPost().'
            );
        }

        if (requestParameters['startingAt'] == null) {
            throw new runtime.RequiredError(
                'startingAt',
                'Required parameter "startingAt" was null or undefined when calling createScheduledTriggerCompanyScheduleTriggerPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['scheduleId'] != null) {
            formParams.append('schedule_id', requestParameters['scheduleId'] as any);
        }

        if (requestParameters['startingAt'] != null) {
            formParams.append('starting_at', (requestParameters['startingAt'] as any).toISOString());
        }


        let urlPath = `/company/schedule/trigger`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServiceSchemaFromJSON(jsonValue));
    }

    /**
     * Create a new service for a specified company.                Requires executive role with `create_service` permission.     The bus must be in ACTIVE status.      The company must be in VERIFIED status.         The route must have at least two landmarks associated with it.             The first landmark must have a distance_from_start of 0, and both arrival_delta and departure_delta must also be 0.          For all intermediate landmarks (between the first and the last), the departure_delta must be greater than the arrival_delta.         The last landmark must have equal values for arrival_delta and departure_delta.         The service name is derived from the names of the route start_time + the first and last landmarks + the bus registration number, not from user input.                  The ending_at is derived from the route last landmarks arrival_delta, not user input.          The service can be generated only for today and tomorrow.        The started_on will be set to current time when the operator start the duty, not user input.         The finished_on will be set to current time when the operators finish the service or when the statement is generated, not user input.        The service is created in the CREATED status by default.            The data is derived from the submitted schedule.         The last_triggered_on is set to current time when the service is created using this endpoint.            The next_trigger_on is set to the datetime when the service should be triggered next, considering the frequency, date, and starting time from the route     Log the service creation activity with the associated token.
     * Create Scheduled Trigger
     */
    async createScheduledTriggerCompanyScheduleTriggerPost(requestParameters: CreateScheduledTriggerCompanyScheduleTriggerPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceSchema> {
        const response = await this.createScheduledTriggerCompanyScheduleTriggerPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Fetch the list of all services created by the trigger.            Only available to users with a valid executive token.            Supports filtering, sorting, and pagination.
     * Fetch Scheduled Trigger
     */
    async fetchScheduledTriggerCompanyScheduleTriggerGetRaw(requestParameters: FetchScheduledTriggerCompanyScheduleTriggerGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ServiceSchema>>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['order_by'] = requestParameters['orderBy'];
        }

        if (requestParameters['orderIn'] != null) {
            queryParameters['order_in'] = requestParameters['orderIn'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['companyId'] != null) {
            queryParameters['company_id'] = requestParameters['companyId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/company/schedule/trigger`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ServiceSchemaFromJSON));
    }

    /**
     * Fetch the list of all services created by the trigger.            Only available to users with a valid executive token.            Supports filtering, sorting, and pagination.
     * Fetch Scheduled Trigger
     */
    async fetchScheduledTriggerCompanyScheduleTriggerGet(requestParameters: FetchScheduledTriggerCompanyScheduleTriggerGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ServiceSchema>> {
        const response = await this.fetchScheduledTriggerCompanyScheduleTriggerGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
