/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppApiScheduleOrderBy,
  AppApiVendorRoleMapOrderIn,
  BodyCreateScheduleCompanySchedulePost,
  BodyUpdateScheduleCompanySchedulePatch,
  Day,
  ErrorResponse,
  HTTPValidationError,
  ScheduleSchema,
  TicketingMode,
  TriggeringMode,
} from '../models/index';
import {
    AppApiScheduleOrderByFromJSON,
    AppApiScheduleOrderByToJSON,
    AppApiVendorRoleMapOrderInFromJSON,
    AppApiVendorRoleMapOrderInToJSON,
    BodyCreateScheduleCompanySchedulePostFromJSON,
    BodyCreateScheduleCompanySchedulePostToJSON,
    BodyUpdateScheduleCompanySchedulePatchFromJSON,
    BodyUpdateScheduleCompanySchedulePatchToJSON,
    DayFromJSON,
    DayToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ScheduleSchemaFromJSON,
    ScheduleSchemaToJSON,
    TicketingModeFromJSON,
    TicketingModeToJSON,
    TriggeringModeFromJSON,
    TriggeringModeToJSON,
} from '../models/index';

export interface CreateScheduleCompanySchedulePostRequest {
    bodyCreateScheduleCompanySchedulePost: BodyCreateScheduleCompanySchedulePost;
}

export interface DeleteScheduleCompanyScheduleDeleteRequest {
    body: number;
}

export interface FetchScheduleCompanyScheduleGetRequest {
    name?: string | null;
    description?: string | null;
    routeId?: number | null;
    fareId?: number | null;
    busId?: number | null;
    frequency?: Array<Day> | null;
    ticketingMode?: TicketingMode | null;
    triggeringMode?: TriggeringMode | null;
    id?: number | null;
    idGe?: number | null;
    idLe?: number | null;
    idList?: Array<number> | null;
    nextTriggerOnGe?: Date | null;
    nextTriggerOnLe?: Date | null;
    lastTriggerOnGe?: Date | null;
    lastTriggerOnLe?: Date | null;
    triggerTillGe?: Date | null;
    triggerTillLe?: Date | null;
    updatedOnGe?: Date | null;
    updatedOnLe?: Date | null;
    createdOnGe?: Date | null;
    createdOnLe?: Date | null;
    orderBy?: AppApiScheduleOrderBy;
    orderIn?: AppApiVendorRoleMapOrderIn;
    offset?: number;
    limit?: number;
    companyId?: number | null;
}

export interface UpdateScheduleCompanySchedulePatchRequest {
    bodyUpdateScheduleCompanySchedulePatch: BodyUpdateScheduleCompanySchedulePatch;
}

/**
 * 
 */
export class ScheduleApi extends runtime.BaseAPI {

    /**
     * Create a new schedule for a specified company.                Requires executive role with `create_schedule` permission.           In this bus_id, route_id must be associated with the company.            If fare_id is in Local scope, it must be associated with the company.        Trigger till must be a future date, it indicates the ending datetime of the schedule.        Log the schedule creation activity with the associated token.
     * Create Schedule
     */
    async createScheduleCompanySchedulePostRaw(requestParameters: CreateScheduleCompanySchedulePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduleSchema>> {
        if (requestParameters['bodyCreateScheduleCompanySchedulePost'] == null) {
            throw new runtime.RequiredError(
                'bodyCreateScheduleCompanySchedulePost',
                'Required parameter "bodyCreateScheduleCompanySchedulePost" was null or undefined when calling createScheduleCompanySchedulePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/company/schedule`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BodyCreateScheduleCompanySchedulePostToJSON(requestParameters['bodyCreateScheduleCompanySchedulePost']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduleSchemaFromJSON(jsonValue));
    }

    /**
     * Create a new schedule for a specified company.                Requires executive role with `create_schedule` permission.           In this bus_id, route_id must be associated with the company.            If fare_id is in Local scope, it must be associated with the company.        Trigger till must be a future date, it indicates the ending datetime of the schedule.        Log the schedule creation activity with the associated token.
     * Create Schedule
     */
    async createScheduleCompanySchedulePost(requestParameters: CreateScheduleCompanySchedulePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduleSchema> {
        const response = await this.createScheduleCompanySchedulePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an existing schedule by ID.           Requires executive role with `delete_schedule` permission.           Deletes the schedule if it exists and logs the action.
     * Delete Schedule
     */
    async deleteScheduleCompanyScheduleDeleteRaw(requestParameters: DeleteScheduleCompanyScheduleDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling deleteScheduleCompanyScheduleDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/company/schedule`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an existing schedule by ID.           Requires executive role with `delete_schedule` permission.           Deletes the schedule if it exists and logs the action.
     * Delete Schedule
     */
    async deleteScheduleCompanyScheduleDelete(requestParameters: DeleteScheduleCompanyScheduleDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteScheduleCompanyScheduleDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Fetch a list of all schedules across companies.          Only available to users with a valid executive token.            Supports filtering, sorting, and pagination.
     * Fetch Schedule
     */
    async fetchScheduleCompanyScheduleGetRaw(requestParameters: FetchScheduleCompanyScheduleGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ScheduleSchema>>> {
        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['description'] != null) {
            queryParameters['description'] = requestParameters['description'];
        }

        if (requestParameters['routeId'] != null) {
            queryParameters['route_id'] = requestParameters['routeId'];
        }

        if (requestParameters['fareId'] != null) {
            queryParameters['fare_id'] = requestParameters['fareId'];
        }

        if (requestParameters['busId'] != null) {
            queryParameters['bus_id'] = requestParameters['busId'];
        }

        if (requestParameters['frequency'] != null) {
            queryParameters['frequency'] = requestParameters['frequency'];
        }

        if (requestParameters['ticketingMode'] != null) {
            queryParameters['ticketing_mode'] = requestParameters['ticketingMode'];
        }

        if (requestParameters['triggeringMode'] != null) {
            queryParameters['triggering_mode'] = requestParameters['triggeringMode'];
        }

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['idGe'] != null) {
            queryParameters['id_ge'] = requestParameters['idGe'];
        }

        if (requestParameters['idLe'] != null) {
            queryParameters['id_le'] = requestParameters['idLe'];
        }

        if (requestParameters['idList'] != null) {
            queryParameters['id_list'] = requestParameters['idList'];
        }

        if (requestParameters['nextTriggerOnGe'] != null) {
            queryParameters['next_trigger_on_ge'] = (requestParameters['nextTriggerOnGe'] as any).toISOString();
        }

        if (requestParameters['nextTriggerOnLe'] != null) {
            queryParameters['next_trigger_on_le'] = (requestParameters['nextTriggerOnLe'] as any).toISOString();
        }

        if (requestParameters['lastTriggerOnGe'] != null) {
            queryParameters['last_trigger_on_ge'] = (requestParameters['lastTriggerOnGe'] as any).toISOString();
        }

        if (requestParameters['lastTriggerOnLe'] != null) {
            queryParameters['last_trigger_on_le'] = (requestParameters['lastTriggerOnLe'] as any).toISOString();
        }

        if (requestParameters['triggerTillGe'] != null) {
            queryParameters['trigger_till_ge'] = (requestParameters['triggerTillGe'] as any).toISOString();
        }

        if (requestParameters['triggerTillLe'] != null) {
            queryParameters['trigger_till_le'] = (requestParameters['triggerTillLe'] as any).toISOString();
        }

        if (requestParameters['updatedOnGe'] != null) {
            queryParameters['updated_on_ge'] = (requestParameters['updatedOnGe'] as any).toISOString();
        }

        if (requestParameters['updatedOnLe'] != null) {
            queryParameters['updated_on_le'] = (requestParameters['updatedOnLe'] as any).toISOString();
        }

        if (requestParameters['createdOnGe'] != null) {
            queryParameters['created_on_ge'] = (requestParameters['createdOnGe'] as any).toISOString();
        }

        if (requestParameters['createdOnLe'] != null) {
            queryParameters['created_on_le'] = (requestParameters['createdOnLe'] as any).toISOString();
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['order_by'] = requestParameters['orderBy'];
        }

        if (requestParameters['orderIn'] != null) {
            queryParameters['order_in'] = requestParameters['orderIn'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['companyId'] != null) {
            queryParameters['company_id'] = requestParameters['companyId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/company/schedule`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ScheduleSchemaFromJSON));
    }

    /**
     * Fetch a list of all schedules across companies.          Only available to users with a valid executive token.            Supports filtering, sorting, and pagination.
     * Fetch Schedule
     */
    async fetchScheduleCompanyScheduleGet(requestParameters: FetchScheduleCompanyScheduleGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ScheduleSchema>> {
        const response = await this.fetchScheduleCompanyScheduleGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an existing schedule by ID.           Requires executive role with `update_schedule` permission.        In this bus_id, route_id must be associated with the company.            If fare_id is in Local scope, it must be associated with the company.         Trigger till must be a future date, it indicates the ending datetime of the schedule.        Log the schedule update activity with the associated token.
     * Update Schedule
     */
    async updateScheduleCompanySchedulePatchRaw(requestParameters: UpdateScheduleCompanySchedulePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduleSchema>> {
        if (requestParameters['bodyUpdateScheduleCompanySchedulePatch'] == null) {
            throw new runtime.RequiredError(
                'bodyUpdateScheduleCompanySchedulePatch',
                'Required parameter "bodyUpdateScheduleCompanySchedulePatch" was null or undefined when calling updateScheduleCompanySchedulePatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/company/schedule`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: BodyUpdateScheduleCompanySchedulePatchToJSON(requestParameters['bodyUpdateScheduleCompanySchedulePatch']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduleSchemaFromJSON(jsonValue));
    }

    /**
     * Update an existing schedule by ID.           Requires executive role with `update_schedule` permission.        In this bus_id, route_id must be associated with the company.            If fare_id is in Local scope, it must be associated with the company.         Trigger till must be a future date, it indicates the ending datetime of the schedule.        Log the schedule update activity with the associated token.
     * Update Schedule
     */
    async updateScheduleCompanySchedulePatch(requestParameters: UpdateScheduleCompanySchedulePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduleSchema> {
        const response = await this.updateScheduleCompanySchedulePatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
