/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  ExecutiveTokenSchema,
  GrantType,
  HTTPValidationError,
  PlatformType,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ExecutiveTokenSchemaFromJSON,
    ExecutiveTokenSchemaToJSON,
    GrantTypeFromJSON,
    GrantTypeToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    PlatformTypeFromJSON,
    PlatformTypeToJSON,
} from '../models/index';

export interface CreateTokenEntebusAccountTokenPostRequest {
    username: string;
    password: string;
    platformType?: PlatformType;
    clientDetails?: string | null;
    grantType?: GrantType;
}

export interface DeleteTokenEntebusAccountTokenDeleteRequest {
    id?: number | null;
}

export interface RefreshTokenEntebusAccountTokenRefreshPostRequest {
    refreshToken: string;
    grantType?: GrantType;
}

/**
 * 
 */
export class TokenApi extends runtime.BaseAPI {

    /**
     * **Issue a new access token for an executive after validating credentials.**  - Verify the `username` and `password`. - Ensure the executive account is in `active status` before allowing token creation. - Maintain a limit on the number of active tokens based on `MAX_EXECUTIVE_TOKENS` to control token rotation. - **Token Creation**     - Generate a new `Executive Token` with a pair of access and refresh tokens.     - The `expires_in` indicates the number of seconds until the access token expires (based on MAX_ACCESS_TOKEN_VALIDITY).     - The `refresh_before` indicates the datetime when the refresh token expires (based on MAX_REFRESH_TOKEN_VALIDITY).     - A new access token can be generated by using the refresh token before it expires.
     * Create Token
     */
    async createTokenEntebusAccountTokenPostRaw(requestParameters: CreateTokenEntebusAccountTokenPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExecutiveTokenSchema>> {
        if (requestParameters['username'] == null) {
            throw new runtime.RequiredError(
                'username',
                'Required parameter "username" was null or undefined when calling createTokenEntebusAccountTokenPost().'
            );
        }

        if (requestParameters['password'] == null) {
            throw new runtime.RequiredError(
                'password',
                'Required parameter "password" was null or undefined when calling createTokenEntebusAccountTokenPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['username'] != null) {
            formParams.append('username', requestParameters['username'] as any);
        }

        if (requestParameters['password'] != null) {
            formParams.append('password', requestParameters['password'] as any);
        }

        if (requestParameters['platformType'] != null) {
            formParams.append('platform_type', requestParameters['platformType'] as any);
        }

        if (requestParameters['clientDetails'] != null) {
            formParams.append('client_details', requestParameters['clientDetails'] as any);
        }

        if (requestParameters['grantType'] != null) {
            formParams.append('grant_type', requestParameters['grantType'] as any);
        }


        let urlPath = `/entebus/account/token`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExecutiveTokenSchemaFromJSON(jsonValue));
    }

    /**
     * **Issue a new access token for an executive after validating credentials.**  - Verify the `username` and `password`. - Ensure the executive account is in `active status` before allowing token creation. - Maintain a limit on the number of active tokens based on `MAX_EXECUTIVE_TOKENS` to control token rotation. - **Token Creation**     - Generate a new `Executive Token` with a pair of access and refresh tokens.     - The `expires_in` indicates the number of seconds until the access token expires (based on MAX_ACCESS_TOKEN_VALIDITY).     - The `refresh_before` indicates the datetime when the refresh token expires (based on MAX_REFRESH_TOKEN_VALIDITY).     - A new access token can be generated by using the refresh token before it expires.
     * Create Token
     */
    async createTokenEntebusAccountTokenPost(requestParameters: CreateTokenEntebusAccountTokenPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExecutiveTokenSchema> {
        const response = await this.createTokenEntebusAccountTokenPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Revoke an executive token.  - Verify the provided access token exists in the database. - Invalidate the current access token.
     * Delete Token
     */
    async deleteTokenEntebusAccountTokenDeleteRaw(requestParameters: DeleteTokenEntebusAccountTokenDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTP Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['id'] != null) {
            formParams.append('id', requestParameters['id'] as any);
        }


        let urlPath = `/entebus/account/token`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Revoke an executive token.  - Verify the provided access token exists in the database. - Invalidate the current access token.
     * Delete Token
     */
    async deleteTokenEntebusAccountTokenDelete(requestParameters: DeleteTokenEntebusAccountTokenDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTokenEntebusAccountTokenDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Fetch Token
     */
    async fetchTokenEntebusAccountTokenGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/entebus/account/token`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Fetch Token
     */
    async fetchTokenEntebusAccountTokenGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.fetchTokenEntebusAccountTokenGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * **Refresh an executive\'s access token using a valid refresh token.**  - Verify the provided refresh token exists in the database. - Invalidate the current refresh token. - **Token Creation**     - Generate a new `Executive Token` with a pair of access and refresh tokens.     - The `expires_in` indicates the number of seconds until the access token expires (based on MAX_ACCESS_TOKEN_VALIDITY).     - The `refresh_before` indicates the datetime when the refresh token expires (based on MAX_REFRESH_TOKEN_VALIDITY).     - A new access token can be generated by using the refresh token before it expires.
     * Refresh Token
     */
    async refreshTokenEntebusAccountTokenRefreshPostRaw(requestParameters: RefreshTokenEntebusAccountTokenRefreshPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExecutiveTokenSchema>> {
        if (requestParameters['refreshToken'] == null) {
            throw new runtime.RequiredError(
                'refreshToken',
                'Required parameter "refreshToken" was null or undefined when calling refreshTokenEntebusAccountTokenRefreshPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['refreshToken'] != null) {
            formParams.append('refresh_token', requestParameters['refreshToken'] as any);
        }

        if (requestParameters['grantType'] != null) {
            formParams.append('grant_type', requestParameters['grantType'] as any);
        }


        let urlPath = `/entebus/account/token/refresh`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExecutiveTokenSchemaFromJSON(jsonValue));
    }

    /**
     * **Refresh an executive\'s access token using a valid refresh token.**  - Verify the provided refresh token exists in the database. - Invalidate the current refresh token. - **Token Creation**     - Generate a new `Executive Token` with a pair of access and refresh tokens.     - The `expires_in` indicates the number of seconds until the access token expires (based on MAX_ACCESS_TOKEN_VALIDITY).     - The `refresh_before` indicates the datetime when the refresh token expires (based on MAX_REFRESH_TOKEN_VALIDITY).     - A new access token can be generated by using the refresh token before it expires.
     * Refresh Token
     */
    async refreshTokenEntebusAccountTokenRefreshPost(requestParameters: RefreshTokenEntebusAccountTokenRefreshPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExecutiveTokenSchema> {
        const response = await this.refreshTokenEntebusAccountTokenRefreshPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
