/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccountStatus,
  AppApiVendorAccountOrderBy,
  AppApiVendorRoleMapOrderIn,
  ErrorResponse,
  GenderType,
  HTTPValidationError,
  VendorSchema,
} from '../models/index';
import {
    AccountStatusFromJSON,
    AccountStatusToJSON,
    AppApiVendorAccountOrderByFromJSON,
    AppApiVendorAccountOrderByToJSON,
    AppApiVendorRoleMapOrderInFromJSON,
    AppApiVendorRoleMapOrderInToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    GenderTypeFromJSON,
    GenderTypeToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    VendorSchemaFromJSON,
    VendorSchemaToJSON,
} from '../models/index';

export interface CreateVendorBusinessAccountPostRequest {
    username: string;
    password: string;
    businessId: number;
    gender?: GenderType;
    fullName?: string | null;
    phoneNumber?: string | null;
    emailId?: string | null;
}

export interface DeleteVendorBusinessAccountDeleteRequest {
    id: number;
}

export interface FetchVendorBusinessAccountGetRequest {
    username?: string | null;
    gender?: GenderType | null;
    fullName?: string | null;
    status?: AccountStatus | null;
    phoneNumber?: string | null;
    emailId?: string | null;
    id?: number | null;
    idGe?: number | null;
    idLe?: number | null;
    idList?: Array<number> | null;
    updatedOnGe?: Date | null;
    updatedOnLe?: Date | null;
    createdOnGe?: Date | null;
    createdOnLe?: Date | null;
    orderBy?: AppApiVendorAccountOrderBy;
    orderIn?: AppApiVendorRoleMapOrderIn;
    offset?: number;
    limit?: number;
    businessId?: number | null;
}

export interface UpdateVendorBusinessAccountPatchRequest {
    id: number;
    password?: string | null;
    gender?: GenderType | null;
    fullName?: string | null;
    status?: AccountStatus | null;
    phoneNumber?: string | null;
    emailId?: string | null;
}

/**
 * 
 */
export class VendorAccountApi extends runtime.BaseAPI {

    /**
     * Creates a new vendor account with an active status.            Only executive with `create_vendor` permission can create vendor.            Logs the vendor account creation activity with the associated token.          Follow patterns for smooth creation of username and password.            The password is hashed using Argon2 before storing.
     * Create Vendor
     */
    async createVendorBusinessAccountPostRaw(requestParameters: CreateVendorBusinessAccountPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VendorSchema>> {
        if (requestParameters['username'] == null) {
            throw new runtime.RequiredError(
                'username',
                'Required parameter "username" was null or undefined when calling createVendorBusinessAccountPost().'
            );
        }

        if (requestParameters['password'] == null) {
            throw new runtime.RequiredError(
                'password',
                'Required parameter "password" was null or undefined when calling createVendorBusinessAccountPost().'
            );
        }

        if (requestParameters['businessId'] == null) {
            throw new runtime.RequiredError(
                'businessId',
                'Required parameter "businessId" was null or undefined when calling createVendorBusinessAccountPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['username'] != null) {
            formParams.append('username', requestParameters['username'] as any);
        }

        if (requestParameters['password'] != null) {
            formParams.append('password', requestParameters['password'] as any);
        }

        if (requestParameters['gender'] != null) {
            formParams.append('gender', requestParameters['gender'] as any);
        }

        if (requestParameters['fullName'] != null) {
            formParams.append('full_name', requestParameters['fullName'] as any);
        }

        if (requestParameters['phoneNumber'] != null) {
            formParams.append('phone_number', requestParameters['phoneNumber'] as any);
        }

        if (requestParameters['emailId'] != null) {
            formParams.append('email_id', requestParameters['emailId'] as any);
        }

        if (requestParameters['businessId'] != null) {
            formParams.append('business_id', requestParameters['businessId'] as any);
        }


        let urlPath = `/business/account`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VendorSchemaFromJSON(jsonValue));
    }

    /**
     * Creates a new vendor account with an active status.            Only executive with `create_vendor` permission can create vendor.            Logs the vendor account creation activity with the associated token.          Follow patterns for smooth creation of username and password.            The password is hashed using Argon2 before storing.
     * Create Vendor
     */
    async createVendorBusinessAccountPost(requestParameters: CreateVendorBusinessAccountPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VendorSchema> {
        const response = await this.createVendorBusinessAccountPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an existing vendor by ID.       Requires executive permissions with `delete_vendor` role.       Deletes the vendor and logs the deletion event.
     * Delete Vendor
     */
    async deleteVendorBusinessAccountDeleteRaw(requestParameters: DeleteVendorBusinessAccountDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteVendorBusinessAccountDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['id'] != null) {
            formParams.append('id', requestParameters['id'] as any);
        }


        let urlPath = `/business/account`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an existing vendor by ID.       Requires executive permissions with `delete_vendor` role.       Deletes the vendor and logs the deletion event.
     * Delete Vendor
     */
    async deleteVendorBusinessAccountDelete(requestParameters: DeleteVendorBusinessAccountDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteVendorBusinessAccountDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Fetch vendor accounts with filtering, sorting, and pagination.         Filter by business_id, username, gender, designation, contact details, status, and creation/update timestamps.        Filter by ID ranges or lists.         Sort by ID, creation date, or update date in ascending or descending order.          Paginate using offset and limit.         Returns a list of vendor accounts matching the criteria.           Requires a valid executive token.
     * Fetch Vendor
     */
    async fetchVendorBusinessAccountGetRaw(requestParameters: FetchVendorBusinessAccountGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<VendorSchema>>> {
        const queryParameters: any = {};

        if (requestParameters['username'] != null) {
            queryParameters['username'] = requestParameters['username'];
        }

        if (requestParameters['gender'] != null) {
            queryParameters['gender'] = requestParameters['gender'];
        }

        if (requestParameters['fullName'] != null) {
            queryParameters['full_name'] = requestParameters['fullName'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['phoneNumber'] != null) {
            queryParameters['phone_number'] = requestParameters['phoneNumber'];
        }

        if (requestParameters['emailId'] != null) {
            queryParameters['email_id'] = requestParameters['emailId'];
        }

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['idGe'] != null) {
            queryParameters['id_ge'] = requestParameters['idGe'];
        }

        if (requestParameters['idLe'] != null) {
            queryParameters['id_le'] = requestParameters['idLe'];
        }

        if (requestParameters['idList'] != null) {
            queryParameters['id_list'] = requestParameters['idList'];
        }

        if (requestParameters['updatedOnGe'] != null) {
            queryParameters['updated_on_ge'] = (requestParameters['updatedOnGe'] as any).toISOString();
        }

        if (requestParameters['updatedOnLe'] != null) {
            queryParameters['updated_on_le'] = (requestParameters['updatedOnLe'] as any).toISOString();
        }

        if (requestParameters['createdOnGe'] != null) {
            queryParameters['created_on_ge'] = (requestParameters['createdOnGe'] as any).toISOString();
        }

        if (requestParameters['createdOnLe'] != null) {
            queryParameters['created_on_le'] = (requestParameters['createdOnLe'] as any).toISOString();
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['order_by'] = requestParameters['orderBy'];
        }

        if (requestParameters['orderIn'] != null) {
            queryParameters['order_in'] = requestParameters['orderIn'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['businessId'] != null) {
            queryParameters['business_id'] = requestParameters['businessId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/business/account`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(VendorSchemaFromJSON));
    }

    /**
     * Fetch vendor accounts with filtering, sorting, and pagination.         Filter by business_id, username, gender, designation, contact details, status, and creation/update timestamps.        Filter by ID ranges or lists.         Sort by ID, creation date, or update date in ascending or descending order.          Paginate using offset and limit.         Returns a list of vendor accounts matching the criteria.           Requires a valid executive token.
     * Fetch Vendor
     */
    async fetchVendorBusinessAccountGet(requestParameters: FetchVendorBusinessAccountGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<VendorSchema>> {
        const response = await this.fetchVendorBusinessAccountGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates an existing vendor account.            Executive with `update_vendor` permission can update vendors account.          Follow patterns for smooth creation of password.             The password is hashed using Argon2 before storing.              If the status is set to`SUSPENDED, all tokens associated with that vendor are revoked.           Logs the vendor account update activity with the associated token.
     * Update Vendor
     */
    async updateVendorBusinessAccountPatchRaw(requestParameters: UpdateVendorBusinessAccountPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VendorSchema>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateVendorBusinessAccountPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['id'] != null) {
            formParams.append('id', requestParameters['id'] as any);
        }

        if (requestParameters['password'] != null) {
            formParams.append('password', requestParameters['password'] as any);
        }

        if (requestParameters['gender'] != null) {
            formParams.append('gender', requestParameters['gender'] as any);
        }

        if (requestParameters['fullName'] != null) {
            formParams.append('full_name', requestParameters['fullName'] as any);
        }

        if (requestParameters['status'] != null) {
            formParams.append('status', requestParameters['status'] as any);
        }

        if (requestParameters['phoneNumber'] != null) {
            formParams.append('phone_number', requestParameters['phoneNumber'] as any);
        }

        if (requestParameters['emailId'] != null) {
            formParams.append('email_id', requestParameters['emailId'] as any);
        }


        let urlPath = `/business/account`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VendorSchemaFromJSON(jsonValue));
    }

    /**
     * Updates an existing vendor account.            Executive with `update_vendor` permission can update vendors account.          Follow patterns for smooth creation of password.             The password is hashed using Argon2 before storing.              If the status is set to`SUSPENDED, all tokens associated with that vendor are revoked.           Logs the vendor account update activity with the associated token.
     * Update Vendor
     */
    async updateVendorBusinessAccountPatch(requestParameters: UpdateVendorBusinessAccountPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VendorSchema> {
        const response = await this.updateVendorBusinessAccountPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
