/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppApiVendorRoleMapOrderIn,
  AppApiVendorTokenOrderBy,
  ErrorResponse,
  HTTPValidationError,
  MaskedVendorTokenSchema,
  PlatformType,
} from '../models/index';
import {
    AppApiVendorRoleMapOrderInFromJSON,
    AppApiVendorRoleMapOrderInToJSON,
    AppApiVendorTokenOrderByFromJSON,
    AppApiVendorTokenOrderByToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MaskedVendorTokenSchemaFromJSON,
    MaskedVendorTokenSchemaToJSON,
    PlatformTypeFromJSON,
    PlatformTypeToJSON,
} from '../models/index';

export interface DeleteTokenBusinessAccountTokenDeleteRequest {
    id: number;
}

export interface FetchTokensBusinessAccountTokenGetRequest {
    vendorId?: number | null;
    platformType?: PlatformType | null;
    clientDetails?: string | null;
    id?: number | null;
    idGe?: number | null;
    idLe?: number | null;
    idList?: Array<number> | null;
    updatedOnGe?: Date | null;
    updatedOnLe?: Date | null;
    createdOnGe?: Date | null;
    createdOnLe?: Date | null;
    orderBy?: AppApiVendorTokenOrderBy;
    orderIn?: AppApiVendorRoleMapOrderIn;
    offset?: number;
    limit?: number;
    businessId?: number | null;
}

/**
 * 
 */
export class VendorTokenApi extends runtime.BaseAPI {

    /**
     * Revokes an access token associated with an vendor account.           This endpoint deletes an access token based on the vendor token ID.          The executive with `manage_ve_token` permission can delete any vendor\'s token.           If the token ID is invalid or already deleted, the operation is silently ignored.            Logs the token revocation event for audit tracking if the id is valid.
     * Delete Token
     */
    async deleteTokenBusinessAccountTokenDeleteRaw(requestParameters: DeleteTokenBusinessAccountTokenDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteTokenBusinessAccountTokenDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['id'] != null) {
            formParams.append('id', requestParameters['id'] as any);
        }


        let urlPath = `/business/account/token`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Revokes an access token associated with an vendor account.           This endpoint deletes an access token based on the vendor token ID.          The executive with `manage_ve_token` permission can delete any vendor\'s token.           If the token ID is invalid or already deleted, the operation is silently ignored.            Logs the token revocation event for audit tracking if the id is valid.
     * Delete Token
     */
    async deleteTokenBusinessAccountTokenDelete(requestParameters: DeleteTokenBusinessAccountTokenDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTokenBusinessAccountTokenDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Fetches a list of vendor tokens belonging to a business, filtered by optional query parameters.          Only executives with `manage_ve_token` permission can access this endpoint.          Supports filtering by token ID, vendor ID, platform type, client details, and creation timestamps.           Enables pagination using offset and limit.           Allows sorting using order_by and order_in.
     * Fetch Tokens
     */
    async fetchTokensBusinessAccountTokenGetRaw(requestParameters: FetchTokensBusinessAccountTokenGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MaskedVendorTokenSchema>>> {
        const queryParameters: any = {};

        if (requestParameters['vendorId'] != null) {
            queryParameters['vendor_id'] = requestParameters['vendorId'];
        }

        if (requestParameters['platformType'] != null) {
            queryParameters['platform_type'] = requestParameters['platformType'];
        }

        if (requestParameters['clientDetails'] != null) {
            queryParameters['client_details'] = requestParameters['clientDetails'];
        }

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['idGe'] != null) {
            queryParameters['id_ge'] = requestParameters['idGe'];
        }

        if (requestParameters['idLe'] != null) {
            queryParameters['id_le'] = requestParameters['idLe'];
        }

        if (requestParameters['idList'] != null) {
            queryParameters['id_list'] = requestParameters['idList'];
        }

        if (requestParameters['updatedOnGe'] != null) {
            queryParameters['updated_on_ge'] = (requestParameters['updatedOnGe'] as any).toISOString();
        }

        if (requestParameters['updatedOnLe'] != null) {
            queryParameters['updated_on_le'] = (requestParameters['updatedOnLe'] as any).toISOString();
        }

        if (requestParameters['createdOnGe'] != null) {
            queryParameters['created_on_ge'] = (requestParameters['createdOnGe'] as any).toISOString();
        }

        if (requestParameters['createdOnLe'] != null) {
            queryParameters['created_on_le'] = (requestParameters['createdOnLe'] as any).toISOString();
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['order_by'] = requestParameters['orderBy'];
        }

        if (requestParameters['orderIn'] != null) {
            queryParameters['order_in'] = requestParameters['orderIn'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['businessId'] != null) {
            queryParameters['business_id'] = requestParameters['businessId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Executive HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/business/account/token`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MaskedVendorTokenSchemaFromJSON));
    }

    /**
     * Fetches a list of vendor tokens belonging to a business, filtered by optional query parameters.          Only executives with `manage_ve_token` permission can access this endpoint.          Supports filtering by token ID, vendor ID, platform type, client details, and creation timestamps.           Enables pagination using offset and limit.           Allows sorting using order_by and order_in.
     * Fetch Tokens
     */
    async fetchTokensBusinessAccountTokenGet(requestParameters: FetchTokensBusinessAccountTokenGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MaskedVendorTokenSchema>> {
        const response = await this.fetchTokensBusinessAccountTokenGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
