/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Status of an account (executive, operator, vendor, etc.).
 * @export
 */
export const AccountStatus = {
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type AccountStatus = typeof AccountStatus[keyof typeof AccountStatus];


export function instanceOfAccountStatus(value: any): boolean {
    for (const key in AccountStatus) {
        if (Object.prototype.hasOwnProperty.call(AccountStatus, key)) {
            if (AccountStatus[key as keyof typeof AccountStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AccountStatusFromJSON(json: any): AccountStatus {
    return AccountStatusFromJSONTyped(json, false);
}

export function AccountStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountStatus {
    return json as AccountStatus;
}

export function AccountStatusToJSON(value?: AccountStatus | null): any {
    return value as any;
}

export function AccountStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): AccountStatus {
    return value as AccountStatus;
}

