/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AppApiOperatorTokenOrderBy = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type AppApiOperatorTokenOrderBy = typeof AppApiOperatorTokenOrderBy[keyof typeof AppApiOperatorTokenOrderBy];


export function instanceOfAppApiOperatorTokenOrderBy(value: any): boolean {
    for (const key in AppApiOperatorTokenOrderBy) {
        if (Object.prototype.hasOwnProperty.call(AppApiOperatorTokenOrderBy, key)) {
            if (AppApiOperatorTokenOrderBy[key as keyof typeof AppApiOperatorTokenOrderBy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppApiOperatorTokenOrderByFromJSON(json: any): AppApiOperatorTokenOrderBy {
    return AppApiOperatorTokenOrderByFromJSONTyped(json, false);
}

export function AppApiOperatorTokenOrderByFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppApiOperatorTokenOrderBy {
    return json as AppApiOperatorTokenOrderBy;
}

export function AppApiOperatorTokenOrderByToJSON(value?: AppApiOperatorTokenOrderBy | null): any {
    return value as any;
}

export function AppApiOperatorTokenOrderByToJSONTyped(value: any, ignoreDiscriminator: boolean): AppApiOperatorTokenOrderBy {
    return value as AppApiOperatorTokenOrderBy;
}

