/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AppApiBusinessOrderBy = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type AppApiBusinessOrderBy = typeof AppApiBusinessOrderBy[keyof typeof AppApiBusinessOrderBy];


export function instanceOfAppApiBusinessOrderBy(value: any): boolean {
    for (const key in AppApiBusinessOrderBy) {
        if (Object.prototype.hasOwnProperty.call(AppApiBusinessOrderBy, key)) {
            if (AppApiBusinessOrderBy[key as keyof typeof AppApiBusinessOrderBy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppApiBusinessOrderByFromJSON(json: any): AppApiBusinessOrderBy {
    return AppApiBusinessOrderByFromJSONTyped(json, false);
}

export function AppApiBusinessOrderByFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppApiBusinessOrderBy {
    return json as AppApiBusinessOrderBy;
}

export function AppApiBusinessOrderByToJSON(value?: AppApiBusinessOrderBy | null): any {
    return value as any;
}

export function AppApiBusinessOrderByToJSONTyped(value: any, ignoreDiscriminator: boolean): AppApiBusinessOrderBy {
    return value as AppApiBusinessOrderBy;
}

