/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AppApiBusOrderBy = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type AppApiBusOrderBy = typeof AppApiBusOrderBy[keyof typeof AppApiBusOrderBy];


export function instanceOfAppApiBusOrderBy(value: any): boolean {
    for (const key in AppApiBusOrderBy) {
        if (Object.prototype.hasOwnProperty.call(AppApiBusOrderBy, key)) {
            if (AppApiBusOrderBy[key as keyof typeof AppApiBusOrderBy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppApiBusOrderByFromJSON(json: any): AppApiBusOrderBy {
    return AppApiBusOrderByFromJSONTyped(json, false);
}

export function AppApiBusOrderByFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppApiBusOrderBy {
    return json as AppApiBusOrderBy;
}

export function AppApiBusOrderByToJSON(value?: AppApiBusOrderBy | null): any {
    return value as any;
}

export function AppApiBusOrderByToJSONTyped(value: any, ignoreDiscriminator: boolean): AppApiBusOrderBy {
    return value as AppApiBusOrderBy;
}

