/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AppApiCompanyOrderBy = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type AppApiCompanyOrderBy = typeof AppApiCompanyOrderBy[keyof typeof AppApiCompanyOrderBy];


export function instanceOfAppApiCompanyOrderBy(value: any): boolean {
    for (const key in AppApiCompanyOrderBy) {
        if (Object.prototype.hasOwnProperty.call(AppApiCompanyOrderBy, key)) {
            if (AppApiCompanyOrderBy[key as keyof typeof AppApiCompanyOrderBy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppApiCompanyOrderByFromJSON(json: any): AppApiCompanyOrderBy {
    return AppApiCompanyOrderByFromJSONTyped(json, false);
}

export function AppApiCompanyOrderByFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppApiCompanyOrderBy {
    return json as AppApiCompanyOrderBy;
}

export function AppApiCompanyOrderByToJSON(value?: AppApiCompanyOrderBy | null): any {
    return value as any;
}

export function AppApiCompanyOrderByToJSONTyped(value: any, ignoreDiscriminator: boolean): AppApiCompanyOrderBy {
    return value as AppApiCompanyOrderBy;
}

