/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AppApiOperatorRoleMapOrderBy = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type AppApiOperatorRoleMapOrderBy = typeof AppApiOperatorRoleMapOrderBy[keyof typeof AppApiOperatorRoleMapOrderBy];


export function instanceOfAppApiOperatorRoleMapOrderBy(value: any): boolean {
    for (const key in AppApiOperatorRoleMapOrderBy) {
        if (Object.prototype.hasOwnProperty.call(AppApiOperatorRoleMapOrderBy, key)) {
            if (AppApiOperatorRoleMapOrderBy[key as keyof typeof AppApiOperatorRoleMapOrderBy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppApiOperatorRoleMapOrderByFromJSON(json: any): AppApiOperatorRoleMapOrderBy {
    return AppApiOperatorRoleMapOrderByFromJSONTyped(json, false);
}

export function AppApiOperatorRoleMapOrderByFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppApiOperatorRoleMapOrderBy {
    return json as AppApiOperatorRoleMapOrderBy;
}

export function AppApiOperatorRoleMapOrderByToJSON(value?: AppApiOperatorRoleMapOrderBy | null): any {
    return value as any;
}

export function AppApiOperatorRoleMapOrderByToJSONTyped(value: any, ignoreDiscriminator: boolean): AppApiOperatorRoleMapOrderBy {
    return value as AppApiOperatorRoleMapOrderBy;
}

