/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AppApiFareOrderBy = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type AppApiFareOrderBy = typeof AppApiFareOrderBy[keyof typeof AppApiFareOrderBy];


export function instanceOfAppApiFareOrderBy(value: any): boolean {
    for (const key in AppApiFareOrderBy) {
        if (Object.prototype.hasOwnProperty.call(AppApiFareOrderBy, key)) {
            if (AppApiFareOrderBy[key as keyof typeof AppApiFareOrderBy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppApiFareOrderByFromJSON(json: any): AppApiFareOrderBy {
    return AppApiFareOrderByFromJSONTyped(json, false);
}

export function AppApiFareOrderByFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppApiFareOrderBy {
    return json as AppApiFareOrderBy;
}

export function AppApiFareOrderByToJSON(value?: AppApiFareOrderBy | null): any {
    return value as any;
}

export function AppApiFareOrderByToJSONTyped(value: any, ignoreDiscriminator: boolean): AppApiFareOrderBy {
    return value as AppApiFareOrderBy;
}

