/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AppApiServiceOrderBy = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6
} as const;
export type AppApiServiceOrderBy = typeof AppApiServiceOrderBy[keyof typeof AppApiServiceOrderBy];


export function instanceOfAppApiServiceOrderBy(value: any): boolean {
    for (const key in AppApiServiceOrderBy) {
        if (Object.prototype.hasOwnProperty.call(AppApiServiceOrderBy, key)) {
            if (AppApiServiceOrderBy[key as keyof typeof AppApiServiceOrderBy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppApiServiceOrderByFromJSON(json: any): AppApiServiceOrderBy {
    return AppApiServiceOrderByFromJSONTyped(json, false);
}

export function AppApiServiceOrderByFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppApiServiceOrderBy {
    return json as AppApiServiceOrderBy;
}

export function AppApiServiceOrderByToJSON(value?: AppApiServiceOrderBy | null): any {
    return value as any;
}

export function AppApiServiceOrderByToJSONTyped(value: any, ignoreDiscriminator: boolean): AppApiServiceOrderBy {
    return value as AppApiServiceOrderBy;
}

