/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AppApiVendorAccountOrderBy = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type AppApiVendorAccountOrderBy = typeof AppApiVendorAccountOrderBy[keyof typeof AppApiVendorAccountOrderBy];


export function instanceOfAppApiVendorAccountOrderBy(value: any): boolean {
    for (const key in AppApiVendorAccountOrderBy) {
        if (Object.prototype.hasOwnProperty.call(AppApiVendorAccountOrderBy, key)) {
            if (AppApiVendorAccountOrderBy[key as keyof typeof AppApiVendorAccountOrderBy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppApiVendorAccountOrderByFromJSON(json: any): AppApiVendorAccountOrderBy {
    return AppApiVendorAccountOrderByFromJSONTyped(json, false);
}

export function AppApiVendorAccountOrderByFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppApiVendorAccountOrderBy {
    return json as AppApiVendorAccountOrderBy;
}

export function AppApiVendorAccountOrderByToJSON(value?: AppApiVendorAccountOrderBy | null): any {
    return value as any;
}

export function AppApiVendorAccountOrderByToJSONTyped(value: any, ignoreDiscriminator: boolean): AppApiVendorAccountOrderBy {
    return value as AppApiVendorAccountOrderBy;
}

