/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AppApiVendorRoleOrderBy = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type AppApiVendorRoleOrderBy = typeof AppApiVendorRoleOrderBy[keyof typeof AppApiVendorRoleOrderBy];


export function instanceOfAppApiVendorRoleOrderBy(value: any): boolean {
    for (const key in AppApiVendorRoleOrderBy) {
        if (Object.prototype.hasOwnProperty.call(AppApiVendorRoleOrderBy, key)) {
            if (AppApiVendorRoleOrderBy[key as keyof typeof AppApiVendorRoleOrderBy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppApiVendorRoleOrderByFromJSON(json: any): AppApiVendorRoleOrderBy {
    return AppApiVendorRoleOrderByFromJSONTyped(json, false);
}

export function AppApiVendorRoleOrderByFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppApiVendorRoleOrderBy {
    return json as AppApiVendorRoleOrderBy;
}

export function AppApiVendorRoleOrderByToJSON(value?: AppApiVendorRoleOrderBy | null): any {
    return value as any;
}

export function AppApiVendorRoleOrderByToJSONTyped(value: any, ignoreDiscriminator: boolean): AppApiVendorRoleOrderBy {
    return value as AppApiVendorRoleOrderBy;
}

