/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AppApiExecutiveRoleMapOrderBy = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type AppApiExecutiveRoleMapOrderBy = typeof AppApiExecutiveRoleMapOrderBy[keyof typeof AppApiExecutiveRoleMapOrderBy];


export function instanceOfAppApiExecutiveRoleMapOrderBy(value: any): boolean {
    for (const key in AppApiExecutiveRoleMapOrderBy) {
        if (Object.prototype.hasOwnProperty.call(AppApiExecutiveRoleMapOrderBy, key)) {
            if (AppApiExecutiveRoleMapOrderBy[key as keyof typeof AppApiExecutiveRoleMapOrderBy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppApiExecutiveRoleMapOrderByFromJSON(json: any): AppApiExecutiveRoleMapOrderBy {
    return AppApiExecutiveRoleMapOrderByFromJSONTyped(json, false);
}

export function AppApiExecutiveRoleMapOrderByFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppApiExecutiveRoleMapOrderBy {
    return json as AppApiExecutiveRoleMapOrderBy;
}

export function AppApiExecutiveRoleMapOrderByToJSON(value?: AppApiExecutiveRoleMapOrderBy | null): any {
    return value as any;
}

export function AppApiExecutiveRoleMapOrderByToJSONTyped(value: any, ignoreDiscriminator: boolean): AppApiExecutiveRoleMapOrderBy {
    return value as AppApiExecutiveRoleMapOrderBy;
}

