/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AppApiExecutiveTokenOrderBy = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type AppApiExecutiveTokenOrderBy = typeof AppApiExecutiveTokenOrderBy[keyof typeof AppApiExecutiveTokenOrderBy];


export function instanceOfAppApiExecutiveTokenOrderBy(value: any): boolean {
    for (const key in AppApiExecutiveTokenOrderBy) {
        if (Object.prototype.hasOwnProperty.call(AppApiExecutiveTokenOrderBy, key)) {
            if (AppApiExecutiveTokenOrderBy[key as keyof typeof AppApiExecutiveTokenOrderBy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppApiExecutiveTokenOrderByFromJSON(json: any): AppApiExecutiveTokenOrderBy {
    return AppApiExecutiveTokenOrderByFromJSONTyped(json, false);
}

export function AppApiExecutiveTokenOrderByFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppApiExecutiveTokenOrderBy {
    return json as AppApiExecutiveTokenOrderBy;
}

export function AppApiExecutiveTokenOrderByToJSON(value?: AppApiExecutiveTokenOrderBy | null): any {
    return value as any;
}

export function AppApiExecutiveTokenOrderByToJSONTyped(value: any, ignoreDiscriminator: boolean): AppApiExecutiveTokenOrderBy {
    return value as AppApiExecutiveTokenOrderBy;
}

