/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AppApiRouteOrderBy = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type AppApiRouteOrderBy = typeof AppApiRouteOrderBy[keyof typeof AppApiRouteOrderBy];


export function instanceOfAppApiRouteOrderBy(value: any): boolean {
    for (const key in AppApiRouteOrderBy) {
        if (Object.prototype.hasOwnProperty.call(AppApiRouteOrderBy, key)) {
            if (AppApiRouteOrderBy[key as keyof typeof AppApiRouteOrderBy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppApiRouteOrderByFromJSON(json: any): AppApiRouteOrderBy {
    return AppApiRouteOrderByFromJSONTyped(json, false);
}

export function AppApiRouteOrderByFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppApiRouteOrderBy {
    return json as AppApiRouteOrderBy;
}

export function AppApiRouteOrderByToJSON(value?: AppApiRouteOrderBy | null): any {
    return value as any;
}

export function AppApiRouteOrderByToJSONTyped(value: any, ignoreDiscriminator: boolean): AppApiRouteOrderBy {
    return value as AppApiRouteOrderBy;
}

