/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AppApiVendorRoleMapOrderIn = {
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type AppApiVendorRoleMapOrderIn = typeof AppApiVendorRoleMapOrderIn[keyof typeof AppApiVendorRoleMapOrderIn];


export function instanceOfAppApiVendorRoleMapOrderIn(value: any): boolean {
    for (const key in AppApiVendorRoleMapOrderIn) {
        if (Object.prototype.hasOwnProperty.call(AppApiVendorRoleMapOrderIn, key)) {
            if (AppApiVendorRoleMapOrderIn[key as keyof typeof AppApiVendorRoleMapOrderIn] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppApiVendorRoleMapOrderInFromJSON(json: any): AppApiVendorRoleMapOrderIn {
    return AppApiVendorRoleMapOrderInFromJSONTyped(json, false);
}

export function AppApiVendorRoleMapOrderInFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppApiVendorRoleMapOrderIn {
    return json as AppApiVendorRoleMapOrderIn;
}

export function AppApiVendorRoleMapOrderInToJSON(value?: AppApiVendorRoleMapOrderIn | null): any {
    return value as any;
}

export function AppApiVendorRoleMapOrderInToJSONTyped(value: any, ignoreDiscriminator: boolean): AppApiVendorRoleMapOrderIn {
    return value as AppApiVendorRoleMapOrderIn;
}

