/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AppApiExecutivePictureOrderBy = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type AppApiExecutivePictureOrderBy = typeof AppApiExecutivePictureOrderBy[keyof typeof AppApiExecutivePictureOrderBy];


export function instanceOfAppApiExecutivePictureOrderBy(value: any): boolean {
    for (const key in AppApiExecutivePictureOrderBy) {
        if (Object.prototype.hasOwnProperty.call(AppApiExecutivePictureOrderBy, key)) {
            if (AppApiExecutivePictureOrderBy[key as keyof typeof AppApiExecutivePictureOrderBy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppApiExecutivePictureOrderByFromJSON(json: any): AppApiExecutivePictureOrderBy {
    return AppApiExecutivePictureOrderByFromJSONTyped(json, false);
}

export function AppApiExecutivePictureOrderByFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppApiExecutivePictureOrderBy {
    return json as AppApiExecutivePictureOrderBy;
}

export function AppApiExecutivePictureOrderByToJSON(value?: AppApiExecutivePictureOrderBy | null): any {
    return value as any;
}

export function AppApiExecutivePictureOrderByToJSONTyped(value: any, ignoreDiscriminator: boolean): AppApiExecutivePictureOrderBy {
    return value as AppApiExecutivePictureOrderBy;
}

