/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AppApiLandmarkOrderBy = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type AppApiLandmarkOrderBy = typeof AppApiLandmarkOrderBy[keyof typeof AppApiLandmarkOrderBy];


export function instanceOfAppApiLandmarkOrderBy(value: any): boolean {
    for (const key in AppApiLandmarkOrderBy) {
        if (Object.prototype.hasOwnProperty.call(AppApiLandmarkOrderBy, key)) {
            if (AppApiLandmarkOrderBy[key as keyof typeof AppApiLandmarkOrderBy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppApiLandmarkOrderByFromJSON(json: any): AppApiLandmarkOrderBy {
    return AppApiLandmarkOrderByFromJSONTyped(json, false);
}

export function AppApiLandmarkOrderByFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppApiLandmarkOrderBy {
    return json as AppApiLandmarkOrderBy;
}

export function AppApiLandmarkOrderByToJSON(value?: AppApiLandmarkOrderBy | null): any {
    return value as any;
}

export function AppApiLandmarkOrderByToJSONTyped(value: any, ignoreDiscriminator: boolean): AppApiLandmarkOrderBy {
    return value as AppApiLandmarkOrderBy;
}

