/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AppApiOperatorAccountOrderBy = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type AppApiOperatorAccountOrderBy = typeof AppApiOperatorAccountOrderBy[keyof typeof AppApiOperatorAccountOrderBy];


export function instanceOfAppApiOperatorAccountOrderBy(value: any): boolean {
    for (const key in AppApiOperatorAccountOrderBy) {
        if (Object.prototype.hasOwnProperty.call(AppApiOperatorAccountOrderBy, key)) {
            if (AppApiOperatorAccountOrderBy[key as keyof typeof AppApiOperatorAccountOrderBy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppApiOperatorAccountOrderByFromJSON(json: any): AppApiOperatorAccountOrderBy {
    return AppApiOperatorAccountOrderByFromJSONTyped(json, false);
}

export function AppApiOperatorAccountOrderByFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppApiOperatorAccountOrderBy {
    return json as AppApiOperatorAccountOrderBy;
}

export function AppApiOperatorAccountOrderByToJSON(value?: AppApiOperatorAccountOrderBy | null): any {
    return value as any;
}

export function AppApiOperatorAccountOrderByToJSONTyped(value: any, ignoreDiscriminator: boolean): AppApiOperatorAccountOrderBy {
    return value as AppApiOperatorAccountOrderBy;
}

