/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AppApiScheduleOrderBy = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6,
    NUMBER_7: 7
} as const;
export type AppApiScheduleOrderBy = typeof AppApiScheduleOrderBy[keyof typeof AppApiScheduleOrderBy];


export function instanceOfAppApiScheduleOrderBy(value: any): boolean {
    for (const key in AppApiScheduleOrderBy) {
        if (Object.prototype.hasOwnProperty.call(AppApiScheduleOrderBy, key)) {
            if (AppApiScheduleOrderBy[key as keyof typeof AppApiScheduleOrderBy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppApiScheduleOrderByFromJSON(json: any): AppApiScheduleOrderBy {
    return AppApiScheduleOrderByFromJSONTyped(json, false);
}

export function AppApiScheduleOrderByFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppApiScheduleOrderBy {
    return json as AppApiScheduleOrderBy;
}

export function AppApiScheduleOrderByToJSON(value?: AppApiScheduleOrderBy | null): any {
    return value as any;
}

export function AppApiScheduleOrderByToJSONTyped(value: any, ignoreDiscriminator: boolean): AppApiScheduleOrderBy {
    return value as AppApiScheduleOrderBy;
}

