/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AppApiVendorTokenOrderBy = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type AppApiVendorTokenOrderBy = typeof AppApiVendorTokenOrderBy[keyof typeof AppApiVendorTokenOrderBy];


export function instanceOfAppApiVendorTokenOrderBy(value: any): boolean {
    for (const key in AppApiVendorTokenOrderBy) {
        if (Object.prototype.hasOwnProperty.call(AppApiVendorTokenOrderBy, key)) {
            if (AppApiVendorTokenOrderBy[key as keyof typeof AppApiVendorTokenOrderBy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppApiVendorTokenOrderByFromJSON(json: any): AppApiVendorTokenOrderBy {
    return AppApiVendorTokenOrderByFromJSONTyped(json, false);
}

export function AppApiVendorTokenOrderByFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppApiVendorTokenOrderBy {
    return json as AppApiVendorTokenOrderBy;
}

export function AppApiVendorTokenOrderByToJSON(value?: AppApiVendorTokenOrderBy | null): any {
    return value as any;
}

export function AppApiVendorTokenOrderByToJSONTyped(value: any, ignoreDiscriminator: boolean): AppApiVendorTokenOrderBy {
    return value as AppApiVendorTokenOrderBy;
}

