/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AppApiDutyOrderBy = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5
} as const;
export type AppApiDutyOrderBy = typeof AppApiDutyOrderBy[keyof typeof AppApiDutyOrderBy];


export function instanceOfAppApiDutyOrderBy(value: any): boolean {
    for (const key in AppApiDutyOrderBy) {
        if (Object.prototype.hasOwnProperty.call(AppApiDutyOrderBy, key)) {
            if (AppApiDutyOrderBy[key as keyof typeof AppApiDutyOrderBy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppApiDutyOrderByFromJSON(json: any): AppApiDutyOrderBy {
    return AppApiDutyOrderByFromJSONTyped(json, false);
}

export function AppApiDutyOrderByFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppApiDutyOrderBy {
    return json as AppApiDutyOrderBy;
}

export function AppApiDutyOrderByToJSON(value?: AppApiDutyOrderBy | null): any {
    return value as any;
}

export function AppApiDutyOrderByToJSONTyped(value: any, ignoreDiscriminator: boolean): AppApiDutyOrderBy {
    return value as AppApiDutyOrderBy;
}

