/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AppApiOperatorRoleOrderBy = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type AppApiOperatorRoleOrderBy = typeof AppApiOperatorRoleOrderBy[keyof typeof AppApiOperatorRoleOrderBy];


export function instanceOfAppApiOperatorRoleOrderBy(value: any): boolean {
    for (const key in AppApiOperatorRoleOrderBy) {
        if (Object.prototype.hasOwnProperty.call(AppApiOperatorRoleOrderBy, key)) {
            if (AppApiOperatorRoleOrderBy[key as keyof typeof AppApiOperatorRoleOrderBy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppApiOperatorRoleOrderByFromJSON(json: any): AppApiOperatorRoleOrderBy {
    return AppApiOperatorRoleOrderByFromJSONTyped(json, false);
}

export function AppApiOperatorRoleOrderByFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppApiOperatorRoleOrderBy {
    return json as AppApiOperatorRoleOrderBy;
}

export function AppApiOperatorRoleOrderByToJSON(value?: AppApiOperatorRoleOrderBy | null): any {
    return value as any;
}

export function AppApiOperatorRoleOrderByToJSONTyped(value: any, ignoreDiscriminator: boolean): AppApiOperatorRoleOrderBy {
    return value as AppApiOperatorRoleOrderBy;
}

