/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FareAttributes } from './FareAttributes';
import {
    FareAttributesFromJSON,
    FareAttributesFromJSONTyped,
    FareAttributesToJSON,
    FareAttributesToJSONTyped,
} from './FareAttributes';

/**
 * 
 * @export
 * @interface BodyUpdateFareCompanyFarePatch
 */
export interface BodyUpdateFareCompanyFarePatch {
    /**
     * 
     * @type {number}
     * @memberof BodyUpdateFareCompanyFarePatch
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof BodyUpdateFareCompanyFarePatch
     */
    name?: string | null;
    /**
     * 
     * @type {FareAttributes}
     * @memberof BodyUpdateFareCompanyFarePatch
     */
    attributes?: FareAttributes | null;
    /**
     * 
     * @type {string}
     * @memberof BodyUpdateFareCompanyFarePatch
     */
    _function?: string | null;
}

/**
 * Check if a given object implements the BodyUpdateFareCompanyFarePatch interface.
 */
export function instanceOfBodyUpdateFareCompanyFarePatch(value: object): value is BodyUpdateFareCompanyFarePatch {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function BodyUpdateFareCompanyFarePatchFromJSON(json: any): BodyUpdateFareCompanyFarePatch {
    return BodyUpdateFareCompanyFarePatchFromJSONTyped(json, false);
}

export function BodyUpdateFareCompanyFarePatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyUpdateFareCompanyFarePatch {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'attributes': json['attributes'] == null ? undefined : FareAttributesFromJSON(json['attributes']),
        '_function': json['function'] == null ? undefined : json['function'],
    };
}

export function BodyUpdateFareCompanyFarePatchToJSON(json: any): BodyUpdateFareCompanyFarePatch {
    return BodyUpdateFareCompanyFarePatchToJSONTyped(json, false);
}

export function BodyUpdateFareCompanyFarePatchToJSONTyped(value?: BodyUpdateFareCompanyFarePatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'attributes': FareAttributesToJSON(value['attributes']),
        'function': value['_function'],
    };
}

