/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TicketingMode } from './TicketingMode';
import {
    TicketingModeFromJSON,
    TicketingModeFromJSONTyped,
    TicketingModeToJSON,
    TicketingModeToJSONTyped,
} from './TicketingMode';
import type { TriggeringMode } from './TriggeringMode';
import {
    TriggeringModeFromJSON,
    TriggeringModeFromJSONTyped,
    TriggeringModeToJSON,
    TriggeringModeToJSONTyped,
} from './TriggeringMode';
import type { Day } from './Day';
import {
    DayFromJSON,
    DayFromJSONTyped,
    DayToJSON,
    DayToJSONTyped,
} from './Day';

/**
 * 
 * @export
 * @interface BodyCreateScheduleCompanySchedulePost
 */
export interface BodyCreateScheduleCompanySchedulePost {
    /**
     * 
     * @type {string}
     * @memberof BodyCreateScheduleCompanySchedulePost
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof BodyCreateScheduleCompanySchedulePost
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BodyCreateScheduleCompanySchedulePost
     */
    routeId: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCreateScheduleCompanySchedulePost
     */
    fareId: number;
    /**
     * 
     * @type {number}
     * @memberof BodyCreateScheduleCompanySchedulePost
     */
    busId: number;
    /**
     * 
     * @type {Array<Day>}
     * @memberof BodyCreateScheduleCompanySchedulePost
     */
    frequency?: Array<Day> | null;
    /**
     * HYBRID: 1, DIGITAL: 2, CONVENTIONAL: 3
     * @type {TicketingMode}
     * @memberof BodyCreateScheduleCompanySchedulePost
     */
    ticketingMode?: TicketingMode;
    /**
     * DISABLED: 1, AUTO: 2, MANUAL: 3
     * @type {TriggeringMode}
     * @memberof BodyCreateScheduleCompanySchedulePost
     */
    triggeringMode?: TriggeringMode;
    /**
     * 
     * @type {Date}
     * @memberof BodyCreateScheduleCompanySchedulePost
     */
    triggerTill?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof BodyCreateScheduleCompanySchedulePost
     */
    nextTriggerOn?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof BodyCreateScheduleCompanySchedulePost
     */
    companyId: number;
}



/**
 * Check if a given object implements the BodyCreateScheduleCompanySchedulePost interface.
 */
export function instanceOfBodyCreateScheduleCompanySchedulePost(value: object): value is BodyCreateScheduleCompanySchedulePost {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('routeId' in value) || value['routeId'] === undefined) return false;
    if (!('fareId' in value) || value['fareId'] === undefined) return false;
    if (!('busId' in value) || value['busId'] === undefined) return false;
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    return true;
}

export function BodyCreateScheduleCompanySchedulePostFromJSON(json: any): BodyCreateScheduleCompanySchedulePost {
    return BodyCreateScheduleCompanySchedulePostFromJSONTyped(json, false);
}

export function BodyCreateScheduleCompanySchedulePostFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyCreateScheduleCompanySchedulePost {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'routeId': json['route_id'],
        'fareId': json['fare_id'],
        'busId': json['bus_id'],
        'frequency': json['frequency'] == null ? undefined : ((json['frequency'] as Array<any>).map(DayFromJSON)),
        'ticketingMode': json['ticketing_mode'] == null ? undefined : TicketingModeFromJSON(json['ticketing_mode']),
        'triggeringMode': json['triggering_mode'] == null ? undefined : TriggeringModeFromJSON(json['triggering_mode']),
        'triggerTill': json['trigger_till'] == null ? undefined : (new Date(json['trigger_till'])),
        'nextTriggerOn': json['next_trigger_on'] == null ? undefined : (new Date(json['next_trigger_on'])),
        'companyId': json['company_id'],
    };
}

export function BodyCreateScheduleCompanySchedulePostToJSON(json: any): BodyCreateScheduleCompanySchedulePost {
    return BodyCreateScheduleCompanySchedulePostToJSONTyped(json, false);
}

export function BodyCreateScheduleCompanySchedulePostToJSONTyped(value?: BodyCreateScheduleCompanySchedulePost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'route_id': value['routeId'],
        'fare_id': value['fareId'],
        'bus_id': value['busId'],
        'frequency': value['frequency'] == null ? undefined : ((value['frequency'] as Array<any>).map(DayToJSON)),
        'ticketing_mode': TicketingModeToJSON(value['ticketingMode']),
        'triggering_mode': TriggeringModeToJSON(value['triggeringMode']),
        'trigger_till': value['triggerTill'] == null ? value['triggerTill'] : value['triggerTill'].toISOString(),
        'next_trigger_on': value['nextTriggerOn'] == null ? value['nextTriggerOn'] : value['nextTriggerOn'].toISOString(),
        'company_id': value['companyId'],
    };
}

