/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FareAttributes } from './FareAttributes';
import {
    FareAttributesFromJSON,
    FareAttributesFromJSONTyped,
    FareAttributesToJSON,
    FareAttributesToJSONTyped,
} from './FareAttributes';
import type { FareScope } from './FareScope';
import {
    FareScopeFromJSON,
    FareScopeFromJSONTyped,
    FareScopeToJSON,
    FareScopeToJSONTyped,
} from './FareScope';

/**
 * 
 * @export
 * @interface BodyCreateFareCompanyFarePost
 */
export interface BodyCreateFareCompanyFarePost {
    /**
     * 
     * @type {string}
     * @memberof BodyCreateFareCompanyFarePost
     */
    name: string;
    /**
     * 
     * @type {FareAttributes}
     * @memberof BodyCreateFareCompanyFarePost
     */
    attributes: FareAttributes;
    /**
     * 
     * @type {string}
     * @memberof BodyCreateFareCompanyFarePost
     */
    _function: string;
    /**
     * 
     * @type {number}
     * @memberof BodyCreateFareCompanyFarePost
     */
    companyId?: number | null;
    /**
     * GLOBAL: 1, LOCAL: 2
     * @type {FareScope}
     * @memberof BodyCreateFareCompanyFarePost
     */
    scope?: FareScope;
}



/**
 * Check if a given object implements the BodyCreateFareCompanyFarePost interface.
 */
export function instanceOfBodyCreateFareCompanyFarePost(value: object): value is BodyCreateFareCompanyFarePost {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    if (!('_function' in value) || value['_function'] === undefined) return false;
    return true;
}

export function BodyCreateFareCompanyFarePostFromJSON(json: any): BodyCreateFareCompanyFarePost {
    return BodyCreateFareCompanyFarePostFromJSONTyped(json, false);
}

export function BodyCreateFareCompanyFarePostFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyCreateFareCompanyFarePost {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'attributes': FareAttributesFromJSON(json['attributes']),
        '_function': json['function'],
        'companyId': json['company_id'] == null ? undefined : json['company_id'],
        'scope': json['scope'] == null ? undefined : FareScopeFromJSON(json['scope']),
    };
}

export function BodyCreateFareCompanyFarePostToJSON(json: any): BodyCreateFareCompanyFarePost {
    return BodyCreateFareCompanyFarePostToJSONTyped(json, false);
}

export function BodyCreateFareCompanyFarePostToJSONTyped(value?: BodyCreateFareCompanyFarePost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'attributes': FareAttributesToJSON(value['attributes']),
        'function': value['_function'],
        'company_id': value['companyId'],
        'scope': FareScopeToJSON(value['scope']),
    };
}

