/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of registered business entity.
 * @export
 */
export const BusinessType = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type BusinessType = typeof BusinessType[keyof typeof BusinessType];


export function instanceOfBusinessType(value: any): boolean {
    for (const key in BusinessType) {
        if (Object.prototype.hasOwnProperty.call(BusinessType, key)) {
            if (BusinessType[key as keyof typeof BusinessType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BusinessTypeFromJSON(json: any): BusinessType {
    return BusinessTypeFromJSONTyped(json, false);
}

export function BusinessTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessType {
    return json as BusinessType;
}

export function BusinessTypeToJSON(value?: BusinessType | null): any {
    return value as any;
}

export function BusinessTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): BusinessType {
    return value as BusinessType;
}

