/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Status of a registered business.
 * @export
 */
export const BusinessStatus = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type BusinessStatus = typeof BusinessStatus[keyof typeof BusinessStatus];


export function instanceOfBusinessStatus(value: any): boolean {
    for (const key in BusinessStatus) {
        if (Object.prototype.hasOwnProperty.call(BusinessStatus, key)) {
            if (BusinessStatus[key as keyof typeof BusinessStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BusinessStatusFromJSON(json: any): BusinessStatus {
    return BusinessStatusFromJSONTyped(json, false);
}

export function BusinessStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessStatus {
    return json as BusinessStatus;
}

export function BusinessStatusToJSON(value?: BusinessStatus | null): any {
    return value as any;
}

export function BusinessStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): BusinessStatus {
    return value as BusinessStatus;
}

