/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BusinessSchema
 */
export interface BusinessSchema {
    /**
     * 
     * @type {number}
     * @memberof BusinessSchema
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof BusinessSchema
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof BusinessSchema
     */
    type: number;
    /**
     * 
     * @type {Date}
     * @memberof BusinessSchema
     */
    updatedOn: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof BusinessSchema
     */
    createdOn: Date;
    /**
     * 
     * @type {number}
     * @memberof BusinessSchema
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof BusinessSchema
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessSchema
     */
    contactPerson: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessSchema
     */
    phoneNumber: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessSchema
     */
    emailId: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessSchema
     */
    location: string;
}

/**
 * Check if a given object implements the BusinessSchema interface.
 */
export function instanceOfBusinessSchema(value: object): value is BusinessSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('updatedOn' in value) || value['updatedOn'] === undefined) return false;
    if (!('createdOn' in value) || value['createdOn'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('contactPerson' in value) || value['contactPerson'] === undefined) return false;
    if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
    if (!('emailId' in value) || value['emailId'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    return true;
}

export function BusinessSchemaFromJSON(json: any): BusinessSchema {
    return BusinessSchemaFromJSONTyped(json, false);
}

export function BusinessSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'type': json['type'],
        'updatedOn': (json['updated_on'] == null ? null : new Date(json['updated_on'])),
        'createdOn': (new Date(json['created_on'])),
        'status': json['status'],
        'address': json['address'],
        'contactPerson': json['contact_person'],
        'phoneNumber': json['phone_number'],
        'emailId': json['email_id'],
        'location': json['location'],
    };
}

export function BusinessSchemaToJSON(json: any): BusinessSchema {
    return BusinessSchemaToJSONTyped(json, false);
}

export function BusinessSchemaToJSONTyped(value?: BusinessSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'type': value['type'],
        'updated_on': value['updatedOn'] == null ? value['updatedOn'] : value['updatedOn'].toISOString(),
        'created_on': value['createdOn'].toISOString(),
        'status': value['status'],
        'address': value['address'],
        'contact_person': value['contactPerson'],
        'phone_number': value['phoneNumber'],
        'email_id': value['emailId'],
        'location': value['location'],
    };
}

