/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BusSchema
 */
export interface BusSchema {
    /**
     * 
     * @type {number}
     * @memberof BusSchema
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof BusSchema
     */
    companyId: number;
    /**
     * 
     * @type {string}
     * @memberof BusSchema
     */
    registrationNumber: string;
    /**
     * 
     * @type {string}
     * @memberof BusSchema
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof BusSchema
     */
    capacity: number;
    /**
     * 
     * @type {Date}
     * @memberof BusSchema
     */
    updatedOn: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof BusSchema
     */
    createdOn: Date;
    /**
     * 
     * @type {Date}
     * @memberof BusSchema
     */
    manufacturedOn: Date;
    /**
     * 
     * @type {Date}
     * @memberof BusSchema
     */
    insuranceUpto: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof BusSchema
     */
    pollutionUpto: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof BusSchema
     */
    fitnessUpto: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof BusSchema
     */
    roadTaxUpto: Date | null;
    /**
     * 
     * @type {number}
     * @memberof BusSchema
     */
    status: number;
}

/**
 * Check if a given object implements the BusSchema interface.
 */
export function instanceOfBusSchema(value: object): value is BusSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    if (!('registrationNumber' in value) || value['registrationNumber'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('capacity' in value) || value['capacity'] === undefined) return false;
    if (!('updatedOn' in value) || value['updatedOn'] === undefined) return false;
    if (!('createdOn' in value) || value['createdOn'] === undefined) return false;
    if (!('manufacturedOn' in value) || value['manufacturedOn'] === undefined) return false;
    if (!('insuranceUpto' in value) || value['insuranceUpto'] === undefined) return false;
    if (!('pollutionUpto' in value) || value['pollutionUpto'] === undefined) return false;
    if (!('fitnessUpto' in value) || value['fitnessUpto'] === undefined) return false;
    if (!('roadTaxUpto' in value) || value['roadTaxUpto'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function BusSchemaFromJSON(json: any): BusSchema {
    return BusSchemaFromJSONTyped(json, false);
}

export function BusSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'companyId': json['company_id'],
        'registrationNumber': json['registration_number'],
        'name': json['name'],
        'capacity': json['capacity'],
        'updatedOn': (json['updated_on'] == null ? null : new Date(json['updated_on'])),
        'createdOn': (new Date(json['created_on'])),
        'manufacturedOn': (new Date(json['manufactured_on'])),
        'insuranceUpto': (json['insurance_upto'] == null ? null : new Date(json['insurance_upto'])),
        'pollutionUpto': (json['pollution_upto'] == null ? null : new Date(json['pollution_upto'])),
        'fitnessUpto': (json['fitness_upto'] == null ? null : new Date(json['fitness_upto'])),
        'roadTaxUpto': (json['road_tax_upto'] == null ? null : new Date(json['road_tax_upto'])),
        'status': json['status'],
    };
}

export function BusSchemaToJSON(json: any): BusSchema {
    return BusSchemaToJSONTyped(json, false);
}

export function BusSchemaToJSONTyped(value?: BusSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'company_id': value['companyId'],
        'registration_number': value['registrationNumber'],
        'name': value['name'],
        'capacity': value['capacity'],
        'updated_on': value['updatedOn'] == null ? value['updatedOn'] : value['updatedOn'].toISOString(),
        'created_on': value['createdOn'].toISOString(),
        'manufactured_on': value['manufacturedOn'].toISOString(),
        'insurance_upto': value['insuranceUpto'] == null ? value['insuranceUpto'] : value['insuranceUpto'].toISOString(),
        'pollution_upto': value['pollutionUpto'] == null ? value['pollutionUpto'] : value['pollutionUpto'].toISOString(),
        'fitness_upto': value['fitnessUpto'] == null ? value['fitnessUpto'] : value['fitnessUpto'].toISOString(),
        'road_tax_upto': value['roadTaxUpto'] == null ? value['roadTaxUpto'] : value['roadTaxUpto'].toISOString(),
        'status': value['status'],
    };
}

