/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BusStopSchema
 */
export interface BusStopSchema {
    /**
     * 
     * @type {number}
     * @memberof BusStopSchema
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof BusStopSchema
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof BusStopSchema
     */
    landmarkId: number;
    /**
     * 
     * @type {string}
     * @memberof BusStopSchema
     */
    location: string;
    /**
     * 
     * @type {Date}
     * @memberof BusStopSchema
     */
    updatedOn: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof BusStopSchema
     */
    createdOn: Date;
}

/**
 * Check if a given object implements the BusStopSchema interface.
 */
export function instanceOfBusStopSchema(value: object): value is BusStopSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('landmarkId' in value) || value['landmarkId'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('updatedOn' in value) || value['updatedOn'] === undefined) return false;
    if (!('createdOn' in value) || value['createdOn'] === undefined) return false;
    return true;
}

export function BusStopSchemaFromJSON(json: any): BusStopSchema {
    return BusStopSchemaFromJSONTyped(json, false);
}

export function BusStopSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusStopSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'landmarkId': json['landmark_id'],
        'location': json['location'],
        'updatedOn': (json['updated_on'] == null ? null : new Date(json['updated_on'])),
        'createdOn': (new Date(json['created_on'])),
    };
}

export function BusStopSchemaToJSON(json: any): BusStopSchema {
    return BusStopSchemaToJSONTyped(json, false);
}

export function BusStopSchemaToJSONTyped(value?: BusStopSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'landmark_id': value['landmarkId'],
        'location': value['location'],
        'updated_on': value['updatedOn'] == null ? value['updatedOn'] : value['updatedOn'].toISOString(),
        'created_on': value['createdOn'].toISOString(),
    };
}

