/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Classification of companies.
 * @export
 */
export const CompanyType = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type CompanyType = typeof CompanyType[keyof typeof CompanyType];


export function instanceOfCompanyType(value: any): boolean {
    for (const key in CompanyType) {
        if (Object.prototype.hasOwnProperty.call(CompanyType, key)) {
            if (CompanyType[key as keyof typeof CompanyType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CompanyTypeFromJSON(json: any): CompanyType {
    return CompanyTypeFromJSONTyped(json, false);
}

export function CompanyTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyType {
    return json as CompanyType;
}

export function CompanyTypeToJSON(value?: CompanyType | null): any {
    return value as any;
}

export function CompanyTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): CompanyType {
    return value as CompanyType;
}

