/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Verification and operational status of a company.
 * @export
 */
export const CompanyStatus = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type CompanyStatus = typeof CompanyStatus[keyof typeof CompanyStatus];


export function instanceOfCompanyStatus(value: any): boolean {
    for (const key in CompanyStatus) {
        if (Object.prototype.hasOwnProperty.call(CompanyStatus, key)) {
            if (CompanyStatus[key as keyof typeof CompanyStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CompanyStatusFromJSON(json: any): CompanyStatus {
    return CompanyStatusFromJSONTyped(json, false);
}

export function CompanyStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyStatus {
    return json as CompanyStatus;
}

export function CompanyStatusToJSON(value?: CompanyStatus | null): any {
    return value as any;
}

export function CompanyStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): CompanyStatus {
    return value as CompanyStatus;
}

