/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Days of the week (used for scheduling).
 * @export
 */
export const Day = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6,
    NUMBER_7: 7
} as const;
export type Day = typeof Day[keyof typeof Day];


export function instanceOfDay(value: any): boolean {
    for (const key in Day) {
        if (Object.prototype.hasOwnProperty.call(Day, key)) {
            if (Day[key as keyof typeof Day] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DayFromJSON(json: any): Day {
    return DayFromJSONTyped(json, false);
}

export function DayFromJSONTyped(json: any, ignoreDiscriminator: boolean): Day {
    return json as Day;
}

export function DayToJSON(value?: Day | null): any {
    return value as any;
}

export function DayToJSONTyped(value: any, ignoreDiscriminator: boolean): Day {
    return value as Day;
}

