/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Lifecycle states of a duty.
 * @export
 */
export const DutyStatus = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5
} as const;
export type DutyStatus = typeof DutyStatus[keyof typeof DutyStatus];


export function instanceOfDutyStatus(value: any): boolean {
    for (const key in DutyStatus) {
        if (Object.prototype.hasOwnProperty.call(DutyStatus, key)) {
            if (DutyStatus[key as keyof typeof DutyStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DutyStatusFromJSON(json: any): DutyStatus {
    return DutyStatusFromJSONTyped(json, false);
}

export function DutyStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): DutyStatus {
    return json as DutyStatus;
}

export function DutyStatusToJSON(value?: DutyStatus | null): any {
    return value as any;
}

export function DutyStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): DutyStatus {
    return value as DutyStatus;
}

