/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExecutiveRoleMapSchema
 */
export interface ExecutiveRoleMapSchema {
    /**
     * 
     * @type {number}
     * @memberof ExecutiveRoleMapSchema
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof ExecutiveRoleMapSchema
     */
    roleId: number;
    /**
     * 
     * @type {number}
     * @memberof ExecutiveRoleMapSchema
     */
    executiveId: number;
    /**
     * 
     * @type {Date}
     * @memberof ExecutiveRoleMapSchema
     */
    updatedOn: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ExecutiveRoleMapSchema
     */
    createdOn: Date;
}

/**
 * Check if a given object implements the ExecutiveRoleMapSchema interface.
 */
export function instanceOfExecutiveRoleMapSchema(value: object): value is ExecutiveRoleMapSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('roleId' in value) || value['roleId'] === undefined) return false;
    if (!('executiveId' in value) || value['executiveId'] === undefined) return false;
    if (!('updatedOn' in value) || value['updatedOn'] === undefined) return false;
    if (!('createdOn' in value) || value['createdOn'] === undefined) return false;
    return true;
}

export function ExecutiveRoleMapSchemaFromJSON(json: any): ExecutiveRoleMapSchema {
    return ExecutiveRoleMapSchemaFromJSONTyped(json, false);
}

export function ExecutiveRoleMapSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecutiveRoleMapSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'roleId': json['role_id'],
        'executiveId': json['executive_id'],
        'updatedOn': (json['updated_on'] == null ? null : new Date(json['updated_on'])),
        'createdOn': (new Date(json['created_on'])),
    };
}

export function ExecutiveRoleMapSchemaToJSON(json: any): ExecutiveRoleMapSchema {
    return ExecutiveRoleMapSchemaToJSONTyped(json, false);
}

export function ExecutiveRoleMapSchemaToJSONTyped(value?: ExecutiveRoleMapSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'role_id': value['roleId'],
        'executive_id': value['executiveId'],
        'updated_on': value['updatedOn'] == null ? value['updatedOn'] : value['updatedOn'].toISOString(),
        'created_on': value['createdOn'].toISOString(),
    };
}

