/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExecutiveImageSchema
 */
export interface ExecutiveImageSchema {
    /**
     * 
     * @type {number}
     * @memberof ExecutiveImageSchema
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof ExecutiveImageSchema
     */
    executiveId: number;
    /**
     * 
     * @type {string}
     * @memberof ExecutiveImageSchema
     */
    fileName: string;
    /**
     * 
     * @type {string}
     * @memberof ExecutiveImageSchema
     */
    fileType: string;
    /**
     * 
     * @type {number}
     * @memberof ExecutiveImageSchema
     */
    fileSize: number;
    /**
     * 
     * @type {Date}
     * @memberof ExecutiveImageSchema
     */
    createdOn: Date;
}

/**
 * Check if a given object implements the ExecutiveImageSchema interface.
 */
export function instanceOfExecutiveImageSchema(value: object): value is ExecutiveImageSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('executiveId' in value) || value['executiveId'] === undefined) return false;
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    if (!('fileType' in value) || value['fileType'] === undefined) return false;
    if (!('fileSize' in value) || value['fileSize'] === undefined) return false;
    if (!('createdOn' in value) || value['createdOn'] === undefined) return false;
    return true;
}

export function ExecutiveImageSchemaFromJSON(json: any): ExecutiveImageSchema {
    return ExecutiveImageSchemaFromJSONTyped(json, false);
}

export function ExecutiveImageSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecutiveImageSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'executiveId': json['executive_id'],
        'fileName': json['file_name'],
        'fileType': json['file_type'],
        'fileSize': json['file_size'],
        'createdOn': (new Date(json['created_on'])),
    };
}

export function ExecutiveImageSchemaToJSON(json: any): ExecutiveImageSchema {
    return ExecutiveImageSchemaToJSONTyped(json, false);
}

export function ExecutiveImageSchemaToJSONTyped(value?: ExecutiveImageSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'executive_id': value['executiveId'],
        'file_name': value['fileName'],
        'file_type': value['fileType'],
        'file_size': value['fileSize'],
        'created_on': value['createdOn'].toISOString(),
    };
}

