/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TicketTypesInAttribute } from './TicketTypesInAttribute';
import {
    TicketTypesInAttributeFromJSON,
    TicketTypesInAttributeFromJSONTyped,
    TicketTypesInAttributeToJSON,
    TicketTypesInAttributeToJSONTyped,
} from './TicketTypesInAttribute';

/**
 * 
 * @export
 * @interface FareAttributes
 */
export interface FareAttributes {
    /**
     * 
     * @type {number}
     * @memberof FareAttributes
     */
    dfVersion: number;
    /**
     * 
     * @type {Array<TicketTypesInAttribute>}
     * @memberof FareAttributes
     */
    ticketTypes: Array<TicketTypesInAttribute>;
    /**
     * 
     * @type {string}
     * @memberof FareAttributes
     */
    currencyType: string;
    /**
     * 
     * @type {string}
     * @memberof FareAttributes
     */
    distanceUnit: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof FareAttributes
     */
    extra: { [key: string]: any; };
}

/**
 * Check if a given object implements the FareAttributes interface.
 */
export function instanceOfFareAttributes(value: object): value is FareAttributes {
    if (!('dfVersion' in value) || value['dfVersion'] === undefined) return false;
    if (!('ticketTypes' in value) || value['ticketTypes'] === undefined) return false;
    if (!('currencyType' in value) || value['currencyType'] === undefined) return false;
    if (!('distanceUnit' in value) || value['distanceUnit'] === undefined) return false;
    if (!('extra' in value) || value['extra'] === undefined) return false;
    return true;
}

export function FareAttributesFromJSON(json: any): FareAttributes {
    return FareAttributesFromJSONTyped(json, false);
}

export function FareAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): FareAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'dfVersion': json['df_version'],
        'ticketTypes': ((json['ticket_types'] as Array<any>).map(TicketTypesInAttributeFromJSON)),
        'currencyType': json['currency_type'],
        'distanceUnit': json['distance_unit'],
        'extra': json['extra'],
    };
}

export function FareAttributesToJSON(json: any): FareAttributes {
    return FareAttributesToJSONTyped(json, false);
}

export function FareAttributesToJSONTyped(value?: FareAttributes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'df_version': value['dfVersion'],
        'ticket_types': ((value['ticketTypes'] as Array<any>).map(TicketTypesInAttributeToJSON)),
        'currency_type': value['currencyType'],
        'distance_unit': value['distanceUnit'],
        'extra': value['extra'],
    };
}

