/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Gender identifiers for user profiles.
 * @export
 */
export const GenderType = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type GenderType = typeof GenderType[keyof typeof GenderType];


export function instanceOfGenderType(value: any): boolean {
    for (const key in GenderType) {
        if (Object.prototype.hasOwnProperty.call(GenderType, key)) {
            if (GenderType[key as keyof typeof GenderType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function GenderTypeFromJSON(json: any): GenderType {
    return GenderTypeFromJSONTyped(json, false);
}

export function GenderTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenderType {
    return json as GenderType;
}

export function GenderTypeToJSON(value?: GenderType | null): any {
    return value as any;
}

export function GenderTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): GenderType {
    return value as GenderType;
}

