/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LandmarkInRouteSchema
 */
export interface LandmarkInRouteSchema {
    /**
     * 
     * @type {number}
     * @memberof LandmarkInRouteSchema
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof LandmarkInRouteSchema
     */
    companyId: number;
    /**
     * 
     * @type {number}
     * @memberof LandmarkInRouteSchema
     */
    routeId: number;
    /**
     * 
     * @type {number}
     * @memberof LandmarkInRouteSchema
     */
    landmarkId: number;
    /**
     * 
     * @type {number}
     * @memberof LandmarkInRouteSchema
     */
    distanceFromStart: number;
    /**
     * 
     * @type {number}
     * @memberof LandmarkInRouteSchema
     */
    arrivalDelta: number;
    /**
     * 
     * @type {number}
     * @memberof LandmarkInRouteSchema
     */
    departureDelta: number;
    /**
     * 
     * @type {Date}
     * @memberof LandmarkInRouteSchema
     */
    updatedOn: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof LandmarkInRouteSchema
     */
    createdOn: Date;
}

/**
 * Check if a given object implements the LandmarkInRouteSchema interface.
 */
export function instanceOfLandmarkInRouteSchema(value: object): value is LandmarkInRouteSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    if (!('routeId' in value) || value['routeId'] === undefined) return false;
    if (!('landmarkId' in value) || value['landmarkId'] === undefined) return false;
    if (!('distanceFromStart' in value) || value['distanceFromStart'] === undefined) return false;
    if (!('arrivalDelta' in value) || value['arrivalDelta'] === undefined) return false;
    if (!('departureDelta' in value) || value['departureDelta'] === undefined) return false;
    if (!('updatedOn' in value) || value['updatedOn'] === undefined) return false;
    if (!('createdOn' in value) || value['createdOn'] === undefined) return false;
    return true;
}

export function LandmarkInRouteSchemaFromJSON(json: any): LandmarkInRouteSchema {
    return LandmarkInRouteSchemaFromJSONTyped(json, false);
}

export function LandmarkInRouteSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): LandmarkInRouteSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'companyId': json['company_id'],
        'routeId': json['route_id'],
        'landmarkId': json['landmark_id'],
        'distanceFromStart': json['distance_from_start'],
        'arrivalDelta': json['arrival_delta'],
        'departureDelta': json['departure_delta'],
        'updatedOn': (json['updated_on'] == null ? null : new Date(json['updated_on'])),
        'createdOn': (new Date(json['created_on'])),
    };
}

export function LandmarkInRouteSchemaToJSON(json: any): LandmarkInRouteSchema {
    return LandmarkInRouteSchemaToJSONTyped(json, false);
}

export function LandmarkInRouteSchemaToJSONTyped(value?: LandmarkInRouteSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'company_id': value['companyId'],
        'route_id': value['routeId'],
        'landmark_id': value['landmarkId'],
        'distance_from_start': value['distanceFromStart'],
        'arrival_delta': value['arrivalDelta'],
        'departure_delta': value['departureDelta'],
        'updated_on': value['updatedOn'] == null ? value['updatedOn'] : value['updatedOn'].toISOString(),
        'created_on': value['createdOn'].toISOString(),
    };
}

