/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LandmarkSchema
 */
export interface LandmarkSchema {
    /**
     * 
     * @type {number}
     * @memberof LandmarkSchema
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof LandmarkSchema
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof LandmarkSchema
     */
    version: number;
    /**
     * 
     * @type {string}
     * @memberof LandmarkSchema
     */
    boundary: string;
    /**
     * 
     * @type {number}
     * @memberof LandmarkSchema
     */
    type: number;
    /**
     * 
     * @type {Date}
     * @memberof LandmarkSchema
     */
    updatedOn: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof LandmarkSchema
     */
    createdOn: Date;
}

/**
 * Check if a given object implements the LandmarkSchema interface.
 */
export function instanceOfLandmarkSchema(value: object): value is LandmarkSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('boundary' in value) || value['boundary'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('updatedOn' in value) || value['updatedOn'] === undefined) return false;
    if (!('createdOn' in value) || value['createdOn'] === undefined) return false;
    return true;
}

export function LandmarkSchemaFromJSON(json: any): LandmarkSchema {
    return LandmarkSchemaFromJSONTyped(json, false);
}

export function LandmarkSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): LandmarkSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'version': json['version'],
        'boundary': json['boundary'],
        'type': json['type'],
        'updatedOn': (json['updated_on'] == null ? null : new Date(json['updated_on'])),
        'createdOn': (new Date(json['created_on'])),
    };
}

export function LandmarkSchemaToJSON(json: any): LandmarkSchema {
    return LandmarkSchemaToJSONTyped(json, false);
}

export function LandmarkSchemaToJSONTyped(value?: LandmarkSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'version': value['version'],
        'boundary': value['boundary'],
        'type': value['type'],
        'updated_on': value['updatedOn'] == null ? value['updatedOn'] : value['updatedOn'].toISOString(),
        'created_on': value['createdOn'].toISOString(),
    };
}

