/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Administrative level or importance of a landmark
 * @export
 */
export const LandmarkType = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5
} as const;
export type LandmarkType = typeof LandmarkType[keyof typeof LandmarkType];


export function instanceOfLandmarkType(value: any): boolean {
    for (const key in LandmarkType) {
        if (Object.prototype.hasOwnProperty.call(LandmarkType, key)) {
            if (LandmarkType[key as keyof typeof LandmarkType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LandmarkTypeFromJSON(json: any): LandmarkType {
    return LandmarkTypeFromJSONTyped(json, false);
}

export function LandmarkTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LandmarkType {
    return json as LandmarkType;
}

export function LandmarkTypeToJSON(value?: LandmarkType | null): any {
    return value as any;
}

export function LandmarkTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): LandmarkType {
    return value as LandmarkType;
}

