/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MaskedVendorTokenSchema
 */
export interface MaskedVendorTokenSchema {
    /**
     * 
     * @type {number}
     * @memberof MaskedVendorTokenSchema
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof MaskedVendorTokenSchema
     */
    vendorId: number;
    /**
     * 
     * @type {number}
     * @memberof MaskedVendorTokenSchema
     */
    businessId: number;
    /**
     * 
     * @type {number}
     * @memberof MaskedVendorTokenSchema
     */
    expiresIn: number;
    /**
     * 
     * @type {number}
     * @memberof MaskedVendorTokenSchema
     */
    platformType: number;
    /**
     * 
     * @type {string}
     * @memberof MaskedVendorTokenSchema
     */
    clientDetails: string | null;
    /**
     * 
     * @type {Date}
     * @memberof MaskedVendorTokenSchema
     */
    createdOn: Date;
    /**
     * 
     * @type {Date}
     * @memberof MaskedVendorTokenSchema
     */
    updatedOn: Date | null;
}

/**
 * Check if a given object implements the MaskedVendorTokenSchema interface.
 */
export function instanceOfMaskedVendorTokenSchema(value: object): value is MaskedVendorTokenSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('vendorId' in value) || value['vendorId'] === undefined) return false;
    if (!('businessId' in value) || value['businessId'] === undefined) return false;
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    if (!('platformType' in value) || value['platformType'] === undefined) return false;
    if (!('clientDetails' in value) || value['clientDetails'] === undefined) return false;
    if (!('createdOn' in value) || value['createdOn'] === undefined) return false;
    if (!('updatedOn' in value) || value['updatedOn'] === undefined) return false;
    return true;
}

export function MaskedVendorTokenSchemaFromJSON(json: any): MaskedVendorTokenSchema {
    return MaskedVendorTokenSchemaFromJSONTyped(json, false);
}

export function MaskedVendorTokenSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaskedVendorTokenSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'vendorId': json['vendor_id'],
        'businessId': json['business_id'],
        'expiresIn': json['expires_in'],
        'platformType': json['platform_type'],
        'clientDetails': json['client_details'],
        'createdOn': (new Date(json['created_on'])),
        'updatedOn': (json['updated_on'] == null ? null : new Date(json['updated_on'])),
    };
}

export function MaskedVendorTokenSchemaToJSON(json: any): MaskedVendorTokenSchema {
    return MaskedVendorTokenSchemaToJSONTyped(json, false);
}

export function MaskedVendorTokenSchemaToJSONTyped(value?: MaskedVendorTokenSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'vendor_id': value['vendorId'],
        'business_id': value['businessId'],
        'expires_in': value['expiresIn'],
        'platform_type': value['platformType'],
        'client_details': value['clientDetails'],
        'created_on': value['createdOn'].toISOString(),
        'updated_on': value['updatedOn'] == null ? value['updatedOn'] : value['updatedOn'].toISOString(),
    };
}

