/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MaskedOperatorTokenSchema
 */
export interface MaskedOperatorTokenSchema {
    /**
     * 
     * @type {number}
     * @memberof MaskedOperatorTokenSchema
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof MaskedOperatorTokenSchema
     */
    operatorId: number;
    /**
     * 
     * @type {number}
     * @memberof MaskedOperatorTokenSchema
     */
    companyId: number;
    /**
     * 
     * @type {number}
     * @memberof MaskedOperatorTokenSchema
     */
    expiresIn: number;
    /**
     * 
     * @type {number}
     * @memberof MaskedOperatorTokenSchema
     */
    platformType: number;
    /**
     * 
     * @type {string}
     * @memberof MaskedOperatorTokenSchema
     */
    clientDetails: string | null;
    /**
     * 
     * @type {Date}
     * @memberof MaskedOperatorTokenSchema
     */
    createdOn: Date;
    /**
     * 
     * @type {Date}
     * @memberof MaskedOperatorTokenSchema
     */
    updatedOn: Date | null;
}

/**
 * Check if a given object implements the MaskedOperatorTokenSchema interface.
 */
export function instanceOfMaskedOperatorTokenSchema(value: object): value is MaskedOperatorTokenSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('operatorId' in value) || value['operatorId'] === undefined) return false;
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    if (!('platformType' in value) || value['platformType'] === undefined) return false;
    if (!('clientDetails' in value) || value['clientDetails'] === undefined) return false;
    if (!('createdOn' in value) || value['createdOn'] === undefined) return false;
    if (!('updatedOn' in value) || value['updatedOn'] === undefined) return false;
    return true;
}

export function MaskedOperatorTokenSchemaFromJSON(json: any): MaskedOperatorTokenSchema {
    return MaskedOperatorTokenSchemaFromJSONTyped(json, false);
}

export function MaskedOperatorTokenSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaskedOperatorTokenSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'operatorId': json['operator_id'],
        'companyId': json['company_id'],
        'expiresIn': json['expires_in'],
        'platformType': json['platform_type'],
        'clientDetails': json['client_details'],
        'createdOn': (new Date(json['created_on'])),
        'updatedOn': (json['updated_on'] == null ? null : new Date(json['updated_on'])),
    };
}

export function MaskedOperatorTokenSchemaToJSON(json: any): MaskedOperatorTokenSchema {
    return MaskedOperatorTokenSchemaToJSONTyped(json, false);
}

export function MaskedOperatorTokenSchemaToJSONTyped(value?: MaskedOperatorTokenSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'operator_id': value['operatorId'],
        'company_id': value['companyId'],
        'expires_in': value['expiresIn'],
        'platform_type': value['platformType'],
        'client_details': value['clientDetails'],
        'created_on': value['createdOn'].toISOString(),
        'updated_on': value['updatedOn'] == null ? value['updatedOn'] : value['updatedOn'].toISOString(),
    };
}

