/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperatorRoleMapSchema
 */
export interface OperatorRoleMapSchema {
    /**
     * 
     * @type {number}
     * @memberof OperatorRoleMapSchema
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof OperatorRoleMapSchema
     */
    companyId: number;
    /**
     * 
     * @type {number}
     * @memberof OperatorRoleMapSchema
     */
    roleId: number;
    /**
     * 
     * @type {number}
     * @memberof OperatorRoleMapSchema
     */
    operatorId: number;
    /**
     * 
     * @type {Date}
     * @memberof OperatorRoleMapSchema
     */
    updatedOn: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof OperatorRoleMapSchema
     */
    createdOn: Date;
}

/**
 * Check if a given object implements the OperatorRoleMapSchema interface.
 */
export function instanceOfOperatorRoleMapSchema(value: object): value is OperatorRoleMapSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    if (!('roleId' in value) || value['roleId'] === undefined) return false;
    if (!('operatorId' in value) || value['operatorId'] === undefined) return false;
    if (!('updatedOn' in value) || value['updatedOn'] === undefined) return false;
    if (!('createdOn' in value) || value['createdOn'] === undefined) return false;
    return true;
}

export function OperatorRoleMapSchemaFromJSON(json: any): OperatorRoleMapSchema {
    return OperatorRoleMapSchemaFromJSONTyped(json, false);
}

export function OperatorRoleMapSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperatorRoleMapSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'companyId': json['company_id'],
        'roleId': json['role_id'],
        'operatorId': json['operator_id'],
        'updatedOn': (json['updated_on'] == null ? null : new Date(json['updated_on'])),
        'createdOn': (new Date(json['created_on'])),
    };
}

export function OperatorRoleMapSchemaToJSON(json: any): OperatorRoleMapSchema {
    return OperatorRoleMapSchemaToJSONTyped(json, false);
}

export function OperatorRoleMapSchemaToJSONTyped(value?: OperatorRoleMapSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'company_id': value['companyId'],
        'role_id': value['roleId'],
        'operator_id': value['operatorId'],
        'updated_on': value['updatedOn'] == null ? value['updatedOn'] : value['updatedOn'].toISOString(),
        'created_on': value['createdOn'].toISOString(),
    };
}

