/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TicketTypes } from './TicketTypes';
import {
    TicketTypesFromJSON,
    TicketTypesFromJSONTyped,
    TicketTypesToJSON,
    TicketTypesToJSONTyped,
} from './TicketTypes';

/**
 * 
 * @export
 * @interface PaperTicketSchema
 */
export interface PaperTicketSchema {
    /**
     * 
     * @type {number}
     * @memberof PaperTicketSchema
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof PaperTicketSchema
     */
    serviceId: number;
    /**
     * 
     * @type {number}
     * @memberof PaperTicketSchema
     */
    dutyId: number;
    /**
     * 
     * @type {number}
     * @memberof PaperTicketSchema
     */
    companyId: number;
    /**
     * 
     * @type {number}
     * @memberof PaperTicketSchema
     */
    sequenceId: number;
    /**
     * 
     * @type {Array<TicketTypes>}
     * @memberof PaperTicketSchema
     */
    ticketTypes: Array<TicketTypes>;
    /**
     * 
     * @type {number}
     * @memberof PaperTicketSchema
     */
    pickupPoint: number;
    /**
     * 
     * @type {number}
     * @memberof PaperTicketSchema
     */
    droppingPoint: number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof PaperTicketSchema
     */
    extra: { [key: string]: any; };
    /**
     * 
     * @type {number}
     * @memberof PaperTicketSchema
     */
    distance: number;
    /**
     * 
     * @type {number}
     * @memberof PaperTicketSchema
     */
    amount: number;
    /**
     * 
     * @type {Date}
     * @memberof PaperTicketSchema
     */
    updatedOn: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PaperTicketSchema
     */
    createdOn: Date;
}

/**
 * Check if a given object implements the PaperTicketSchema interface.
 */
export function instanceOfPaperTicketSchema(value: object): value is PaperTicketSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('dutyId' in value) || value['dutyId'] === undefined) return false;
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    if (!('sequenceId' in value) || value['sequenceId'] === undefined) return false;
    if (!('ticketTypes' in value) || value['ticketTypes'] === undefined) return false;
    if (!('pickupPoint' in value) || value['pickupPoint'] === undefined) return false;
    if (!('droppingPoint' in value) || value['droppingPoint'] === undefined) return false;
    if (!('extra' in value) || value['extra'] === undefined) return false;
    if (!('distance' in value) || value['distance'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('updatedOn' in value) || value['updatedOn'] === undefined) return false;
    if (!('createdOn' in value) || value['createdOn'] === undefined) return false;
    return true;
}

export function PaperTicketSchemaFromJSON(json: any): PaperTicketSchema {
    return PaperTicketSchemaFromJSONTyped(json, false);
}

export function PaperTicketSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaperTicketSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'serviceId': json['service_id'],
        'dutyId': json['duty_id'],
        'companyId': json['company_id'],
        'sequenceId': json['sequence_id'],
        'ticketTypes': ((json['ticket_types'] as Array<any>).map(TicketTypesFromJSON)),
        'pickupPoint': json['pickup_point'],
        'droppingPoint': json['dropping_point'],
        'extra': json['extra'],
        'distance': json['distance'],
        'amount': json['amount'],
        'updatedOn': (json['updated_on'] == null ? null : new Date(json['updated_on'])),
        'createdOn': (new Date(json['created_on'])),
    };
}

export function PaperTicketSchemaToJSON(json: any): PaperTicketSchema {
    return PaperTicketSchemaToJSONTyped(json, false);
}

export function PaperTicketSchemaToJSONTyped(value?: PaperTicketSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'service_id': value['serviceId'],
        'duty_id': value['dutyId'],
        'company_id': value['companyId'],
        'sequence_id': value['sequenceId'],
        'ticket_types': ((value['ticketTypes'] as Array<any>).map(TicketTypesToJSON)),
        'pickup_point': value['pickupPoint'],
        'dropping_point': value['droppingPoint'],
        'extra': value['extra'],
        'distance': value['distance'],
        'amount': value['amount'],
        'updated_on': value['updatedOn'] == null ? value['updatedOn'] : value['updatedOn'].toISOString(),
        'created_on': value['createdOn'].toISOString(),
    };
}

