/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Platform used to access the system.
 * @export
 */
export const PlatformType = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type PlatformType = typeof PlatformType[keyof typeof PlatformType];


export function instanceOfPlatformType(value: any): boolean {
    for (const key in PlatformType) {
        if (Object.prototype.hasOwnProperty.call(PlatformType, key)) {
            if (PlatformType[key as keyof typeof PlatformType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PlatformTypeFromJSON(json: any): PlatformType {
    return PlatformTypeFromJSONTyped(json, false);
}

export function PlatformTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlatformType {
    return json as PlatformType;
}

export function PlatformTypeToJSON(value?: PlatformType | null): any {
    return value as any;
}

export function PlatformTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): PlatformType {
    return value as PlatformType;
}

