/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RouteSchema
 */
export interface RouteSchema {
    /**
     * 
     * @type {number}
     * @memberof RouteSchema
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof RouteSchema
     */
    companyId: number;
    /**
     * 
     * @type {string}
     * @memberof RouteSchema
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RouteSchema
     */
    startTime: string;
    /**
     * 
     * @type {number}
     * @memberof RouteSchema
     */
    status: number;
    /**
     * 
     * @type {Date}
     * @memberof RouteSchema
     */
    updatedOn: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof RouteSchema
     */
    createdOn: Date;
}

/**
 * Check if a given object implements the RouteSchema interface.
 */
export function instanceOfRouteSchema(value: object): value is RouteSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('updatedOn' in value) || value['updatedOn'] === undefined) return false;
    if (!('createdOn' in value) || value['createdOn'] === undefined) return false;
    return true;
}

export function RouteSchemaFromJSON(json: any): RouteSchema {
    return RouteSchemaFromJSONTyped(json, false);
}

export function RouteSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'companyId': json['company_id'],
        'name': json['name'],
        'startTime': json['start_time'],
        'status': json['status'],
        'updatedOn': (json['updated_on'] == null ? null : new Date(json['updated_on'])),
        'createdOn': (new Date(json['created_on'])),
    };
}

export function RouteSchemaToJSON(json: any): RouteSchema {
    return RouteSchemaToJSONTyped(json, false);
}

export function RouteSchemaToJSONTyped(value?: RouteSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'company_id': value['companyId'],
        'name': value['name'],
        'start_time': value['startTime'],
        'status': value['status'],
        'updated_on': value['updatedOn'] == null ? value['updatedOn'] : value['updatedOn'].toISOString(),
        'created_on': value['createdOn'].toISOString(),
    };
}

