/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScheduleSchema
 */
export interface ScheduleSchema {
    /**
     * 
     * @type {number}
     * @memberof ScheduleSchema
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof ScheduleSchema
     */
    companyId: number;
    /**
     * 
     * @type {string}
     * @memberof ScheduleSchema
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ScheduleSchema
     */
    description: string | null;
    /**
     * 
     * @type {number}
     * @memberof ScheduleSchema
     */
    routeId: number | null;
    /**
     * 
     * @type {number}
     * @memberof ScheduleSchema
     */
    fareId: number | null;
    /**
     * 
     * @type {number}
     * @memberof ScheduleSchema
     */
    busId: number | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof ScheduleSchema
     */
    frequency: Array<number> | null;
    /**
     * 
     * @type {number}
     * @memberof ScheduleSchema
     */
    ticketingMode: number;
    /**
     * 
     * @type {number}
     * @memberof ScheduleSchema
     */
    triggeringMode: number;
    /**
     * 
     * @type {Date}
     * @memberof ScheduleSchema
     */
    nextTriggerOn: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ScheduleSchema
     */
    lastTriggerOn: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ScheduleSchema
     */
    triggerTill: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ScheduleSchema
     */
    updatedOn: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ScheduleSchema
     */
    createdOn: Date;
}

/**
 * Check if a given object implements the ScheduleSchema interface.
 */
export function instanceOfScheduleSchema(value: object): value is ScheduleSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('routeId' in value) || value['routeId'] === undefined) return false;
    if (!('fareId' in value) || value['fareId'] === undefined) return false;
    if (!('busId' in value) || value['busId'] === undefined) return false;
    if (!('frequency' in value) || value['frequency'] === undefined) return false;
    if (!('ticketingMode' in value) || value['ticketingMode'] === undefined) return false;
    if (!('triggeringMode' in value) || value['triggeringMode'] === undefined) return false;
    if (!('nextTriggerOn' in value) || value['nextTriggerOn'] === undefined) return false;
    if (!('lastTriggerOn' in value) || value['lastTriggerOn'] === undefined) return false;
    if (!('triggerTill' in value) || value['triggerTill'] === undefined) return false;
    if (!('updatedOn' in value) || value['updatedOn'] === undefined) return false;
    if (!('createdOn' in value) || value['createdOn'] === undefined) return false;
    return true;
}

export function ScheduleSchemaFromJSON(json: any): ScheduleSchema {
    return ScheduleSchemaFromJSONTyped(json, false);
}

export function ScheduleSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'companyId': json['company_id'],
        'name': json['name'],
        'description': json['description'],
        'routeId': json['route_id'],
        'fareId': json['fare_id'],
        'busId': json['bus_id'],
        'frequency': json['frequency'] == null ? null : json['frequency'],
        'ticketingMode': json['ticketing_mode'],
        'triggeringMode': json['triggering_mode'],
        'nextTriggerOn': (json['next_trigger_on'] == null ? null : new Date(json['next_trigger_on'])),
        'lastTriggerOn': (json['last_trigger_on'] == null ? null : new Date(json['last_trigger_on'])),
        'triggerTill': (json['trigger_till'] == null ? null : new Date(json['trigger_till'])),
        'updatedOn': (json['updated_on'] == null ? null : new Date(json['updated_on'])),
        'createdOn': (new Date(json['created_on'])),
    };
}

export function ScheduleSchemaToJSON(json: any): ScheduleSchema {
    return ScheduleSchemaToJSONTyped(json, false);
}

export function ScheduleSchemaToJSONTyped(value?: ScheduleSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'company_id': value['companyId'],
        'name': value['name'],
        'description': value['description'],
        'route_id': value['routeId'],
        'fare_id': value['fareId'],
        'bus_id': value['busId'],
        'frequency': value['frequency'],
        'ticketing_mode': value['ticketingMode'],
        'triggering_mode': value['triggeringMode'],
        'next_trigger_on': value['nextTriggerOn'] == null ? value['nextTriggerOn'] : value['nextTriggerOn'].toISOString(),
        'last_trigger_on': value['lastTriggerOn'] == null ? value['lastTriggerOn'] : value['lastTriggerOn'].toISOString(),
        'trigger_till': value['triggerTill'] == null ? value['triggerTill'] : value['triggerTill'].toISOString(),
        'updated_on': value['updatedOn'] == null ? value['updatedOn'] : value['updatedOn'].toISOString(),
        'created_on': value['createdOn'].toISOString(),
    };
}

