/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceTraceSchema
 */
export interface ServiceTraceSchema {
    /**
     * 
     * @type {number}
     * @memberof ServiceTraceSchema
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof ServiceTraceSchema
     */
    companyId: number;
    /**
     * 
     * @type {number}
     * @memberof ServiceTraceSchema
     */
    dutyId: number | null;
    /**
     * 
     * @type {number}
     * @memberof ServiceTraceSchema
     */
    serviceId: number;
    /**
     * 
     * @type {number}
     * @memberof ServiceTraceSchema
     */
    landmarkId: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceTraceSchema
     */
    location: string | null;
    /**
     * 
     * @type {number}
     * @memberof ServiceTraceSchema
     */
    accurate: number | null;
    /**
     * 
     * @type {Date}
     * @memberof ServiceTraceSchema
     */
    updatedOn: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ServiceTraceSchema
     */
    createdOn: Date;
}

/**
 * Check if a given object implements the ServiceTraceSchema interface.
 */
export function instanceOfServiceTraceSchema(value: object): value is ServiceTraceSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    if (!('dutyId' in value) || value['dutyId'] === undefined) return false;
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('landmarkId' in value) || value['landmarkId'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('accurate' in value) || value['accurate'] === undefined) return false;
    if (!('updatedOn' in value) || value['updatedOn'] === undefined) return false;
    if (!('createdOn' in value) || value['createdOn'] === undefined) return false;
    return true;
}

export function ServiceTraceSchemaFromJSON(json: any): ServiceTraceSchema {
    return ServiceTraceSchemaFromJSONTyped(json, false);
}

export function ServiceTraceSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceTraceSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'companyId': json['company_id'],
        'dutyId': json['duty_id'],
        'serviceId': json['service_id'],
        'landmarkId': json['landmark_id'],
        'location': json['location'],
        'accurate': json['accurate'],
        'updatedOn': (json['updated_on'] == null ? null : new Date(json['updated_on'])),
        'createdOn': (new Date(json['created_on'])),
    };
}

export function ServiceTraceSchemaToJSON(json: any): ServiceTraceSchema {
    return ServiceTraceSchemaToJSONTyped(json, false);
}

export function ServiceTraceSchemaToJSONTyped(value?: ServiceTraceSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'company_id': value['companyId'],
        'duty_id': value['dutyId'],
        'service_id': value['serviceId'],
        'landmark_id': value['landmarkId'],
        'location': value['location'],
        'accurate': value['accurate'],
        'updated_on': value['updatedOn'] == null ? value['updatedOn'] : value['updatedOn'].toISOString(),
        'created_on': value['createdOn'].toISOString(),
    };
}

