/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceSchema
 */
export interface ServiceSchema {
    /**
     * 
     * @type {number}
     * @memberof ServiceSchema
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof ServiceSchema
     */
    companyId: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceSchema
     */
    name: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ServiceSchema
     */
    route: { [key: string]: any; };
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ServiceSchema
     */
    fare: { [key: string]: any; };
    /**
     * 
     * @type {number}
     * @memberof ServiceSchema
     */
    busId: number;
    /**
     * 
     * @type {number}
     * @memberof ServiceSchema
     */
    ticketMode: number;
    /**
     * 
     * @type {number}
     * @memberof ServiceSchema
     */
    status: number;
    /**
     * 
     * @type {Date}
     * @memberof ServiceSchema
     */
    startingAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ServiceSchema
     */
    endingAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ServiceSchema
     */
    remark: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ServiceSchema
     */
    startedOn: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ServiceSchema
     */
    finishedOn: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ServiceSchema
     */
    updatedOn: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ServiceSchema
     */
    createdOn: Date;
    /**
     * 
     * @type {number}
     * @memberof ServiceSchema
     */
    scheduleId: number | null;
    /**
     * 
     * @type {string}
     * @memberof ServiceSchema
     */
    publicKey: string;
}

/**
 * Check if a given object implements the ServiceSchema interface.
 */
export function instanceOfServiceSchema(value: object): value is ServiceSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('route' in value) || value['route'] === undefined) return false;
    if (!('fare' in value) || value['fare'] === undefined) return false;
    if (!('busId' in value) || value['busId'] === undefined) return false;
    if (!('ticketMode' in value) || value['ticketMode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('startingAt' in value) || value['startingAt'] === undefined) return false;
    if (!('endingAt' in value) || value['endingAt'] === undefined) return false;
    if (!('remark' in value) || value['remark'] === undefined) return false;
    if (!('startedOn' in value) || value['startedOn'] === undefined) return false;
    if (!('finishedOn' in value) || value['finishedOn'] === undefined) return false;
    if (!('updatedOn' in value) || value['updatedOn'] === undefined) return false;
    if (!('createdOn' in value) || value['createdOn'] === undefined) return false;
    if (!('scheduleId' in value) || value['scheduleId'] === undefined) return false;
    if (!('publicKey' in value) || value['publicKey'] === undefined) return false;
    return true;
}

export function ServiceSchemaFromJSON(json: any): ServiceSchema {
    return ServiceSchemaFromJSONTyped(json, false);
}

export function ServiceSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'companyId': json['company_id'],
        'name': json['name'],
        'route': json['route'],
        'fare': json['fare'],
        'busId': json['bus_id'],
        'ticketMode': json['ticket_mode'],
        'status': json['status'],
        'startingAt': (new Date(json['starting_at'])),
        'endingAt': (new Date(json['ending_at'])),
        'remark': json['remark'],
        'startedOn': (json['started_on'] == null ? null : new Date(json['started_on'])),
        'finishedOn': (json['finished_on'] == null ? null : new Date(json['finished_on'])),
        'updatedOn': (json['updated_on'] == null ? null : new Date(json['updated_on'])),
        'createdOn': (new Date(json['created_on'])),
        'scheduleId': json['schedule_id'],
        'publicKey': json['public_key'],
    };
}

export function ServiceSchemaToJSON(json: any): ServiceSchema {
    return ServiceSchemaToJSONTyped(json, false);
}

export function ServiceSchemaToJSONTyped(value?: ServiceSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'company_id': value['companyId'],
        'name': value['name'],
        'route': value['route'],
        'fare': value['fare'],
        'bus_id': value['busId'],
        'ticket_mode': value['ticketMode'],
        'status': value['status'],
        'starting_at': value['startingAt'].toISOString(),
        'ending_at': value['endingAt'].toISOString(),
        'remark': value['remark'],
        'started_on': value['startedOn'] == null ? value['startedOn'] : value['startedOn'].toISOString(),
        'finished_on': value['finishedOn'] == null ? value['finishedOn'] : value['finishedOn'].toISOString(),
        'updated_on': value['updatedOn'] == null ? value['updatedOn'] : value['updatedOn'].toISOString(),
        'created_on': value['createdOn'].toISOString(),
        'schedule_id': value['scheduleId'],
        'public_key': value['publicKey'],
    };
}

