/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Modes of ticketing supported by the system.
 * @export
 */
export const TicketingMode = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type TicketingMode = typeof TicketingMode[keyof typeof TicketingMode];


export function instanceOfTicketingMode(value: any): boolean {
    for (const key in TicketingMode) {
        if (Object.prototype.hasOwnProperty.call(TicketingMode, key)) {
            if (TicketingMode[key as keyof typeof TicketingMode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TicketingModeFromJSON(json: any): TicketingMode {
    return TicketingModeFromJSONTyped(json, false);
}

export function TicketingModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketingMode {
    return json as TicketingMode;
}

export function TicketingModeToJSON(value?: TicketingMode | null): any {
    return value as any;
}

export function TicketingModeToJSONTyped(value: any, ignoreDiscriminator: boolean): TicketingMode {
    return value as TicketingMode;
}

