/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TicketTypes
 */
export interface TicketTypes {
    /**
     * 
     * @type {string}
     * @memberof TicketTypes
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof TicketTypes
     */
    count: number;
}

/**
 * Check if a given object implements the TicketTypes interface.
 */
export function instanceOfTicketTypes(value: object): value is TicketTypes {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function TicketTypesFromJSON(json: any): TicketTypes {
    return TicketTypesFromJSONTyped(json, false);
}

export function TicketTypesFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketTypes {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'count': json['count'],
    };
}

export function TicketTypesToJSON(json: any): TicketTypes {
    return TicketTypesToJSONTyped(json, false);
}

export function TicketTypesToJSONTyped(value?: TicketTypes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'count': value['count'],
    };
}

