/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Service triggering configuration.
 * @export
 */
export const TriggeringMode = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type TriggeringMode = typeof TriggeringMode[keyof typeof TriggeringMode];


export function instanceOfTriggeringMode(value: any): boolean {
    for (const key in TriggeringMode) {
        if (Object.prototype.hasOwnProperty.call(TriggeringMode, key)) {
            if (TriggeringMode[key as keyof typeof TriggeringMode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TriggeringModeFromJSON(json: any): TriggeringMode {
    return TriggeringModeFromJSONTyped(json, false);
}

export function TriggeringModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TriggeringMode {
    return json as TriggeringMode;
}

export function TriggeringModeToJSON(value?: TriggeringMode | null): any {
    return value as any;
}

export function TriggeringModeToJSONTyped(value: any, ignoreDiscriminator: boolean): TriggeringMode {
    return value as TriggeringMode;
}

