/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VendorSchema
 */
export interface VendorSchema {
    /**
     * 
     * @type {number}
     * @memberof VendorSchema
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof VendorSchema
     */
    businessId: number;
    /**
     * 
     * @type {string}
     * @memberof VendorSchema
     */
    username: string;
    /**
     * 
     * @type {number}
     * @memberof VendorSchema
     */
    gender: number;
    /**
     * 
     * @type {string}
     * @memberof VendorSchema
     */
    fullName: string | null;
    /**
     * 
     * @type {number}
     * @memberof VendorSchema
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof VendorSchema
     */
    phoneNumber: string | null;
    /**
     * 
     * @type {string}
     * @memberof VendorSchema
     */
    emailId: string | null;
    /**
     * 
     * @type {Date}
     * @memberof VendorSchema
     */
    updatedOn: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof VendorSchema
     */
    createdOn: Date;
}

/**
 * Check if a given object implements the VendorSchema interface.
 */
export function instanceOfVendorSchema(value: object): value is VendorSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('businessId' in value) || value['businessId'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('gender' in value) || value['gender'] === undefined) return false;
    if (!('fullName' in value) || value['fullName'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
    if (!('emailId' in value) || value['emailId'] === undefined) return false;
    if (!('updatedOn' in value) || value['updatedOn'] === undefined) return false;
    if (!('createdOn' in value) || value['createdOn'] === undefined) return false;
    return true;
}

export function VendorSchemaFromJSON(json: any): VendorSchema {
    return VendorSchemaFromJSONTyped(json, false);
}

export function VendorSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): VendorSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'businessId': json['business_id'],
        'username': json['username'],
        'gender': json['gender'],
        'fullName': json['full_name'],
        'status': json['status'],
        'phoneNumber': json['phone_number'],
        'emailId': json['email_id'],
        'updatedOn': (json['updated_on'] == null ? null : new Date(json['updated_on'])),
        'createdOn': (new Date(json['created_on'])),
    };
}

export function VendorSchemaToJSON(json: any): VendorSchema {
    return VendorSchemaToJSONTyped(json, false);
}

export function VendorSchemaToJSONTyped(value?: VendorSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'business_id': value['businessId'],
        'username': value['username'],
        'gender': value['gender'],
        'full_name': value['fullName'],
        'status': value['status'],
        'phone_number': value['phoneNumber'],
        'email_id': value['emailId'],
        'updated_on': value['updatedOn'] == null ? value['updatedOn'] : value['updatedOn'].toISOString(),
        'created_on': value['createdOn'].toISOString(),
    };
}

