/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VendorRoleMapSchema
 */
export interface VendorRoleMapSchema {
    /**
     * 
     * @type {number}
     * @memberof VendorRoleMapSchema
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof VendorRoleMapSchema
     */
    businessId: number;
    /**
     * 
     * @type {number}
     * @memberof VendorRoleMapSchema
     */
    roleId: number;
    /**
     * 
     * @type {number}
     * @memberof VendorRoleMapSchema
     */
    vendorId: number;
    /**
     * 
     * @type {Date}
     * @memberof VendorRoleMapSchema
     */
    updatedOn: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof VendorRoleMapSchema
     */
    createdOn: Date;
}

/**
 * Check if a given object implements the VendorRoleMapSchema interface.
 */
export function instanceOfVendorRoleMapSchema(value: object): value is VendorRoleMapSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('businessId' in value) || value['businessId'] === undefined) return false;
    if (!('roleId' in value) || value['roleId'] === undefined) return false;
    if (!('vendorId' in value) || value['vendorId'] === undefined) return false;
    if (!('updatedOn' in value) || value['updatedOn'] === undefined) return false;
    if (!('createdOn' in value) || value['createdOn'] === undefined) return false;
    return true;
}

export function VendorRoleMapSchemaFromJSON(json: any): VendorRoleMapSchema {
    return VendorRoleMapSchemaFromJSONTyped(json, false);
}

export function VendorRoleMapSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): VendorRoleMapSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'businessId': json['business_id'],
        'roleId': json['role_id'],
        'vendorId': json['vendor_id'],
        'updatedOn': (json['updated_on'] == null ? null : new Date(json['updated_on'])),
        'createdOn': (new Date(json['created_on'])),
    };
}

export function VendorRoleMapSchemaToJSON(json: any): VendorRoleMapSchema {
    return VendorRoleMapSchemaToJSONTyped(json, false);
}

export function VendorRoleMapSchemaToJSONTyped(value?: VendorRoleMapSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'business_id': value['businessId'],
        'role_id': value['roleId'],
        'vendor_id': value['vendorId'],
        'updated_on': value['updatedOn'] == null ? value['updatedOn'] : value['updatedOn'].toISOString(),
        'created_on': value['createdOn'].toISOString(),
    };
}

