/* tslint:disable */
/* eslint-disable */
/**
 * Executive APP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VendorRoleSchema
 */
export interface VendorRoleSchema {
    /**
     * 
     * @type {number}
     * @memberof VendorRoleSchema
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof VendorRoleSchema
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof VendorRoleSchema
     */
    businessId: number;
    /**
     * 
     * @type {boolean}
     * @memberof VendorRoleSchema
     */
    manageToken: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof VendorRoleSchema
     */
    updateBusiness: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof VendorRoleSchema
     */
    createVendor: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof VendorRoleSchema
     */
    updateVendor: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof VendorRoleSchema
     */
    deleteVendor: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof VendorRoleSchema
     */
    createRole: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof VendorRoleSchema
     */
    updateRole: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof VendorRoleSchema
     */
    deleteRole: boolean;
    /**
     * 
     * @type {Date}
     * @memberof VendorRoleSchema
     */
    updatedOn: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof VendorRoleSchema
     */
    createdOn: Date;
}

/**
 * Check if a given object implements the VendorRoleSchema interface.
 */
export function instanceOfVendorRoleSchema(value: object): value is VendorRoleSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('businessId' in value) || value['businessId'] === undefined) return false;
    if (!('manageToken' in value) || value['manageToken'] === undefined) return false;
    if (!('updateBusiness' in value) || value['updateBusiness'] === undefined) return false;
    if (!('createVendor' in value) || value['createVendor'] === undefined) return false;
    if (!('updateVendor' in value) || value['updateVendor'] === undefined) return false;
    if (!('deleteVendor' in value) || value['deleteVendor'] === undefined) return false;
    if (!('createRole' in value) || value['createRole'] === undefined) return false;
    if (!('updateRole' in value) || value['updateRole'] === undefined) return false;
    if (!('deleteRole' in value) || value['deleteRole'] === undefined) return false;
    if (!('updatedOn' in value) || value['updatedOn'] === undefined) return false;
    if (!('createdOn' in value) || value['createdOn'] === undefined) return false;
    return true;
}

export function VendorRoleSchemaFromJSON(json: any): VendorRoleSchema {
    return VendorRoleSchemaFromJSONTyped(json, false);
}

export function VendorRoleSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): VendorRoleSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'businessId': json['business_id'],
        'manageToken': json['manage_token'],
        'updateBusiness': json['update_business'],
        'createVendor': json['create_vendor'],
        'updateVendor': json['update_vendor'],
        'deleteVendor': json['delete_vendor'],
        'createRole': json['create_role'],
        'updateRole': json['update_role'],
        'deleteRole': json['delete_role'],
        'updatedOn': (json['updated_on'] == null ? null : new Date(json['updated_on'])),
        'createdOn': (new Date(json['created_on'])),
    };
}

export function VendorRoleSchemaToJSON(json: any): VendorRoleSchema {
    return VendorRoleSchemaToJSONTyped(json, false);
}

export function VendorRoleSchemaToJSONTyped(value?: VendorRoleSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'business_id': value['businessId'],
        'manage_token': value['manageToken'],
        'update_business': value['updateBusiness'],
        'create_vendor': value['createVendor'],
        'update_vendor': value['updateVendor'],
        'delete_vendor': value['deleteVendor'],
        'create_role': value['createRole'],
        'update_role': value['updateRole'],
        'delete_role': value['deleteRole'],
        'updated_on': value['updatedOn'] == null ? value['updatedOn'] : value['updatedOn'].toISOString(),
        'created_on': value['createdOn'].toISOString(),
    };
}

